// Package infra holds the Postgres-backed implementation of the
// llm_provider domain. Queries are generated by sqlc — see queries.sql
// for the SQL surface; this file only owns the (de)serialisation between
// the generated row types and the domain model, plus the cryptobox
// sealing for api_key_encrypted.
//
// Encryption contract:
//   - CreateProvider / UpdateProvider treat the inbound Provider.ApiKey as
//     plaintext. Both methods seal it via the cryptobox before insert /
//     update. An empty ApiKey on UpdateProvider means "leave the stored
//     key unchanged".
//   - GetProviderByName / GetProviderByID / ListProviders return the
//     SEALED blob in Provider.ApiKey. It is the caller's job (the
//     llm_proxy) to decrypt; handlers in this module never surface the
//     field on the wire.
package infra

import (
	"context"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"time"

	"github.com/jackc/pgerrcode"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/hangrix/hangrix/apps/hangrix/internal/config"
	"github.com/hangrix/hangrix/apps/hangrix/internal/database"
	"github.com/hangrix/hangrix/apps/hangrix/internal/modules/llm_provider/domain"
	"github.com/hangrix/hangrix/apps/hangrix/internal/modules/llm_provider/infra/llmproviderdb"
	"github.com/hangrix/hangrix/pkg/cryptobox"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// PostgresRepo implements domain.Repo and domain.Lookup on a single pgx
// pool. The module binds the same instance to both interfaces.
type PostgresRepo struct {
	q    *llmproviderdb.Queries
	pool *pgxpool.Pool
	box  *cryptobox.Box
}

type PostgresRepoDeps struct {
	Pool   *pgxpool.Pool
	Config *config.Config
}

// NewPostgresRepo applies migrations and constructs the cryptobox up front
// so a malformed master key fails loudly at startup instead of on the first
// CreateProvider call. Mirrors the fail-loud pattern of the other modules'
// migration runners.
func NewPostgresRepo(deps *PostgresRepoDeps) *PostgresRepo {
	sub, err := fs.Sub(migrationsFS, "migrations")
	if err != nil {
		panic(fmt.Errorf("llm_provider migrations sub-fs: %w", err))
	}
	if err := database.Migrate(deps.Pool, sub, "goose_llm_provider", "."); err != nil {
		panic(fmt.Errorf("apply llm_provider migrations: %w", err))
	}
	box, err := cryptobox.New(deps.Config.LLM.EncryptionKey)
	if err != nil {
		panic(fmt.Errorf("llm_provider cryptobox: %w", err))
	}
	return &PostgresRepo{
		q:    llmproviderdb.New(deps.Pool),
		pool: deps.Pool,
		box:  box,
	}
}

// ---- providers ----

func (r *PostgresRepo) CreateProvider(ctx context.Context, p *domain.Provider) (*domain.Provider, error) {
	sealed, err := r.box.Encrypt(p.ApiKey)
	if err != nil {
		return nil, fmt.Errorf("seal api key: %w", err)
	}
	row, err := r.q.CreateProvider(ctx, llmproviderdb.CreateProviderParams{
		Name:            p.Name,
		Type:            string(p.Type),
		BaseUrl:         p.BaseURL,
		ApiKeyEncrypted: sealed,
		AllowedModels:   p.AllowedModels,
		CreatedBy:       p.CreatedBy,
	})
	if err != nil {
		if isUniqueViolation(err) {
			return nil, domain.ErrProviderConflict
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) UpdateProvider(ctx context.Context, p *domain.Provider) (*domain.Provider, error) {
	var sealedArg pgtype.Text
	if p.ApiKey != "" {
		s, err := r.box.Encrypt(p.ApiKey)
		if err != nil {
			return nil, fmt.Errorf("seal api key: %w", err)
		}
		sealedArg = pgtype.Text{String: s, Valid: true}
	}
	row, err := r.q.UpdateProvider(ctx, llmproviderdb.UpdateProviderParams{
		ID:              p.ID,
		BaseUrl:         p.BaseURL,
		ApiKeyEncrypted: sealedArg,
		AllowedModels:   p.AllowedModels,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrProviderNotFound
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) GetProviderByName(ctx context.Context, name string) (*domain.Provider, error) {
	row, err := r.q.GetProviderByName(ctx, name)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrProviderNotFound
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) GetProviderByID(ctx context.Context, id int64) (*domain.Provider, error) {
	row, err := r.q.GetProviderByID(ctx, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrProviderNotFound
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) ListProviders(ctx context.Context) ([]*domain.Provider, error) {
	rows, err := r.q.ListProviders(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*domain.Provider, 0, len(rows))
	for _, row := range rows {
		out = append(out, providerFromRow(row))
	}
	return out, nil
}

func (r *PostgresRepo) DeleteProvider(ctx context.Context, id int64) error {
	n, err := r.q.DeleteProvider(ctx, id)
	if err != nil {
		return err
	}
	if n == 0 {
		return domain.ErrProviderNotFound
	}
	return nil
}

// FindProviderByModel returns the lowest-id provider whose AllowedModels
// array contains `model`. Two-call admin pages can rely on the
// deterministic ordering — id ASC means "first registered wins" when
// multiple providers list the same model. Operators wanting a different
// preference order can simply trim allow-lists rather than introducing a
// priority field today.
func (r *PostgresRepo) FindProviderByModel(ctx context.Context, model string) (*domain.Provider, error) {
	if model == "" {
		return nil, domain.ErrNoModelMatch
	}
	row, err := r.q.FindProviderByModel(ctx, model)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrNoModelMatch
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

// ---- usage log ----

func (r *PostgresRepo) RecordUsage(ctx context.Context, u *domain.UsageRecord) error {
	var sessionArg pgtype.Int8
	if u.SessionID != nil {
		sessionArg = pgtype.Int8{Int64: *u.SessionID, Valid: true}
	}
	return r.q.RecordUsage(ctx, llmproviderdb.RecordUsageParams{
		SessionID:        sessionArg,
		ProviderID:       u.ProviderID,
		Model:            u.Model,
		PromptTokens:     u.PromptTokens,
		CompletionTokens: u.CompletionTokens,
		TotalTokens:      u.TotalTokens,
		LatencyMs:        u.LatencyMS,
		StatusCode:       u.StatusCode,
		ErrorMessage:     u.ErrorMessage,
		RequestPath:      u.RequestPath,
	})
}

// ListUsage is a read helper outside the Repo interface — the admin handler
// renders it; the proxy never calls it. since/limit are clamped by the caller.
func (r *PostgresRepo) ListUsage(ctx context.Context, providerID *int64, since *time.Time, limit int) ([]*UsageRow, error) {
	var (
		provArg  pgtype.Int8
		sinceArg pgtype.Timestamptz
	)
	if providerID != nil {
		provArg = pgtype.Int8{Int64: *providerID, Valid: true}
	}
	if since != nil {
		sinceArg = pgtype.Timestamptz{Time: *since, Valid: true}
	}
	rows, err := r.q.ListUsage(ctx, llmproviderdb.ListUsageParams{
		ProviderID: provArg,
		Since:      sinceArg,
		Lim:        int32(limit),
	})
	if err != nil {
		return nil, err
	}
	out := make([]*UsageRow, 0, len(rows))
	for _, row := range rows {
		ur := &UsageRow{
			ID:               row.ID,
			ProviderID:       row.ProviderID,
			ProviderName:     row.ProviderName,
			Model:            row.Model,
			PromptTokens:     row.PromptTokens,
			CompletionTokens: row.CompletionTokens,
			TotalTokens:      row.TotalTokens,
			LatencyMS:        row.LatencyMs,
			StatusCode:       row.StatusCode,
			ErrorMessage:     row.ErrorMessage,
			RequestPath:      row.RequestPath,
			CreatedAt:        row.CreatedAt.Time,
		}
		if row.SessionID.Valid {
			v := row.SessionID.Int64
			ur.SessionID = &v
		}
		out = append(out, ur)
	}
	return out, nil
}

// UsageRow is the read-side projection returned by ListUsage. It mirrors
// domain.UsageRecord plus a denormalized provider name for display and the
// row id/timestamp the writer never sees.
type UsageRow struct {
	ID               int64
	SessionID        *int64
	ProviderID       int64
	ProviderName     string
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMS        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
	CreatedAt        time.Time
}

// ---- row → domain ----

func providerFromRow(r llmproviderdb.LlmProvider) *domain.Provider {
	return &domain.Provider{
		ID:            r.ID,
		Name:          r.Name,
		Type:          domain.ProviderType(r.Type),
		BaseURL:       r.BaseUrl,
		ApiKey:        r.ApiKeyEncrypted,
		AllowedModels: r.AllowedModels,
		CreatedBy:     r.CreatedBy,
		CreatedAt:     r.CreatedAt.Time,
		UpdatedAt:     r.UpdatedAt.Time,
	}
}

// ---- pgx error helpers ----

func isUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == pgerrcode.UniqueViolation
}
