// Package infra holds the Postgres-backed implementation of the
// llm_provider domain. Queries are generated by sqlc — see queries.sql
// for the SQL surface; this file only owns the (de)serialisation between
// the generated row types and the domain model, plus the cryptobox
// sealing for api_key_encrypted.
//
// Encryption contract:
//   - CreateProvider / UpdateProvider treat the inbound Provider.ApiKey as
//     plaintext. Both methods seal it via the cryptobox before insert /
//     update. An empty ApiKey on UpdateProvider means "leave the stored
//     key unchanged".
//   - GetProviderByName / GetProviderByID / ListProviders return the
//     SEALED blob in Provider.ApiKey. It is the caller's job (the
//     llm_proxy) to decrypt; handlers in this module never surface the
//     field on the wire.
package infra

import (
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/hangrix/hangrix/apps/hangrix/internal/config"
	"github.com/hangrix/hangrix/apps/hangrix/internal/database"
	"github.com/hangrix/hangrix/apps/hangrix/internal/modules/llm_provider/domain"
	"github.com/hangrix/hangrix/apps/hangrix/internal/modules/llm_provider/infra/llmproviderdb"
	"github.com/hangrix/hangrix/pkg/cryptobox"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// PostgresRepo implements domain.Repo and domain.Lookup on a single pgx
// pool. The module binds the same instance to both interfaces.
type PostgresRepo struct {
	q    *llmproviderdb.Queries
	pool *pgxpool.Pool
	box  *cryptobox.Box
}

type PostgresRepoDeps struct {
	Pool   *pgxpool.Pool
	Config *config.Config
}

// NewPostgresRepo applies migrations and constructs the cryptobox up front
// so a malformed master key fails loudly at startup instead of on the first
// CreateProvider call. Mirrors the fail-loud pattern of the other modules'
// migration runners.
func NewPostgresRepo(deps *PostgresRepoDeps) *PostgresRepo {
	sub, err := fs.Sub(migrationsFS, "migrations")
	if err != nil {
		panic(fmt.Errorf("llm_provider migrations sub-fs: %w", err))
	}
	if err := database.Migrate(deps.Pool, sub, "goose_llm_provider", "."); err != nil {
		panic(fmt.Errorf("apply llm_provider migrations: %w", err))
	}
	box, err := cryptobox.New(deps.Config.LLM.EncryptionKey)
	if err != nil {
		panic(fmt.Errorf("llm_provider cryptobox: %w", err))
	}
	return &PostgresRepo{
		q:    llmproviderdb.New(deps.Pool),
		pool: deps.Pool,
		box:  box,
	}
}

// ---- providers ----

func (r *PostgresRepo) CreateProvider(ctx context.Context, p *domain.Provider) (*domain.Provider, error) {
	sealed, err := r.box.Encrypt(p.ApiKey)
	if err != nil {
		return nil, fmt.Errorf("seal api key: %w", err)
	}
	row, err := r.q.CreateProvider(ctx, llmproviderdb.CreateProviderParams{
		Name:            p.Name,
		Type:            string(p.Type),
		BaseUrl:         p.BaseURL,
		ApiKeyEncrypted: sealed,
		AllowedModels:   p.AllowedModels,
		ActorID:         p.ActorID,
	})
	if err != nil {
		if database.IsUniqueViolation(err) {
			return nil, domain.ErrProviderConflict
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) UpdateProvider(ctx context.Context, p *domain.Provider) (*domain.Provider, error) {
	var sealedArg pgtype.Text
	if p.ApiKey != "" {
		s, err := r.box.Encrypt(p.ApiKey)
		if err != nil {
			return nil, fmt.Errorf("seal api key: %w", err)
		}
		sealedArg = pgtype.Text{String: s, Valid: true}
	}
	row, err := r.q.UpdateProvider(ctx, llmproviderdb.UpdateProviderParams{
		ID:              p.ID,
		BaseUrl:         p.BaseURL,
		ApiKeyEncrypted: sealedArg,
		AllowedModels:   p.AllowedModels,
		Disabled:        p.Disabled,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrProviderNotFound
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) GetProviderByName(ctx context.Context, name string) (*domain.Provider, error) {
	row, err := r.q.GetProviderByName(ctx, name)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrProviderNotFound
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) GetProviderByID(ctx context.Context, id int64) (*domain.Provider, error) {
	row, err := r.q.GetProviderByID(ctx, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrProviderNotFound
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) ListProviders(ctx context.Context) ([]*domain.Provider, error) {
	rows, err := r.q.ListProviders(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*domain.Provider, 0, len(rows))
	for _, row := range rows {
		out = append(out, providerFromRow(row))
	}
	return out, nil
}

// SetProviderDisabled flips the disabled flag without touching the rest of
// the row. Returns the updated provider (sealed key still opaque). The
// admin handler uses this as a one-call toggle so it doesn't have to read
// the row, mutate, and write it back.
func (r *PostgresRepo) SetProviderDisabled(ctx context.Context, id int64, disabled bool) (*domain.Provider, error) {
	row, err := r.q.SetProviderDisabled(ctx, llmproviderdb.SetProviderDisabledParams{
		ID:       id,
		Disabled: disabled,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrProviderNotFound
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) DeleteProvider(ctx context.Context, id int64) error {
	n, err := r.q.DeleteProvider(ctx, id)
	if err != nil {
		return err
	}
	if n == 0 {
		return domain.ErrProviderNotFound
	}
	return nil
}

// FindProviderByModel returns the lowest-id provider whose AllowedModels
// array contains `model`. Two-call admin pages can rely on the
// deterministic ordering — id ASC means "first registered wins" when
// multiple providers list the same model. Operators wanting a different
// preference order can simply trim allow-lists rather than introducing a
// priority field today.
func (r *PostgresRepo) FindProviderByModel(ctx context.Context, model string) (*domain.Provider, error) {
	if model == "" {
		return nil, domain.ErrNoModelMatch
	}
	row, err := r.q.FindProviderByModel(ctx, model)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrNoModelMatch
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

// ---- usage log ----

func (r *PostgresRepo) RecordUsage(ctx context.Context, u *domain.UsageRecord) error {
	var sessionArg pgtype.Int8
	if u.SessionID != nil {
		sessionArg = pgtype.Int8{Int64: *u.SessionID, Valid: true}
	}
	return r.q.RecordUsage(ctx, llmproviderdb.RecordUsageParams{
		SessionID:        sessionArg,
		ProviderID:       u.ProviderID,
		Model:            u.Model,
		PromptTokens:     u.PromptTokens,
		CompletionTokens: u.CompletionTokens,
		TotalTokens:      u.TotalTokens,
		LatencyMs:        u.LatencyMS,
		StatusCode:       u.StatusCode,
		ErrorMessage:     u.ErrorMessage,
		RequestPath:      u.RequestPath,
		RequestBody:      u.RequestBody,
		ResponseBody:     u.ResponseBody,
	})
}

// ListUsage is a read helper outside the Repo interface — the admin handler
// renders it; the proxy never calls it. since/limit/offset are clamped by
// the caller; offset paginates a window over the same filter set, and
// CountUsage exposes the matching total so the UI can render a page count.
func (r *PostgresRepo) ListUsage(ctx context.Context, providerID *int64, since *time.Time, offset, limit int) ([]*UsageRow, error) {
	provArg, sinceArg := usageFilterArgs(providerID, since)
	rows, err := r.q.ListUsage(ctx, llmproviderdb.ListUsageParams{
		ProviderID: provArg,
		Since:      sinceArg,
		Off:        int32(offset),
		Lim:        int32(limit),
	})
	if err != nil {
		return nil, err
	}
	out := make([]*UsageRow, 0, len(rows))
	for _, row := range rows {
		ur := &UsageRow{
			ID:               row.ID,
			ProviderID:       row.ProviderID,
			ProviderName:     row.ProviderName,
			Model:            row.Model,
			PromptTokens:     row.PromptTokens,
			CompletionTokens: row.CompletionTokens,
			TotalTokens:      row.TotalTokens,
			LatencyMS:        row.LatencyMs,
			StatusCode:       row.StatusCode,
			ErrorMessage:     row.ErrorMessage,
			RequestPath:      row.RequestPath,
			CreatedAt:        row.CreatedAt.Time,
		}
		if row.SessionID.Valid {
			v := row.SessionID.Int64
			ur.SessionID = &v
		}
		out = append(out, ur)
	}
	return out, nil
}

// CountUsage returns the row count matching the same filter set as
// ListUsage — the admin page pairs the two to drive its pager.
func (r *PostgresRepo) CountUsage(ctx context.Context, providerID *int64, since *time.Time) (int64, error) {
	provArg, sinceArg := usageFilterArgs(providerID, since)
	return r.q.CountUsage(ctx, llmproviderdb.CountUsageParams{
		ProviderID: provArg,
		Since:      sinceArg,
	})
}

func usageFilterArgs(providerID *int64, since *time.Time) (pgtype.Int8, pgtype.Timestamptz) {
	var (
		provArg  pgtype.Int8
		sinceArg pgtype.Timestamptz
	)
	if providerID != nil {
		provArg = pgtype.Int8{Int64: *providerID, Valid: true}
	}
	if since != nil {
		sinceArg = pgtype.Timestamptz{Time: *since, Valid: true}
	}
	return provArg, sinceArg
}

// UsageRow is the read-side projection returned by ListUsage. It mirrors
// domain.UsageRecord plus a denormalized provider name for display and the
// row id/timestamp the writer never sees.
type UsageRow struct {
	ID               int64
	SessionID        *int64
	ProviderID       int64
	ProviderName     string
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMS        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
	CreatedAt        time.Time
}

// UsageDetailRow is the single-row read model returned by GetUsageByID.
// It mirrors UsageRow but also includes RequestBody / ResponseBody.
type UsageDetailRow struct {
	ID               int64
	SessionID        *int64
	ProviderID       int64
	ProviderName     string
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMS        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
	RequestBody      string
	ResponseBody     string
	CreatedAt        time.Time
}

// GetUsageByID returns a single usage row including the large body
// columns. Returns pgx.ErrNoRows when the id doesn't exist.
func (r *PostgresRepo) GetUsageByID(ctx context.Context, id int64) (*UsageDetailRow, error) {
	row, err := r.q.GetUsageByID(ctx, id)
	if err != nil {
		return nil, err
	}
	ur := &UsageDetailRow{
		ID:               row.ID,
		ProviderID:       row.ProviderID,
		ProviderName:     row.ProviderName,
		Model:            row.Model,
		PromptTokens:     row.PromptTokens,
		CompletionTokens: row.CompletionTokens,
		TotalTokens:      row.TotalTokens,
		LatencyMS:        row.LatencyMs,
		StatusCode:       row.StatusCode,
		ErrorMessage:     row.ErrorMessage,
		RequestPath:      row.RequestPath,
		RequestBody:      row.RequestBody,
		ResponseBody:     row.ResponseBody,
		CreatedAt:        row.CreatedAt.Time,
	}
	if row.SessionID.Valid {
		v := row.SessionID.Int64
		ur.SessionID = &v
	}
	return ur, nil
}

// ---- export ----

const exportUsagePageSize = 500

// ExportUsageCSV pages through the usage log in small batches and writes
// them as CSV to w. Only summary columns are included (no request_body /
// response_body).
func (r *PostgresRepo) ExportUsageCSV(ctx context.Context, w io.Writer, providerID *int64, since *time.Time) error {
	provArg, sinceArg := usageFilterArgs(providerID, since)

	// BOM-free; the ZIP content-type declares UTF-8.
	if _, err := io.WriteString(w, "created_at,provider_name,model,prompt_tokens,completion_tokens,total_tokens,latency_ms,status_code,session_id\n"); err != nil {
		return err
	}

	for offset := 0; ; offset += exportUsagePageSize {
		rows, err := r.q.ExportUsageCSV(ctx, llmproviderdb.ExportUsageCSVParams{
			ProviderID: provArg,
			Since:      sinceArg,
			Lim:        exportUsagePageSize,
			Off:        int32(offset),
		})
		if err != nil {
			return fmt.Errorf("export csv query: %w", err)
		}
		if len(rows) == 0 {
			return nil
		}

		for _, row := range rows {
			var sid string
			if row.SessionID.Valid {
				sid = fmt.Sprintf("%d", row.SessionID.Int64)
			}
			line := fmt.Sprintf("%s,%s,%s,%d,%d,%d,%d,%d,%s\n",
				row.CreatedAt.Time.UTC().Format(time.RFC3339),
				csvEscape(row.ProviderName),
				csvEscape(row.Model),
				row.PromptTokens,
				row.CompletionTokens,
				row.TotalTokens,
				row.LatencyMs,
				row.StatusCode,
				sid,
			)
			if _, err := io.WriteString(w, line); err != nil {
				return err
			}
		}
		if len(rows) < exportUsagePageSize {
			return nil
		}
	}
}

// ExportUsageJSONL pages through the full usage log in small batches and
// writes them as JSONL (one JSON object per line) to w. All columns are
// included, including request_body and response_body.
func (r *PostgresRepo) ExportUsageJSONL(ctx context.Context, w io.Writer, providerID *int64, since *time.Time) error {
	provArg, sinceArg := usageFilterArgs(providerID, since)

	for offset := 0; ; offset += exportUsagePageSize {
		rows, err := r.q.ExportUsageJSONL(ctx, llmproviderdb.ExportUsageJSONLParams{
			ProviderID: provArg,
			Since:      sinceArg,
			Lim:        exportUsagePageSize,
			Off:        int32(offset),
		})
		if err != nil {
			return fmt.Errorf("export jsonl query: %w", err)
		}
		if len(rows) == 0 {
			return nil
		}

		for _, row := range rows {
			obj := exportJSONLRow{
				CreatedAt:        row.CreatedAt.Time.UTC().Format(time.RFC3339),
				ProviderName:     row.ProviderName,
				Model:            row.Model,
				PromptTokens:     row.PromptTokens,
				CompletionTokens: row.CompletionTokens,
				TotalTokens:      row.TotalTokens,
				LatencyMS:        row.LatencyMs,
				StatusCode:       row.StatusCode,
				RequestPath:      row.RequestPath,
				ErrorMessage:     row.ErrorMessage,
				RequestBody:      row.RequestBody,
				ResponseBody:     row.ResponseBody,
			}
			if row.SessionID.Valid {
				v := row.SessionID.Int64
				obj.SessionID = &v
			}

			b, err := json.Marshal(obj)
			if err != nil {
				return fmt.Errorf("export jsonl marshal: %w", err)
			}
			if _, err := w.Write(append(b, '\n')); err != nil {
				return err
			}
		}
		if len(rows) < exportUsagePageSize {
			return nil
		}
	}
}

type exportJSONLRow struct {
	CreatedAt        string `json:"created_at"`
	ProviderName     string `json:"provider_name"`
	Model            string `json:"model"`
	PromptTokens     int32  `json:"prompt_tokens"`
	CompletionTokens int32  `json:"completion_tokens"`
	TotalTokens      int32  `json:"total_tokens"`
	LatencyMS        int32  `json:"latency_ms"`
	StatusCode       int32  `json:"status_code"`
	ErrorMessage     string `json:"error_message"`
	RequestPath      string `json:"request_path"`
	RequestBody      string `json:"request_body"`
	ResponseBody     string `json:"response_body"`
	SessionID        *int64 `json:"session_id,omitempty"`
}

// csvEscape escapes a string for CSV: wraps in double-quotes and doubles any
// embedded double-quotes when the value contains a comma, quote, or newline.
func csvEscape(s string) string {
	for i := 0; i < len(s); i++ {
		if s[i] == ',' || s[i] == '"' || s[i] == '\n' || s[i] == '\r' {
			quoted := make([]byte, 0, len(s)+4)
			quoted = append(quoted, '"')
			for j := 0; j < len(s); j++ {
				if s[j] == '"' {
					quoted = append(quoted, '"', '"')
				} else {
					quoted = append(quoted, s[j])
				}
			}
			quoted = append(quoted, '"')
			return string(quoted)
		}
	}
	return s
}

// ---- cleanup ----

// DeleteUsageBefore hard-deletes usage-log rows whose created_at is strictly
// before cutoff and returns how many rows were removed. Called only by the
// background reaper (service/reaper.go); not part of the domain.Repo interface
// because admin handlers should never trigger mass deletion.
func (r *PostgresRepo) DeleteUsageBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	return r.q.DeleteUsageBefore(ctx, pgtype.Timestamptz{Time: cutoff, Valid: true})
}

// ---- row → domain ----

func providerFromRow(r llmproviderdb.LlmProvider) *domain.Provider {
	return &domain.Provider{
		ID:            r.ID,
		Name:          r.Name,
		Type:          domain.ProviderType(r.Type),
		BaseURL:       r.BaseUrl,
		ApiKey:        r.ApiKeyEncrypted,
		AllowedModels: r.AllowedModels,
		Disabled:      r.Disabled,
		ActorID:       r.ActorID,
		CreatedAt:     r.CreatedAt.Time,
		UpdatedAt:     r.UpdatedAt.Time,
	}
}

// ---- pgx error helpers ----
