// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package issuedb

import (
	"context"
)

// iteratorForCreatePatchFiles implements pgx.CopyFromSource.
type iteratorForCreatePatchFiles struct {
	rows                 []CreatePatchFilesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePatchFiles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePatchFiles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SubmissionID,
		r.rows[0].Seq,
		r.rows[0].FileName,
		r.rows[0].PatchText,
		r.rows[0].Subject,
	}, nil
}

func (r iteratorForCreatePatchFiles) Err() error {
	return nil
}

func (q *Queries) CreatePatchFiles(ctx context.Context, arg []CreatePatchFilesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"issue_patch_files"}, []string{"submission_id", "seq", "file_name", "patch_text", "subject"}, &iteratorForCreatePatchFiles{rows: arg})
}
