// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package issuedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BranchProtection struct {
	ID               int64
	RepoID           int64
	Pattern          string
	ForbidForcePush  bool
	ForbidDelete     bool
	ForbidDirectPush bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Issue struct {
	ID             int64
	RepoID         int64
	Number         int64
	AuthorID       pgtype.Int8
	Title          string
	Body           string
	State          string
	BranchName     string
	BaseBranch     string
	HeadSha        string
	MergeCommitSha string
	MergedAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ParentID       pgtype.Int8
	ParentNumber   int64
	AgentRole      string
}

type IssueAttachment struct {
	ID               int64
	RepoID           int64
	IssueID          int64
	CommentID        pgtype.Int8
	AuthorID         pgtype.Int8
	AgentRole        string
	StorageKey       string
	OriginalName     string
	SizeBytes        int64
	MimeType         string
	DetectedMimeType string
	Sha256           string
	Kind             string
	Status           string
	CreatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	DisplayName      string
	Inline           bool
}

type IssueComment struct {
	ID        int64
	IssueID   int64
	AuthorID  pgtype.Int8
	Body      string
	FilePath  string
	Line      int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	AgentRole string
}

type IssueCounter struct {
	RepoID int64
	Next   int64
}

type IssueEvent struct {
	ID        int64
	IssueID   int64
	Kind      string
	Payload   []byte
	ActorID   pgtype.Int8
	CreatedAt pgtype.Timestamptz
	AgentRole string
}

type Organization struct {
	ID          int64
	Name        string
	DisplayName string
	Description string
	AvatarUrl   string
	CreatedBy   int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type OrganizationMember struct {
	OrgID   int64
	UserID  int64
	Role    string
	AddedBy int64
	AddedAt pgtype.Timestamptz
}

type Repo struct {
	ID            int64
	OwnerUserID   pgtype.Int8
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerOrgID    pgtype.Int8
}

type RepoMember struct {
	RepoID  int64
	UserID  int64
	Role    string
	AddedBy int64
	AddedAt pgtype.Timestamptz
}

type RepoVariable struct {
	ID        int64
	RepoID    int64
	Name      string
	Value     string
	Kind      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
