// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package issuedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIssues = `-- name: CountIssues :one
SELECT COUNT(*) FROM issues i
WHERE i.repo_id = $1
  AND ($2::TEXT IS NULL OR i.state = $2)
`

type CountIssuesParams struct {
	RepoID int64
	State  pgtype.Text
}

func (q *Queries) CountIssues(ctx context.Context, arg CountIssuesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIssues, arg.RepoID, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one

INSERT INTO issue_attachments (
    repo_id, issue_id, author_id, agent_role, storage_key,
    original_name, display_name, size_bytes, mime_type, detected_mime_type,
    sha256, kind, inline, status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id, created_at
`

type CreateAttachmentParams struct {
	RepoID           int64
	IssueID          int64
	AuthorID         pgtype.Int8
	AgentRole        string
	StorageKey       string
	OriginalName     string
	DisplayName      string
	SizeBytes        int64
	MimeType         string
	DetectedMimeType string
	Sha256           string
	Kind             string
	Inline           bool
	Status           string
}

type CreateAttachmentRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

// ---- issue_attachments ----
// Human path: sqlc.narg('author_id'), agent_role=”
// Agent path: author_id=NULL (omit), agent_role with the role key.
func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (CreateAttachmentRow, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.RepoID,
		arg.IssueID,
		arg.AuthorID,
		arg.AgentRole,
		arg.StorageKey,
		arg.OriginalName,
		arg.DisplayName,
		arg.SizeBytes,
		arg.MimeType,
		arg.DetectedMimeType,
		arg.Sha256,
		arg.Kind,
		arg.Inline,
		arg.Status,
	)
	var i CreateAttachmentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createComment = `-- name: CreateComment :one

INSERT INTO issue_comments (
    issue_id, author_id, agent_role, body, file_path, line
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at
`

type CreateCommentParams struct {
	IssueID   int64
	AuthorID  pgtype.Int8
	AgentRole string
	Body      string
	FilePath  string
	Line      int32
}

type CreateCommentRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// ---- issue_comments ----
// author_id and agent_role are mutually exclusive (CHECK constraint at
// the table level). Callers pass exactly one — sqlc.narg('author_id')
// for the human path, sqlc.arg('agent_role') for the agent path; the
// other gets the zero value.
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.IssueID,
		arg.AuthorID,
		arg.AgentRole,
		arg.Body,
		arg.FilePath,
		arg.Line,
	)
	var i CreateCommentRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createEvent = `-- name: CreateEvent :one

INSERT INTO issue_events (
    issue_id, kind, payload, actor_id, agent_role
)
VALUES (
    $1,
    $2,
    $3::jsonb,
    $4,
    $5
)
RETURNING id, created_at
`

type CreateEventParams struct {
	IssueID   int64
	Kind      string
	Payload   []byte
	ActorID   pgtype.Int8
	AgentRole string
}

type CreateEventRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

// ---- issue_events ----
// actor_id is nullable for system-generated events (M5+); agent_role
// is the role-key string for agent-generated events. Both can be set
// on a row to attribute a system-side action to a specific agent role.
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.IssueID,
		arg.Kind,
		arg.Payload,
		arg.ActorID,
		arg.AgentRole,
	)
	var i CreateEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createIssue = `-- name: CreateIssue :one

INSERT INTO issues (
    repo_id, number, author_id, agent_role, title, body, branch_name,
    base_branch, parent_id, parent_number
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, state, created_at, updated_at
`

type CreateIssueParams struct {
	RepoID       int64
	Number       int64
	AuthorID     pgtype.Int8
	AgentRole    string
	Title        string
	Body         string
	BranchName   string
	BaseBranch   string
	ParentID     pgtype.Int8
	ParentNumber int64
}

type CreateIssueRow struct {
	ID        int64
	State     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// ---- issues ----
// author_id and agent_role are mutually exclusive (CHECK constraint).
// Human path: sqlc.narg('author_id') with the user's ID, agent_role=”.
// Agent path: author_id=NULL (omit), agent_role with the role key.
func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (CreateIssueRow, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.RepoID,
		arg.Number,
		arg.AuthorID,
		arg.AgentRole,
		arg.Title,
		arg.Body,
		arg.BranchName,
		arg.BaseBranch,
		arg.ParentID,
		arg.ParentNumber,
	)
	var i CreateIssueRow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT a.id, a.repo_id, a.issue_id,
       COALESCE(a.comment_id, 0)::BIGINT AS comment_id,
       COALESCE(a.author_id, 0)::BIGINT   AS author_id,
       a.agent_role, a.storage_key, a.original_name,
       a.display_name, a.size_bytes, a.mime_type, a.detected_mime_type,
       a.sha256, a.kind, a.inline, a.status,
       a.created_at, a.deleted_at
FROM issue_attachments a
WHERE a.id = $1
`

type GetAttachmentRow struct {
	ID               int64
	RepoID           int64
	IssueID          int64
	CommentID        int64
	AuthorID         int64
	AgentRole        string
	StorageKey       string
	OriginalName     string
	DisplayName      string
	SizeBytes        int64
	MimeType         string
	DetectedMimeType string
	Sha256           string
	Kind             string
	Inline           bool
	Status           string
	CreatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

func (q *Queries) GetAttachment(ctx context.Context, id int64) (GetAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i GetAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.IssueID,
		&i.CommentID,
		&i.AuthorID,
		&i.AgentRole,
		&i.StorageKey,
		&i.OriginalName,
		&i.DisplayName,
		&i.SizeBytes,
		&i.MimeType,
		&i.DetectedMimeType,
		&i.Sha256,
		&i.Kind,
		&i.Inline,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.issue_id,
       COALESCE(c.author_id, 0)::BIGINT AS author_id,
       COALESCE(u.username, '')         AS author_name,
       c.agent_role, c.body, c.file_path, c.line,
       c.created_at, c.updated_at
FROM issue_comments c
LEFT JOIN users u ON u.id = c.author_id
WHERE c.id = $1
`

type GetCommentByIDRow struct {
	ID         int64
	IssueID    int64
	AuthorID   int64
	AuthorName string
	AgentRole  string
	Body       string
	FilePath   string
	Line       int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) GetCommentByID(ctx context.Context, id int64) (GetCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.AuthorName,
		&i.AgentRole,
		&i.Body,
		&i.FilePath,
		&i.Line,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContribution = `-- name: GetContribution :one
SELECT id, repo_id, issue_id, session_id, agent_role, ref_name,
       head_sha, base_sha, title, description, status, mergeable,
       merge_mode, changed_paths, files, additions, deletions,
       merged_commit_sha, merged_at, created_at, updated_at
FROM contributions
WHERE id = $1
`

func (q *Queries) GetContribution(ctx context.Context, id int64) (Contribution, error) {
	row := q.db.QueryRow(ctx, getContribution, id)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.IssueID,
		&i.SessionID,
		&i.AgentRole,
		&i.RefName,
		&i.HeadSha,
		&i.BaseSha,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Mergeable,
		&i.MergeMode,
		&i.ChangedPaths,
		&i.Files,
		&i.Additions,
		&i.Deletions,
		&i.MergedCommitSha,
		&i.MergedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContributionByRef = `-- name: GetContributionByRef :one
SELECT id, repo_id, issue_id, session_id, agent_role, ref_name,
       head_sha, base_sha, title, description, status, mergeable,
       merge_mode, changed_paths, files, additions, deletions,
       merged_commit_sha, merged_at, created_at, updated_at
FROM contributions
WHERE issue_id = $1 AND ref_name = $2
`

type GetContributionByRefParams struct {
	IssueID int64
	RefName string
}

func (q *Queries) GetContributionByRef(ctx context.Context, arg GetContributionByRefParams) (Contribution, error) {
	row := q.db.QueryRow(ctx, getContributionByRef, arg.IssueID, arg.RefName)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.IssueID,
		&i.SessionID,
		&i.AgentRole,
		&i.RefName,
		&i.HeadSha,
		&i.BaseSha,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Mergeable,
		&i.MergeMode,
		&i.ChangedPaths,
		&i.Files,
		&i.Additions,
		&i.Deletions,
		&i.MergedCommitSha,
		&i.MergedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT e.id, e.issue_id, e.kind, e.payload,
       COALESCE(e.actor_id, 0)::BIGINT AS actor_id,
       COALESCE(u.username, '')        AS actor_name,
       e.agent_role, e.created_at
FROM issue_events e
LEFT JOIN users u ON u.id = e.actor_id
WHERE e.id = $1
`

type GetEventByIDRow struct {
	ID        int64
	IssueID   int64
	Kind      string
	Payload   []byte
	ActorID   int64
	ActorName string
	AgentRole string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetEventByID(ctx context.Context, id int64) (GetEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Kind,
		&i.Payload,
		&i.ActorID,
		&i.ActorName,
		&i.AgentRole,
		&i.CreatedAt,
	)
	return i, err
}

const getIssueByNumber = `-- name: GetIssueByNumber :one
SELECT i.id, i.repo_id, i.number,
       COALESCE(i.author_id, 0)::BIGINT AS author_id,
       COALESCE(u.username, '')         AS author_name,
       i.agent_role, i.title, i.body, i.state,
       i.branch_name, i.base_branch,
       i.head_sha, i.merge_commit_sha, i.merged_at,
       COALESCE(i.parent_id, 0)::BIGINT AS parent_id, i.parent_number,
       i.created_at, i.updated_at
FROM issues i
LEFT JOIN users u ON u.id = i.author_id
WHERE i.repo_id = $1 AND i.number = $2
`

type GetIssueByNumberParams struct {
	RepoID int64
	Number int64
}

type GetIssueByNumberRow struct {
	ID             int64
	RepoID         int64
	Number         int64
	AuthorID       int64
	AuthorName     string
	AgentRole      string
	Title          string
	Body           string
	State          string
	BranchName     string
	BaseBranch     string
	HeadSha        string
	MergeCommitSha string
	MergedAt       pgtype.Timestamptz
	ParentID       int64
	ParentNumber   int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetIssueByNumber(ctx context.Context, arg GetIssueByNumberParams) (GetIssueByNumberRow, error) {
	row := q.db.QueryRow(ctx, getIssueByNumber, arg.RepoID, arg.Number)
	var i GetIssueByNumberRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Number,
		&i.AuthorID,
		&i.AuthorName,
		&i.AgentRole,
		&i.Title,
		&i.Body,
		&i.State,
		&i.BranchName,
		&i.BaseBranch,
		&i.HeadSha,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ParentID,
		&i.ParentNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT a.id, a.repo_id, a.issue_id,
       COALESCE(a.comment_id, 0)::BIGINT AS comment_id,
       COALESCE(a.author_id, 0)::BIGINT   AS author_id,
       a.agent_role, a.storage_key, a.original_name,
       a.display_name, a.size_bytes, a.mime_type, a.detected_mime_type,
       a.sha256, a.kind, a.inline, a.status,
       a.created_at, a.deleted_at
FROM issue_attachments a
WHERE a.issue_id = $1
  AND ($2::BIGINT IS NULL OR a.comment_id = $2)
ORDER BY a.created_at, a.id
`

type ListAttachmentsParams struct {
	IssueID   int64
	CommentID pgtype.Int8
}

type ListAttachmentsRow struct {
	ID               int64
	RepoID           int64
	IssueID          int64
	CommentID        int64
	AuthorID         int64
	AgentRole        string
	StorageKey       string
	OriginalName     string
	DisplayName      string
	SizeBytes        int64
	MimeType         string
	DetectedMimeType string
	Sha256           string
	Kind             string
	Inline           bool
	Status           string
	CreatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

func (q *Queries) ListAttachments(ctx context.Context, arg ListAttachmentsParams) ([]ListAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listAttachments, arg.IssueID, arg.CommentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsRow{}
	for rows.Next() {
		var i ListAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.IssueID,
			&i.CommentID,
			&i.AuthorID,
			&i.AgentRole,
			&i.StorageKey,
			&i.OriginalName,
			&i.DisplayName,
			&i.SizeBytes,
			&i.MimeType,
			&i.DetectedMimeType,
			&i.Sha256,
			&i.Kind,
			&i.Inline,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT c.id, c.issue_id,
       COALESCE(c.author_id, 0)::BIGINT AS author_id,
       COALESCE(u.username, '')         AS author_name,
       c.agent_role, c.body, c.file_path, c.line,
       c.created_at, c.updated_at
FROM issue_comments c
LEFT JOIN users u ON u.id = c.author_id
WHERE c.issue_id = $1
ORDER BY c.created_at, c.id
`

type ListCommentsRow struct {
	ID         int64
	IssueID    int64
	AuthorID   int64
	AuthorName string
	AgentRole  string
	Body       string
	FilePath   string
	Line       int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListComments(ctx context.Context, issueID int64) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsRow{}
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AgentRole,
			&i.Body,
			&i.FilePath,
			&i.Line,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContributions = `-- name: ListContributions :many
SELECT id, repo_id, issue_id, session_id, agent_role, ref_name,
       head_sha, base_sha, title, description, status, mergeable,
       merge_mode, changed_paths, files, additions, deletions,
       merged_commit_sha, merged_at, created_at, updated_at
FROM contributions
WHERE issue_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListContributions(ctx context.Context, issueID int64) ([]Contribution, error) {
	rows, err := q.db.Query(ctx, listContributions, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contribution{}
	for rows.Next() {
		var i Contribution
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.IssueID,
			&i.SessionID,
			&i.AgentRole,
			&i.RefName,
			&i.HeadSha,
			&i.BaseSha,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Mergeable,
			&i.MergeMode,
			&i.ChangedPaths,
			&i.Files,
			&i.Additions,
			&i.Deletions,
			&i.MergedCommitSha,
			&i.MergedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.issue_id, e.kind, e.payload,
       COALESCE(e.actor_id, 0)::BIGINT AS actor_id,
       COALESCE(u.username, '')        AS actor_name,
       e.agent_role, e.created_at
FROM issue_events e
LEFT JOIN users u ON u.id = e.actor_id
WHERE e.issue_id = $1
ORDER BY e.created_at, e.id
`

type ListEventsRow struct {
	ID        int64
	IssueID   int64
	Kind      string
	Payload   []byte
	ActorID   int64
	ActorName string
	AgentRole string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListEvents(ctx context.Context, issueID int64) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Kind,
			&i.Payload,
			&i.ActorID,
			&i.ActorName,
			&i.AgentRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueChildren = `-- name: ListIssueChildren :many
SELECT i.id, i.repo_id, i.number,
       COALESCE(i.author_id, 0)::BIGINT AS author_id,
       COALESCE(u.username, '')         AS author_name,
       i.agent_role, i.title, i.body, i.state,
       i.branch_name, i.base_branch,
       i.head_sha, i.merge_commit_sha, i.merged_at,
       COALESCE(i.parent_id, 0)::BIGINT AS parent_id, i.parent_number,
       i.created_at, i.updated_at
FROM issues i
LEFT JOIN users u ON u.id = i.author_id
WHERE i.parent_id = $1
ORDER BY i.number ASC
`

type ListIssueChildrenRow struct {
	ID             int64
	RepoID         int64
	Number         int64
	AuthorID       int64
	AuthorName     string
	AgentRole      string
	Title          string
	Body           string
	State          string
	BranchName     string
	BaseBranch     string
	HeadSha        string
	MergeCommitSha string
	MergedAt       pgtype.Timestamptz
	ParentID       int64
	ParentNumber   int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListIssueChildren(ctx context.Context, parentID pgtype.Int8) ([]ListIssueChildrenRow, error) {
	rows, err := q.db.Query(ctx, listIssueChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueChildrenRow{}
	for rows.Next() {
		var i ListIssueChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Number,
			&i.AuthorID,
			&i.AuthorName,
			&i.AgentRole,
			&i.Title,
			&i.Body,
			&i.State,
			&i.BranchName,
			&i.BaseBranch,
			&i.HeadSha,
			&i.MergeCommitSha,
			&i.MergedAt,
			&i.ParentID,
			&i.ParentNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssues = `-- name: ListIssues :many
SELECT i.id, i.repo_id, i.number,
       COALESCE(i.author_id, 0)::BIGINT AS author_id,
       COALESCE(u.username, '')         AS author_name,
       i.agent_role, i.title, i.body, i.state,
       i.branch_name, i.base_branch,
       i.head_sha, i.merge_commit_sha, i.merged_at,
       COALESCE(i.parent_id, 0)::BIGINT AS parent_id, i.parent_number,
       i.created_at, i.updated_at
FROM issues i
LEFT JOIN users u ON u.id = i.author_id
WHERE i.repo_id = $1
  AND ($2::TEXT IS NULL OR i.state = $2)
ORDER BY i.number DESC
LIMIT $4 OFFSET $3
`

type ListIssuesParams struct {
	RepoID int64
	State  pgtype.Text
	Off    int32
	Lim    int32
}

type ListIssuesRow struct {
	ID             int64
	RepoID         int64
	Number         int64
	AuthorID       int64
	AuthorName     string
	AgentRole      string
	Title          string
	Body           string
	State          string
	BranchName     string
	BaseBranch     string
	HeadSha        string
	MergeCommitSha string
	MergedAt       pgtype.Timestamptz
	ParentID       int64
	ParentNumber   int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// State arg is optional (NULL = "any state").
func (q *Queries) ListIssues(ctx context.Context, arg ListIssuesParams) ([]ListIssuesRow, error) {
	rows, err := q.db.Query(ctx, listIssues,
		arg.RepoID,
		arg.State,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesRow{}
	for rows.Next() {
		var i ListIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Number,
			&i.AuthorID,
			&i.AuthorName,
			&i.AgentRole,
			&i.Title,
			&i.Body,
			&i.State,
			&i.BranchName,
			&i.BaseBranch,
			&i.HeadSha,
			&i.MergeCommitSha,
			&i.MergedAt,
			&i.ParentID,
			&i.ParentNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIssueNumbers = `-- name: ListOpenIssueNumbers :many
SELECT number FROM issues
WHERE repo_id = $1 AND state = 'open'
ORDER BY number
`

func (q *Queries) ListOpenIssueNumbers(ctx context.Context, repoID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOpenIssueNumbers, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var number int64
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttachmentAttached = `-- name: MarkAttachmentAttached :exec
UPDATE issue_attachments
SET status = 'attached', comment_id = $1
WHERE id = $2 AND status = 'uploaded'
`

type MarkAttachmentAttachedParams struct {
	CommentID pgtype.Int8
	ID        int64
}

func (q *Queries) MarkAttachmentAttached(ctx context.Context, arg MarkAttachmentAttachedParams) error {
	_, err := q.db.Exec(ctx, markAttachmentAttached, arg.CommentID, arg.ID)
	return err
}

const markContributionMerged = `-- name: MarkContributionMerged :one
UPDATE contributions
SET status = 'merged',
    merged_commit_sha = $1,
    merged_at = NOW(),
    mergeable = TRUE,
    updated_at = NOW()
WHERE id = $2
RETURNING id
`

type MarkContributionMergedParams struct {
	MergedCommitSha string
	ID              int64
}

func (q *Queries) MarkContributionMerged(ctx context.Context, arg MarkContributionMergedParams) (int64, error) {
	row := q.db.QueryRow(ctx, markContributionMerged, arg.MergedCommitSha, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const nextIssueNumber = `-- name: NextIssueNumber :one

INSERT INTO issue_counters (repo_id, next)
VALUES ($1, 2)
ON CONFLICT (repo_id) DO UPDATE SET next = issue_counters.next + 1
RETURNING (next - 1)::BIGINT AS number
`

// ---- issue_counters ----
// Atomic per-repo issue counter. RETURNS the value just claimed; the row
// initialiser starts at 2 because the first claim must return 1.
// Explicit BIGINT cast on the SELECT side so sqlc emits int64 rather
// than narrowing to int32 on the `next - 1` arithmetic.
func (q *Queries) NextIssueNumber(ctx context.Context, repoID int64) (int64, error) {
	row := q.db.QueryRow(ctx, nextIssueNumber, repoID)
	var number int64
	err := row.Scan(&number)
	return number, err
}

const setContributionMergeable = `-- name: SetContributionMergeable :exec
UPDATE contributions
SET mergeable = $1,
    merge_mode = $2,
    updated_at = NOW()
WHERE id = $3
`

type SetContributionMergeableParams struct {
	Mergeable bool
	MergeMode string
	ID        int64
}

func (q *Queries) SetContributionMergeable(ctx context.Context, arg SetContributionMergeableParams) error {
	_, err := q.db.Exec(ctx, setContributionMergeable, arg.Mergeable, arg.MergeMode, arg.ID)
	return err
}

const setContributionMeta = `-- name: SetContributionMeta :one
UPDATE contributions
SET title = $1,
    description = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING id
`

type SetContributionMetaParams struct {
	Title       string
	Description string
	ID          int64
}

func (q *Queries) SetContributionMeta(ctx context.Context, arg SetContributionMetaParams) (int64, error) {
	row := q.db.QueryRow(ctx, setContributionMeta, arg.Title, arg.Description, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setContributionStatus = `-- name: SetContributionStatus :one
UPDATE contributions
SET status = $1, updated_at = NOW()
WHERE id = $2
RETURNING id
`

type SetContributionStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) SetContributionStatus(ctx context.Context, arg SetContributionStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, setContributionStatus, arg.Status, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const softDeleteAttachment = `-- name: SoftDeleteAttachment :exec
UPDATE issue_attachments
SET status = 'deleted', deleted_at = NOW()
WHERE id = $1 AND status <> 'deleted'
`

func (q *Queries) SoftDeleteAttachment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteAttachment, id)
	return err
}

const updateIssueHeadSHA = `-- name: UpdateIssueHeadSHA :exec
UPDATE issues SET head_sha = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateIssueHeadSHAParams struct {
	HeadSha string
	ID      int64
}

func (q *Queries) UpdateIssueHeadSHA(ctx context.Context, arg UpdateIssueHeadSHAParams) error {
	_, err := q.db.Exec(ctx, updateIssueHeadSHA, arg.HeadSha, arg.ID)
	return err
}

const updateIssueState = `-- name: UpdateIssueState :one
UPDATE issues
SET state = $1,
    merge_commit_sha = CASE WHEN $1 = 'merged'
                            THEN $2
                            ELSE merge_commit_sha
                       END,
    merged_at = CASE WHEN $1 = 'merged' THEN NOW() ELSE merged_at END,
    updated_at = NOW()
WHERE id = $3
RETURNING repo_id, number
`

type UpdateIssueStateParams struct {
	State    string
	MergeSha string
	ID       int64
}

type UpdateIssueStateRow struct {
	RepoID int64
	Number int64
}

// Sets state and (when transitioning to merged) merge_commit_sha + merged_at.
func (q *Queries) UpdateIssueState(ctx context.Context, arg UpdateIssueStateParams) (UpdateIssueStateRow, error) {
	row := q.db.QueryRow(ctx, updateIssueState, arg.State, arg.MergeSha, arg.ID)
	var i UpdateIssueStateRow
	err := row.Scan(&i.RepoID, &i.Number)
	return i, err
}

const updateIssueTitleBody = `-- name: UpdateIssueTitleBody :one
UPDATE issues
SET title = $1,
    body = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING repo_id, number
`

type UpdateIssueTitleBodyParams struct {
	Title string
	Body  string
	ID    int64
}

type UpdateIssueTitleBodyRow struct {
	RepoID int64
	Number int64
}

func (q *Queries) UpdateIssueTitleBody(ctx context.Context, arg UpdateIssueTitleBodyParams) (UpdateIssueTitleBodyRow, error) {
	row := q.db.QueryRow(ctx, updateIssueTitleBody, arg.Title, arg.Body, arg.ID)
	var i UpdateIssueTitleBodyRow
	err := row.Scan(&i.RepoID, &i.Number)
	return i, err
}

const upsertContributionOnPush = `-- name: UpsertContributionOnPush :one

INSERT INTO contributions (
    repo_id, issue_id, session_id, agent_role, ref_name,
    head_sha, base_sha, changed_paths, files, additions, deletions, status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    'open'
)
ON CONFLICT (issue_id, ref_name) DO UPDATE SET
    session_id    = EXCLUDED.session_id,
    agent_role    = EXCLUDED.agent_role,
    head_sha      = EXCLUDED.head_sha,
    base_sha      = EXCLUDED.base_sha,
    changed_paths = EXCLUDED.changed_paths,
    files         = EXCLUDED.files,
    additions     = EXCLUDED.additions,
    deletions     = EXCLUDED.deletions,
    status        = CASE
                        WHEN contributions.head_sha IS DISTINCT FROM EXCLUDED.head_sha
                             AND contributions.status IN ('open','changes_requested')
                        THEN 'open'
                        ELSE contributions.status
                    END,
    updated_at    = NOW()
RETURNING id
`

type UpsertContributionOnPushParams struct {
	RepoID       int64
	IssueID      int64
	SessionID    int64
	AgentRole    string
	RefName      string
	HeadSha      string
	BaseSha      string
	ChangedPaths []string
	Files        int32
	Additions    int32
	Deletions    int32
}

// ---- contributions ----
// Insert a contribution for a freshly-pushed namespace ref, or update the
// existing one (keyed by issue_id+ref_name) with the new head/diff. When the
// head SHA actually changed, the status resets to 'open' (a new push dismisses
// prior approvals — GitHub-style) and mergeable is recomputed by the caller.
func (q *Queries) UpsertContributionOnPush(ctx context.Context, arg UpsertContributionOnPushParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertContributionOnPush,
		arg.RepoID,
		arg.IssueID,
		arg.SessionID,
		arg.AgentRole,
		arg.RefName,
		arg.HeadSha,
		arg.BaseSha,
		arg.ChangedPaths,
		arg.Files,
		arg.Additions,
		arg.Deletions,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
