// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package issuedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIssues = `-- name: CountIssues :one
SELECT COUNT(*) FROM issues i
WHERE i.repo_id = $1
  AND ($2::TEXT IS NULL OR i.state = $2)
`

type CountIssuesParams struct {
	RepoID int64
	State  pgtype.Text
}

func (q *Queries) CountIssues(ctx context.Context, arg CountIssuesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIssues, arg.RepoID, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one

INSERT INTO issue_comments (
    issue_id, author_id, agent_role, body, file_path, line
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at
`

type CreateCommentParams struct {
	IssueID   int64
	AuthorID  pgtype.Int8
	AgentRole string
	Body      string
	FilePath  string
	Line      int32
}

type CreateCommentRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// ---- issue_comments ----
// author_id and agent_role are mutually exclusive (CHECK constraint at
// the table level). Callers pass exactly one — sqlc.narg('author_id')
// for the human path, sqlc.arg('agent_role') for the agent path; the
// other gets the zero value.
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.IssueID,
		arg.AuthorID,
		arg.AgentRole,
		arg.Body,
		arg.FilePath,
		arg.Line,
	)
	var i CreateCommentRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createEvent = `-- name: CreateEvent :one

INSERT INTO issue_events (
    issue_id, kind, payload, actor_id, agent_role
)
VALUES (
    $1,
    $2,
    $3::jsonb,
    $4,
    $5
)
RETURNING id, created_at
`

type CreateEventParams struct {
	IssueID   int64
	Kind      string
	Payload   []byte
	ActorID   pgtype.Int8
	AgentRole string
}

type CreateEventRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

// ---- issue_events ----
// actor_id is nullable for system-generated events (M5+); agent_role
// is the role-key string for agent-generated events. Both can be set
// on a row to attribute a system-side action to a specific agent role.
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.IssueID,
		arg.Kind,
		arg.Payload,
		arg.ActorID,
		arg.AgentRole,
	)
	var i CreateEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createIssue = `-- name: CreateIssue :one

INSERT INTO issues (
    repo_id, number, author_id, title, body, branch_name,
    base_branch, parent_id, parent_number
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, state, created_at, updated_at
`

type CreateIssueParams struct {
	RepoID       int64
	Number       int64
	AuthorID     int64
	Title        string
	Body         string
	BranchName   string
	BaseBranch   string
	ParentID     pgtype.Int8
	ParentNumber int64
}

type CreateIssueRow struct {
	ID        int64
	State     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// ---- issues ----
func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (CreateIssueRow, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.RepoID,
		arg.Number,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.BranchName,
		arg.BaseBranch,
		arg.ParentID,
		arg.ParentNumber,
	)
	var i CreateIssueRow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.issue_id,
       COALESCE(c.author_id, 0)::BIGINT AS author_id,
       COALESCE(u.username, '')         AS author_name,
       c.agent_role, c.body, c.file_path, c.line,
       c.created_at, c.updated_at
FROM issue_comments c
LEFT JOIN users u ON u.id = c.author_id
WHERE c.id = $1
`

type GetCommentByIDRow struct {
	ID         int64
	IssueID    int64
	AuthorID   int64
	AuthorName string
	AgentRole  string
	Body       string
	FilePath   string
	Line       int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) GetCommentByID(ctx context.Context, id int64) (GetCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.AuthorName,
		&i.AgentRole,
		&i.Body,
		&i.FilePath,
		&i.Line,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT e.id, e.issue_id, e.kind, e.payload,
       COALESCE(e.actor_id, 0)::BIGINT AS actor_id,
       COALESCE(u.username, '')        AS actor_name,
       e.agent_role, e.created_at
FROM issue_events e
LEFT JOIN users u ON u.id = e.actor_id
WHERE e.id = $1
`

type GetEventByIDRow struct {
	ID        int64
	IssueID   int64
	Kind      string
	Payload   []byte
	ActorID   int64
	ActorName string
	AgentRole string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetEventByID(ctx context.Context, id int64) (GetEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Kind,
		&i.Payload,
		&i.ActorID,
		&i.ActorName,
		&i.AgentRole,
		&i.CreatedAt,
	)
	return i, err
}

const getIssueByNumber = `-- name: GetIssueByNumber :one
SELECT i.id, i.repo_id, i.number, i.author_id, u.username,
       i.title, i.body, i.state, i.branch_name, i.base_branch,
       i.head_sha, i.merge_commit_sha, i.merged_at,
       COALESCE(i.parent_id, 0)::BIGINT AS parent_id, i.parent_number,
       i.created_at, i.updated_at
FROM issues i
JOIN users u ON u.id = i.author_id
WHERE i.repo_id = $1 AND i.number = $2
`

type GetIssueByNumberParams struct {
	RepoID int64
	Number int64
}

type GetIssueByNumberRow struct {
	ID             int64
	RepoID         int64
	Number         int64
	AuthorID       int64
	Username       string
	Title          string
	Body           string
	State          string
	BranchName     string
	BaseBranch     string
	HeadSha        string
	MergeCommitSha string
	MergedAt       pgtype.Timestamptz
	ParentID       int64
	ParentNumber   int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetIssueByNumber(ctx context.Context, arg GetIssueByNumberParams) (GetIssueByNumberRow, error) {
	row := q.db.QueryRow(ctx, getIssueByNumber, arg.RepoID, arg.Number)
	var i GetIssueByNumberRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Number,
		&i.AuthorID,
		&i.Username,
		&i.Title,
		&i.Body,
		&i.State,
		&i.BranchName,
		&i.BaseBranch,
		&i.HeadSha,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ParentID,
		&i.ParentNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT c.id, c.issue_id,
       COALESCE(c.author_id, 0)::BIGINT AS author_id,
       COALESCE(u.username, '')         AS author_name,
       c.agent_role, c.body, c.file_path, c.line,
       c.created_at, c.updated_at
FROM issue_comments c
LEFT JOIN users u ON u.id = c.author_id
WHERE c.issue_id = $1
ORDER BY c.created_at, c.id
`

type ListCommentsRow struct {
	ID         int64
	IssueID    int64
	AuthorID   int64
	AuthorName string
	AgentRole  string
	Body       string
	FilePath   string
	Line       int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListComments(ctx context.Context, issueID int64) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsRow{}
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AgentRole,
			&i.Body,
			&i.FilePath,
			&i.Line,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.issue_id, e.kind, e.payload,
       COALESCE(e.actor_id, 0)::BIGINT AS actor_id,
       COALESCE(u.username, '')        AS actor_name,
       e.agent_role, e.created_at
FROM issue_events e
LEFT JOIN users u ON u.id = e.actor_id
WHERE e.issue_id = $1
ORDER BY e.created_at, e.id
`

type ListEventsRow struct {
	ID        int64
	IssueID   int64
	Kind      string
	Payload   []byte
	ActorID   int64
	ActorName string
	AgentRole string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListEvents(ctx context.Context, issueID int64) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Kind,
			&i.Payload,
			&i.ActorID,
			&i.ActorName,
			&i.AgentRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueChildren = `-- name: ListIssueChildren :many
SELECT i.id, i.repo_id, i.number, i.author_id, u.username,
       i.title, i.body, i.state, i.branch_name, i.base_branch,
       i.head_sha, i.merge_commit_sha, i.merged_at,
       COALESCE(i.parent_id, 0)::BIGINT AS parent_id, i.parent_number,
       i.created_at, i.updated_at
FROM issues i
JOIN users u ON u.id = i.author_id
WHERE i.parent_id = $1
ORDER BY i.number ASC
`

type ListIssueChildrenRow struct {
	ID             int64
	RepoID         int64
	Number         int64
	AuthorID       int64
	Username       string
	Title          string
	Body           string
	State          string
	BranchName     string
	BaseBranch     string
	HeadSha        string
	MergeCommitSha string
	MergedAt       pgtype.Timestamptz
	ParentID       int64
	ParentNumber   int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListIssueChildren(ctx context.Context, parentID pgtype.Int8) ([]ListIssueChildrenRow, error) {
	rows, err := q.db.Query(ctx, listIssueChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueChildrenRow{}
	for rows.Next() {
		var i ListIssueChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Number,
			&i.AuthorID,
			&i.Username,
			&i.Title,
			&i.Body,
			&i.State,
			&i.BranchName,
			&i.BaseBranch,
			&i.HeadSha,
			&i.MergeCommitSha,
			&i.MergedAt,
			&i.ParentID,
			&i.ParentNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssues = `-- name: ListIssues :many
SELECT i.id, i.repo_id, i.number, i.author_id, u.username,
       i.title, i.body, i.state, i.branch_name, i.base_branch,
       i.head_sha, i.merge_commit_sha, i.merged_at,
       COALESCE(i.parent_id, 0)::BIGINT AS parent_id, i.parent_number,
       i.created_at, i.updated_at
FROM issues i
JOIN users u ON u.id = i.author_id
WHERE i.repo_id = $1
  AND ($2::TEXT IS NULL OR i.state = $2)
ORDER BY i.number DESC
LIMIT $4 OFFSET $3
`

type ListIssuesParams struct {
	RepoID int64
	State  pgtype.Text
	Off    int32
	Lim    int32
}

type ListIssuesRow struct {
	ID             int64
	RepoID         int64
	Number         int64
	AuthorID       int64
	Username       string
	Title          string
	Body           string
	State          string
	BranchName     string
	BaseBranch     string
	HeadSha        string
	MergeCommitSha string
	MergedAt       pgtype.Timestamptz
	ParentID       int64
	ParentNumber   int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// State arg is optional (NULL = "any state").
func (q *Queries) ListIssues(ctx context.Context, arg ListIssuesParams) ([]ListIssuesRow, error) {
	rows, err := q.db.Query(ctx, listIssues,
		arg.RepoID,
		arg.State,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesRow{}
	for rows.Next() {
		var i ListIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Number,
			&i.AuthorID,
			&i.Username,
			&i.Title,
			&i.Body,
			&i.State,
			&i.BranchName,
			&i.BaseBranch,
			&i.HeadSha,
			&i.MergeCommitSha,
			&i.MergedAt,
			&i.ParentID,
			&i.ParentNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIssueNumbers = `-- name: ListOpenIssueNumbers :many
SELECT number FROM issues
WHERE repo_id = $1 AND state = 'open'
ORDER BY number
`

func (q *Queries) ListOpenIssueNumbers(ctx context.Context, repoID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOpenIssueNumbers, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var number int64
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextIssueNumber = `-- name: NextIssueNumber :one

INSERT INTO issue_counters (repo_id, next)
VALUES ($1, 2)
ON CONFLICT (repo_id) DO UPDATE SET next = issue_counters.next + 1
RETURNING (next - 1)::BIGINT AS number
`

// ---- issue_counters ----
// Atomic per-repo issue counter. RETURNS the value just claimed; the row
// initialiser starts at 2 because the first claim must return 1.
// Explicit BIGINT cast on the SELECT side so sqlc emits int64 rather
// than narrowing to int32 on the `next - 1` arithmetic.
func (q *Queries) NextIssueNumber(ctx context.Context, repoID int64) (int64, error) {
	row := q.db.QueryRow(ctx, nextIssueNumber, repoID)
	var number int64
	err := row.Scan(&number)
	return number, err
}

const updateIssueHeadSHA = `-- name: UpdateIssueHeadSHA :exec
UPDATE issues SET head_sha = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateIssueHeadSHAParams struct {
	HeadSha string
	ID      int64
}

func (q *Queries) UpdateIssueHeadSHA(ctx context.Context, arg UpdateIssueHeadSHAParams) error {
	_, err := q.db.Exec(ctx, updateIssueHeadSHA, arg.HeadSha, arg.ID)
	return err
}

const updateIssueState = `-- name: UpdateIssueState :one
UPDATE issues
SET state = $1,
    merge_commit_sha = CASE WHEN $1 = 'merged'
                            THEN $2
                            ELSE merge_commit_sha
                       END,
    merged_at = CASE WHEN $1 = 'merged' THEN NOW() ELSE merged_at END,
    updated_at = NOW()
WHERE id = $3
RETURNING repo_id, number
`

type UpdateIssueStateParams struct {
	State    string
	MergeSha string
	ID       int64
}

type UpdateIssueStateRow struct {
	RepoID int64
	Number int64
}

// Sets state and (when transitioning to merged) merge_commit_sha + merged_at.
func (q *Queries) UpdateIssueState(ctx context.Context, arg UpdateIssueStateParams) (UpdateIssueStateRow, error) {
	row := q.db.QueryRow(ctx, updateIssueState, arg.State, arg.MergeSha, arg.ID)
	var i UpdateIssueStateRow
	err := row.Scan(&i.RepoID, &i.Number)
	return i, err
}

const updateIssueTitleBody = `-- name: UpdateIssueTitleBody :one
UPDATE issues
SET title = $1,
    body = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING repo_id, number
`

type UpdateIssueTitleBodyParams struct {
	Title string
	Body  string
	ID    int64
}

type UpdateIssueTitleBodyRow struct {
	RepoID int64
	Number int64
}

func (q *Queries) UpdateIssueTitleBody(ctx context.Context, arg UpdateIssueTitleBodyParams) (UpdateIssueTitleBodyRow, error) {
	row := q.db.QueryRow(ctx, updateIssueTitleBody, arg.Title, arg.Body, arg.ID)
	var i UpdateIssueTitleBodyRow
	err := row.Scan(&i.RepoID, &i.Number)
	return i, err
}
