// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package automationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeAutomationRun = `-- name: CompleteAutomationRun :execrows
UPDATE automation_runs
SET status       = 'success',
    issue_id     = $1,
    finished_at  = NOW()
WHERE id = $2
`

type CompleteAutomationRunParams struct {
	IssueID pgtype.Int8
	ID      int64
}

func (q *Queries) CompleteAutomationRun(ctx context.Context, arg CompleteAutomationRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAutomationRun, arg.IssueID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAutomationRun = `-- name: CreateAutomationRun :one
INSERT INTO automation_runs (repo_id, task_name, status, started_at)
VALUES ($1, $2, 'running', NOW())
RETURNING id, repo_id, task_name, issue_id, status, error_message, started_at, finished_at, created_at
`

type CreateAutomationRunParams struct {
	RepoID   int64
	TaskName string
}

func (q *Queries) CreateAutomationRun(ctx context.Context, arg CreateAutomationRunParams) (AutomationRun, error) {
	row := q.db.QueryRow(ctx, createAutomationRun, arg.RepoID, arg.TaskName)
	var i AutomationRun
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TaskName,
		&i.IssueID,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const failAutomationRun = `-- name: FailAutomationRun :execrows
UPDATE automation_runs
SET status        = 'failed',
    error_message = $1,
    finished_at   = NOW()
WHERE id = $2
`

type FailAutomationRunParams struct {
	ErrorMessage pgtype.Text
	ID           int64
}

func (q *Queries) FailAutomationRun(ctx context.Context, arg FailAutomationRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, failAutomationRun, arg.ErrorMessage, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lastSuccessfulAutomationRun = `-- name: LastSuccessfulAutomationRun :one
SELECT id, repo_id, task_name, issue_id, status, error_message, started_at, finished_at, created_at
FROM automation_runs
WHERE repo_id   = $1
  AND task_name = $2
  AND status    = 'success'
ORDER BY created_at DESC
LIMIT 1
`

type LastSuccessfulAutomationRunParams struct {
	RepoID   int64
	TaskName string
}

func (q *Queries) LastSuccessfulAutomationRun(ctx context.Context, arg LastSuccessfulAutomationRunParams) (AutomationRun, error) {
	row := q.db.QueryRow(ctx, lastSuccessfulAutomationRun, arg.RepoID, arg.TaskName)
	var i AutomationRun
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TaskName,
		&i.IssueID,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAutomationRuns = `-- name: ListAutomationRuns :many
SELECT id, repo_id, task_name, issue_id, status, error_message, started_at, finished_at, created_at
FROM automation_runs
WHERE repo_id = $1
  AND ($2::TEXT IS NULL OR task_name = $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListAutomationRunsParams struct {
	RepoID   int64
	TaskName pgtype.Text
	Limit    int32
}

func (q *Queries) ListAutomationRuns(ctx context.Context, arg ListAutomationRunsParams) ([]AutomationRun, error) {
	rows, err := q.db.Query(ctx, listAutomationRuns, arg.RepoID, arg.TaskName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationRun{}
	for rows.Next() {
		var i AutomationRun
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.TaskName,
			&i.IssueID,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentAutomationRunExists = `-- name: RecentAutomationRunExists :one
SELECT EXISTS (
    SELECT 1
    FROM automation_runs
    WHERE repo_id    = $1
      AND task_name  = $2
      AND created_at > $3
) AS exists
`

type RecentAutomationRunExistsParams struct {
	RepoID   int64
	TaskName string
	Since    pgtype.Timestamptz
}

func (q *Queries) RecentAutomationRunExists(ctx context.Context, arg RecentAutomationRunExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, recentAutomationRunExists, arg.RepoID, arg.TaskName, arg.Since)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
