// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package questionnairedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Actor struct {
	ID             int64
	Kind           string
	UserID         pgtype.Int8
	AgentRoleKey   pgtype.Text
	AgentSessionID pgtype.Int8
	WorkflowRunID  pgtype.Int8
	DisplayName    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type BranchProtection struct {
	ID               int64
	RepoID           int64
	Pattern          string
	ForbidForcePush  bool
	ForbidDelete     bool
	ForbidDirectPush bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Contribution struct {
	ID              int64
	RepoID          int64
	IssueID         int64
	SessionID       int64
	AgentRole       string
	RefName         string
	HeadSha         string
	BaseSha         string
	Title           string
	Description     string
	Status          string
	Mergeable       bool
	MergeMode       string
	ChangedPaths    []string
	Files           int32
	Additions       int32
	Deletions       int32
	MergedCommitSha string
	MergedAt        pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ActorID         int64
}

type Issue struct {
	ID             int64
	RepoID         int64
	Number         int64
	Title          string
	Body           string
	State          string
	BranchName     string
	BaseBranch     string
	HeadSha        string
	MergeCommitSha string
	MergedAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ParentID       pgtype.Int8
	ParentNumber   int64
	ActorID        int64
}

type IssueAttachment struct {
	ID               int64
	RepoID           int64
	IssueID          int64
	CommentID        pgtype.Int8
	StorageKey       string
	OriginalName     string
	SizeBytes        int64
	MimeType         string
	DetectedMimeType string
	Sha256           string
	Kind             string
	Status           string
	CreatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	DisplayName      string
	Inline           bool
	ActorID          int64
}

type IssueComment struct {
	ID        int64
	IssueID   int64
	Body      string
	FilePath  string
	Line      int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ActorID   int64
}

type IssueCounter struct {
	RepoID int64
	Next   int64
}

type IssueDependency struct {
	ID          int64
	RepoID      int64
	IssueID     int64
	DependsOnID int64
	CreatedBy   pgtype.Int8
	CreatedAt   pgtype.Timestamptz
}

type IssueEvent struct {
	ID        int64
	IssueID   int64
	Kind      string
	Payload   []byte
	ActorID   int64
	CreatedAt pgtype.Timestamptz
}

type Organization struct {
	ID          int64
	Name        string
	DisplayName string
	Description string
	AvatarUrl   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	ActorID     int64
}

type OrganizationMember struct {
	OrgID   int64
	UserID  int64
	Role    string
	AddedAt pgtype.Timestamptz
	ActorID int64
}

type Questionnaire struct {
	ID             int64
	IssueID        int64
	Title          string
	Description    string
	Status         string
	CreatedByAgent string
	CreatedAt      pgtype.Timestamptz
	ClosedAt       pgtype.Timestamptz
	ClosedReason   string
}

type QuestionnaireAnswer struct {
	ID              int64
	QuestionnaireID int64
	Answers         []byte
	SubmittedAt     pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ActorID         int64
}

type QuestionnaireQuestion struct {
	ID              int64
	QuestionnaireID int64
	Position        int32
	QuestionText    string
	Qtype           string
	Options         []byte
	Required        bool
}

type Repo struct {
	ID            int64
	OwnerUserID   pgtype.Int8
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerOrgID    pgtype.Int8
}

type RepoMember struct {
	RepoID  int64
	UserID  int64
	Role    string
	AddedAt pgtype.Timestamptz
	ActorID int64
}

type RepoVariable struct {
	ID        int64
	RepoID    int64
	Name      string
	Value     string
	Kind      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Todo struct {
	ID        int64
	IssueID   int64
	Content   string
	Status    string
	Position  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
