// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package questionnairedb

import (
	"context"
)

const autoCloseQuestionnaire = `-- name: AutoCloseQuestionnaire :one
UPDATE questionnaires
SET status = 'closed', closed_at = now(),
    closed_reason = COALESCE(NULLIF($1, ''), 'auto:first_submission')
WHERE id = $2 AND status = 'open'
RETURNING id, issue_id, title, description, status, created_by_agent, created_at, closed_at, closed_reason
`

type AutoCloseQuestionnaireParams struct {
	ClosedReason interface{}
	ID           int64
}

func (q *Queries) AutoCloseQuestionnaire(ctx context.Context, arg AutoCloseQuestionnaireParams) (Questionnaire, error) {
	row := q.db.QueryRow(ctx, autoCloseQuestionnaire, arg.ClosedReason, arg.ID)
	var i Questionnaire
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.ClosedReason,
	)
	return i, err
}

const closeQuestionnaire = `-- name: CloseQuestionnaire :one
UPDATE questionnaires
SET status = 'closed', closed_at = now(), closed_reason = $1
WHERE id = $2
RETURNING id, issue_id, title, description, status, created_by_agent, created_at, closed_at, closed_reason
`

type CloseQuestionnaireParams struct {
	ClosedReason string
	ID           int64
}

func (q *Queries) CloseQuestionnaire(ctx context.Context, arg CloseQuestionnaireParams) (Questionnaire, error) {
	row := q.db.QueryRow(ctx, closeQuestionnaire, arg.ClosedReason, arg.ID)
	var i Questionnaire
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.ClosedReason,
	)
	return i, err
}

const countAnswers = `-- name: CountAnswers :one
SELECT COUNT(*)::BIGINT AS cnt
FROM questionnaire_answers
WHERE questionnaire_id = $1
`

func (q *Queries) CountAnswers(ctx context.Context, questionnaireID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAnswers, questionnaireID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questionnaire_questions (questionnaire_id, position, question_text, qtype, options, required)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, questionnaire_id, position, question_text, qtype, options, required
`

type CreateQuestionParams struct {
	QuestionnaireID int64
	Position        int32
	QuestionText    string
	Qtype           string
	Options         []byte
	Required        bool
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (QuestionnaireQuestion, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.QuestionnaireID,
		arg.Position,
		arg.QuestionText,
		arg.Qtype,
		arg.Options,
		arg.Required,
	)
	var i QuestionnaireQuestion
	err := row.Scan(
		&i.ID,
		&i.QuestionnaireID,
		&i.Position,
		&i.QuestionText,
		&i.Qtype,
		&i.Options,
		&i.Required,
	)
	return i, err
}

const createQuestionnaire = `-- name: CreateQuestionnaire :one

INSERT INTO questionnaires (issue_id, title, description, status, created_by_agent)
VALUES ($1, $2, $3, 'open', $4)
RETURNING id, issue_id, title, description, status, created_by_agent, created_at, closed_at, closed_reason
`

type CreateQuestionnaireParams struct {
	IssueID        int64
	Title          string
	Description    string
	CreatedByAgent string
}

// Questionnaire queries: CRUD + answers + results.
// sqlc.arg / sqlc.narg used for named parameters.
func (q *Queries) CreateQuestionnaire(ctx context.Context, arg CreateQuestionnaireParams) (Questionnaire, error) {
	row := q.db.QueryRow(ctx, createQuestionnaire,
		arg.IssueID,
		arg.Title,
		arg.Description,
		arg.CreatedByAgent,
	)
	var i Questionnaire
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.ClosedReason,
	)
	return i, err
}

const getQuestionnaire = `-- name: GetQuestionnaire :one
SELECT id, issue_id, title, description, status, created_by_agent, created_at, closed_at, closed_reason
FROM questionnaires
WHERE id = $1
`

func (q *Queries) GetQuestionnaire(ctx context.Context, id int64) (Questionnaire, error) {
	row := q.db.QueryRow(ctx, getQuestionnaire, id)
	var i Questionnaire
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.ClosedReason,
	)
	return i, err
}

const getQuestionnairesByIssue = `-- name: GetQuestionnairesByIssue :many
SELECT id, issue_id, title, description, status, created_by_agent, created_at, closed_at, closed_reason
FROM questionnaires
WHERE issue_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetQuestionnairesByIssue(ctx context.Context, issueID int64) ([]Questionnaire, error) {
	rows, err := q.db.Query(ctx, getQuestionnairesByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Questionnaire{}
	for rows.Next() {
		var i Questionnaire
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedByAgent,
			&i.CreatedAt,
			&i.ClosedAt,
			&i.ClosedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestions = `-- name: GetQuestions :many
SELECT id, questionnaire_id, position, question_text, qtype, options, required
FROM questionnaire_questions
WHERE questionnaire_id = $1
ORDER BY position ASC
`

func (q *Queries) GetQuestions(ctx context.Context, questionnaireID int64) ([]QuestionnaireQuestion, error) {
	rows, err := q.db.Query(ctx, getQuestions, questionnaireID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionnaireQuestion{}
	for rows.Next() {
		var i QuestionnaireQuestion
		if err := rows.Scan(
			&i.ID,
			&i.QuestionnaireID,
			&i.Position,
			&i.QuestionText,
			&i.Qtype,
			&i.Options,
			&i.Required,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatusForUpdate = `-- name: GetStatusForUpdate :one
SELECT status
FROM questionnaires
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetStatusForUpdate(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getStatusForUpdate, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getUserAnswer = `-- name: GetUserAnswer :one
SELECT id, questionnaire_id, user_id, answers, submitted_at, updated_at
FROM questionnaire_answers
WHERE questionnaire_id = $1 AND user_id = $2
`

type GetUserAnswerParams struct {
	QuestionnaireID int64
	UserID          int64
}

func (q *Queries) GetUserAnswer(ctx context.Context, arg GetUserAnswerParams) (QuestionnaireAnswer, error) {
	row := q.db.QueryRow(ctx, getUserAnswer, arg.QuestionnaireID, arg.UserID)
	var i QuestionnaireAnswer
	err := row.Scan(
		&i.ID,
		&i.QuestionnaireID,
		&i.UserID,
		&i.Answers,
		&i.SubmittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAnswer = `-- name: InsertAnswer :one
INSERT INTO questionnaire_answers (questionnaire_id, user_id, answers)
VALUES ($1, $2, $3)
RETURNING id, questionnaire_id, user_id, answers, submitted_at, updated_at
`

type InsertAnswerParams struct {
	QuestionnaireID int64
	UserID          int64
	Answers         []byte
}

func (q *Queries) InsertAnswer(ctx context.Context, arg InsertAnswerParams) (QuestionnaireAnswer, error) {
	row := q.db.QueryRow(ctx, insertAnswer, arg.QuestionnaireID, arg.UserID, arg.Answers)
	var i QuestionnaireAnswer
	err := row.Scan(
		&i.ID,
		&i.QuestionnaireID,
		&i.UserID,
		&i.Answers,
		&i.SubmittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnswers = `-- name: ListAnswers :many
SELECT id, questionnaire_id, user_id, answers, submitted_at, updated_at
FROM questionnaire_answers
WHERE questionnaire_id = $1
ORDER BY submitted_at ASC
`

func (q *Queries) ListAnswers(ctx context.Context, questionnaireID int64) ([]QuestionnaireAnswer, error) {
	rows, err := q.db.Query(ctx, listAnswers, questionnaireID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionnaireAnswer{}
	for rows.Next() {
		var i QuestionnaireAnswer
		if err := rows.Scan(
			&i.ID,
			&i.QuestionnaireID,
			&i.UserID,
			&i.Answers,
			&i.SubmittedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
