// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package workflowdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentSession struct {
	ID                      int64
	RunnerID                pgtype.Int8
	RepoID                  pgtype.Int8
	IssueNumber             pgtype.Int4
	Status                  string
	Role                    string
	Model                   string
	AgentImage              string
	WorkingBranch           string
	BaseBranch              string
	HostAddendum            string
	Env                     []byte
	SessionTokenPrefix      string
	SessionTokenHash        string
	SessionTokenSealed      pgtype.Text
	SessionTokenRevokedAt   pgtype.Timestamptz
	ExitCode                pgtype.Int4
	ErrorMessage            string
	CreatedBy               int64
	CreatedAt               pgtype.Timestamptz
	ClaimedAt               pgtype.Timestamptz
	StartedAt               pgtype.Timestamptz
	EndedAt                 pgtype.Timestamptz
	RepoSha                 string
	RoleKey                 string
	CauseKind               string
	CauseID                 string
	RoleConfig              []byte
	ContainerID             string
	ContainerLastUsedAt     pgtype.Timestamptz
	ContainerCleanupPending bool
}

type AgentSessionInput struct {
	ID         int64
	SessionID  int64
	Seq        int32
	Payload    []byte
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type AgentSessionMessage struct {
	ID         int64
	SessionID  int64
	Seq        int32
	Kind       string
	Role       string
	Content    string
	EventName  string
	ToolCallID string
	ToolName   string
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
}

type BranchProtection struct {
	ID               int64
	RepoID           int64
	Pattern          string
	ForbidForcePush  bool
	ForbidDelete     bool
	ForbidDirectPush bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Organization struct {
	ID          int64
	Name        string
	DisplayName string
	Description string
	AvatarUrl   string
	CreatedBy   int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type OrganizationMember struct {
	OrgID   int64
	UserID  int64
	Role    string
	AddedBy int64
	AddedAt pgtype.Timestamptz
}

type Repo struct {
	ID            int64
	OwnerUserID   pgtype.Int8
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerOrgID    pgtype.Int8
}

type RepoMember struct {
	RepoID  int64
	UserID  int64
	Role    string
	AddedBy int64
	AddedAt pgtype.Timestamptz
}

type RepoVariable struct {
	ID        int64
	RepoID    int64
	Name      string
	Value     string
	Kind      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Runner struct {
	ID                  int64
	Name                string
	OwnerUserID         pgtype.Int8
	Visibility          string
	Status              string
	Capabilities        []byte
	LastHeartbeatAt     pgtype.Timestamptz
	EnrollTokenPrefix   string
	EnrollTokenHash     string
	EnrollTokenUsedAt   pgtype.Timestamptz
	AgentTokenPrefix    pgtype.Text
	AgentTokenHash      pgtype.Text
	AgentTokenRevokedAt pgtype.Timestamptz
	CreatedBy           int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type WorkflowJobLog struct {
	ID               int64
	WorkflowJobRunID int64
	Stream           string
	Line             string
	CreatedAt        pgtype.Timestamptz
}

type WorkflowJobRun struct {
	ID               int64
	WorkflowRunID    int64
	JobKey           string
	DisplayName      string
	Status           string
	SequenceIndex    int32
	WorkingDirectory string
	TimeoutMinutes   int32
	RunnerID         pgtype.Int8
	ContainerID      pgtype.Text
	EnvJson          []byte
	StepsJson        []byte
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	ExitCode         pgtype.Int4
	ErrorMessage     string
	CreatedAt        pgtype.Timestamptz
}

type WorkflowRun struct {
	ID                    int64
	RepoID                int64
	WorkflowName          string
	SourceFile            string
	Status                string
	EventName             string
	CauseID               pgtype.Int8
	Ref                   string
	CommitSha             string
	ContainerSnapshotJson []byte
	TriggerPayloadJson    []byte
	StartedAt             pgtype.Timestamptz
	FinishedAt            pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
}
