// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package workflowdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendWorkflowJobLog = `-- name: AppendWorkflowJobLog :exec

INSERT INTO workflow_job_logs (workflow_job_run_id, stream, line)
VALUES ($1, $2, $3)
`

type AppendWorkflowJobLogParams struct {
	WorkflowJobRunID int64
	Stream           string
	Line             string
}

// ---- workflow_job_logs ----
func (q *Queries) AppendWorkflowJobLog(ctx context.Context, arg AppendWorkflowJobLogParams) error {
	_, err := q.db.Exec(ctx, appendWorkflowJobLog, arg.WorkflowJobRunID, arg.Stream, arg.Line)
	return err
}

const claimNextWorkflowJob = `-- name: ClaimNextWorkflowJob :one
UPDATE workflow_job_runs
SET status = 'running', runner_id = $1, started_at = NOW()
WHERE id = (
    SELECT j.id FROM workflow_job_runs j
    WHERE j.status = 'pending'
      AND NOT EXISTS (
        SELECT 1 FROM workflow_job_runs j2
        WHERE j2.workflow_run_id = j.workflow_run_id
          AND j2.sequence_index < j.sequence_index
          AND j2.status NOT IN ('success', 'skipped', 'failed', 'cancelled')
      )
    ORDER BY j.sequence_index ASC, j.created_at ASC, j.id ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, workflow_run_id, job_key, display_name, status, sequence_index, working_directory, timeout_minutes, runner_id, container_id, env_json, steps_json, started_at, finished_at, exit_code, error_message, created_at, step_outputs_json, job_outputs_json, job_outputs_raw_json
`

// Only claim a job if no earlier-sequence job in the same run is still
// pending or running. This preserves the sequential execution guarantee:
// jobs within a workflow run execute one at a time in sequence order.
func (q *Queries) ClaimNextWorkflowJob(ctx context.Context, runnerID pgtype.Int8) (WorkflowJobRun, error) {
	row := q.db.QueryRow(ctx, claimNextWorkflowJob, runnerID)
	var i WorkflowJobRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.JobKey,
		&i.DisplayName,
		&i.Status,
		&i.SequenceIndex,
		&i.WorkingDirectory,
		&i.TimeoutMinutes,
		&i.RunnerID,
		&i.ContainerID,
		&i.EnvJson,
		&i.StepsJson,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StepOutputsJson,
		&i.JobOutputsJson,
		&i.JobOutputsRawJson,
	)
	return i, err
}

const createWorkflowJobRun = `-- name: CreateWorkflowJobRun :one

INSERT INTO workflow_job_runs (
    workflow_run_id, job_key, display_name, status, sequence_index,
    working_directory, timeout_minutes, env_json, steps_json, job_outputs_raw_json
) VALUES (
    $1, $2, $3,
    'pending', $4,
    $5, $6,
    $7, $8,
    $9
) RETURNING id, workflow_run_id, job_key, display_name, status, sequence_index, working_directory, timeout_minutes, runner_id, container_id, env_json, steps_json, started_at, finished_at, exit_code, error_message, created_at, step_outputs_json, job_outputs_json, job_outputs_raw_json
`

type CreateWorkflowJobRunParams struct {
	WorkflowRunID     int64
	JobKey            string
	DisplayName       string
	SequenceIndex     int32
	WorkingDirectory  string
	TimeoutMinutes    int32
	EnvJson           []byte
	StepsJson         []byte
	JobOutputsRawJson []byte
}

// ---- workflow_job_runs ----
func (q *Queries) CreateWorkflowJobRun(ctx context.Context, arg CreateWorkflowJobRunParams) (WorkflowJobRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowJobRun,
		arg.WorkflowRunID,
		arg.JobKey,
		arg.DisplayName,
		arg.SequenceIndex,
		arg.WorkingDirectory,
		arg.TimeoutMinutes,
		arg.EnvJson,
		arg.StepsJson,
		arg.JobOutputsRawJson,
	)
	var i WorkflowJobRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.JobKey,
		&i.DisplayName,
		&i.Status,
		&i.SequenceIndex,
		&i.WorkingDirectory,
		&i.TimeoutMinutes,
		&i.RunnerID,
		&i.ContainerID,
		&i.EnvJson,
		&i.StepsJson,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StepOutputsJson,
		&i.JobOutputsJson,
		&i.JobOutputsRawJson,
	)
	return i, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one


INSERT INTO workflow_runs (
    repo_id, workflow_name, source_file, status, event_name,
    cause_id, ref, commit_sha, container_snapshot_json, trigger_payload_json,
    workflow_token
) VALUES (
    $1, $2, $3,
    'pending', $4,
    $5, $6, $7,
    $8, $9,
    $10
) RETURNING id, repo_id, workflow_name, source_file, status, event_name, cause_id, ref, commit_sha, container_snapshot_json, trigger_payload_json, started_at, finished_at, created_at, workflow_token
`

type CreateWorkflowRunParams struct {
	RepoID                int64
	WorkflowName          string
	SourceFile            string
	EventName             string
	CauseID               pgtype.Int8
	Ref                   string
	CommitSha             string
	ContainerSnapshotJson []byte
	TriggerPayloadJson    []byte
	WorkflowToken         string
}

// Workflow module queries.
// Naming convention: sqlc.arg('name') for named parameters.
// ---- workflow_runs ----
func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.RepoID,
		arg.WorkflowName,
		arg.SourceFile,
		arg.EventName,
		arg.CauseID,
		arg.Ref,
		arg.CommitSha,
		arg.ContainerSnapshotJson,
		arg.TriggerPayloadJson,
		arg.WorkflowToken,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.WorkflowName,
		&i.SourceFile,
		&i.Status,
		&i.EventName,
		&i.CauseID,
		&i.Ref,
		&i.CommitSha,
		&i.ContainerSnapshotJson,
		&i.TriggerPayloadJson,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.WorkflowToken,
	)
	return i, err
}

const getWorkflowJobRun = `-- name: GetWorkflowJobRun :one
SELECT id, workflow_run_id, job_key, display_name, status, sequence_index, working_directory, timeout_minutes, runner_id, container_id, env_json, steps_json, started_at, finished_at, exit_code, error_message, created_at, step_outputs_json, job_outputs_json, job_outputs_raw_json FROM workflow_job_runs WHERE id = $1
`

func (q *Queries) GetWorkflowJobRun(ctx context.Context, id int64) (WorkflowJobRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowJobRun, id)
	var i WorkflowJobRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.JobKey,
		&i.DisplayName,
		&i.Status,
		&i.SequenceIndex,
		&i.WorkingDirectory,
		&i.TimeoutMinutes,
		&i.RunnerID,
		&i.ContainerID,
		&i.EnvJson,
		&i.StepsJson,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StepOutputsJson,
		&i.JobOutputsJson,
		&i.JobOutputsRawJson,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, repo_id, workflow_name, source_file, status, event_name, cause_id, ref, commit_sha, container_snapshot_json, trigger_payload_json, started_at, finished_at, created_at, workflow_token FROM workflow_runs WHERE id = $1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id int64) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.WorkflowName,
		&i.SourceFile,
		&i.Status,
		&i.EventName,
		&i.CauseID,
		&i.Ref,
		&i.CommitSha,
		&i.ContainerSnapshotJson,
		&i.TriggerPayloadJson,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.WorkflowToken,
	)
	return i, err
}

const getWorkflowRunByToken = `-- name: GetWorkflowRunByToken :one
SELECT repo_id, status FROM workflow_runs
WHERE workflow_token = $1 AND workflow_token <> ''
`

type GetWorkflowRunByTokenRow struct {
	RepoID int64
	Status string
}

func (q *Queries) GetWorkflowRunByToken(ctx context.Context, token string) (GetWorkflowRunByTokenRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowRunByToken, token)
	var i GetWorkflowRunByTokenRow
	err := row.Scan(&i.RepoID, &i.Status)
	return i, err
}

const listWorkflowJobLogs = `-- name: ListWorkflowJobLogs :many
SELECT id, workflow_job_run_id, stream, line, created_at, COUNT(*) OVER() AS total_count
FROM workflow_job_logs
WHERE workflow_job_run_id = $1
ORDER BY created_at ASC, id ASC
LIMIT $3 OFFSET $2
`

type ListWorkflowJobLogsParams struct {
	WorkflowJobRunID int64
	Offset           int32
	Limit            int32
}

type ListWorkflowJobLogsRow struct {
	ID               int64
	WorkflowJobRunID int64
	Stream           string
	Line             string
	CreatedAt        pgtype.Timestamptz
	TotalCount       int64
}

func (q *Queries) ListWorkflowJobLogs(ctx context.Context, arg ListWorkflowJobLogsParams) ([]ListWorkflowJobLogsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowJobLogs, arg.WorkflowJobRunID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowJobLogsRow{}
	for rows.Next() {
		var i ListWorkflowJobLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowJobRunID,
			&i.Stream,
			&i.Line,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowJobRunsByRun = `-- name: ListWorkflowJobRunsByRun :many
SELECT id, workflow_run_id, job_key, display_name, status, sequence_index, working_directory, timeout_minutes, runner_id, container_id, env_json, steps_json, started_at, finished_at, exit_code, error_message, created_at, step_outputs_json, job_outputs_json, job_outputs_raw_json FROM workflow_job_runs
WHERE workflow_run_id = $1
ORDER BY sequence_index ASC
`

func (q *Queries) ListWorkflowJobRunsByRun(ctx context.Context, workflowRunID int64) ([]WorkflowJobRun, error) {
	rows, err := q.db.Query(ctx, listWorkflowJobRunsByRun, workflowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowJobRun{}
	for rows.Next() {
		var i WorkflowJobRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowRunID,
			&i.JobKey,
			&i.DisplayName,
			&i.Status,
			&i.SequenceIndex,
			&i.WorkingDirectory,
			&i.TimeoutMinutes,
			&i.RunnerID,
			&i.ContainerID,
			&i.EnvJson,
			&i.StepsJson,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StepOutputsJson,
			&i.JobOutputsJson,
			&i.JobOutputsRawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRunsByRepo = `-- name: ListWorkflowRunsByRepo :many
SELECT id, repo_id, workflow_name, source_file, status, event_name, cause_id, ref, commit_sha, container_snapshot_json, trigger_payload_json, started_at, finished_at, created_at, workflow_token, COUNT(*) OVER() AS total_count
FROM workflow_runs
WHERE repo_id = $1
  AND ($2 = '' OR workflow_name = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListWorkflowRunsByRepoParams struct {
	RepoID       int64
	WorkflowName interface{}
	Offset       int32
	Limit        int32
}

type ListWorkflowRunsByRepoRow struct {
	ID                    int64
	RepoID                int64
	WorkflowName          string
	SourceFile            string
	Status                string
	EventName             string
	CauseID               pgtype.Int8
	Ref                   string
	CommitSha             string
	ContainerSnapshotJson []byte
	TriggerPayloadJson    []byte
	StartedAt             pgtype.Timestamptz
	FinishedAt            pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	WorkflowToken         string
	TotalCount            int64
}

func (q *Queries) ListWorkflowRunsByRepo(ctx context.Context, arg ListWorkflowRunsByRepoParams) ([]ListWorkflowRunsByRepoRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowRunsByRepo,
		arg.RepoID,
		arg.WorkflowName,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowRunsByRepoRow{}
	for rows.Next() {
		var i ListWorkflowRunsByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.WorkflowName,
			&i.SourceFile,
			&i.Status,
			&i.EventName,
			&i.CauseID,
			&i.Ref,
			&i.CommitSha,
			&i.ContainerSnapshotJson,
			&i.TriggerPayloadJson,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.WorkflowToken,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkflowJobRunning = `-- name: MarkWorkflowJobRunning :exec
UPDATE workflow_job_runs
SET status = 'running', runner_id = $1, started_at = NOW()
WHERE id = $2
`

type MarkWorkflowJobRunningParams struct {
	RunnerID pgtype.Int8
	ID       int64
}

func (q *Queries) MarkWorkflowJobRunning(ctx context.Context, arg MarkWorkflowJobRunningParams) error {
	_, err := q.db.Exec(ctx, markWorkflowJobRunning, arg.RunnerID, arg.ID)
	return err
}

const markWorkflowJobTerminal = `-- name: MarkWorkflowJobTerminal :exec
UPDATE workflow_job_runs
SET status = $1,
    exit_code = $2,
    error_message = $3,
    finished_at = NOW()
WHERE id = $4
`

type MarkWorkflowJobTerminalParams struct {
	Status       string
	ExitCode     pgtype.Int4
	ErrorMessage string
	ID           int64
}

func (q *Queries) MarkWorkflowJobTerminal(ctx context.Context, arg MarkWorkflowJobTerminalParams) error {
	_, err := q.db.Exec(ctx, markWorkflowJobTerminal,
		arg.Status,
		arg.ExitCode,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const markWorkflowRunStarted = `-- name: MarkWorkflowRunStarted :exec
UPDATE workflow_runs
SET status = 'running', started_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkWorkflowRunStarted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markWorkflowRunStarted, id)
	return err
}

const markWorkflowRunTerminal = `-- name: MarkWorkflowRunTerminal :exec
UPDATE workflow_runs
SET status = $1, finished_at = NOW()
WHERE id = $2 AND status IN ('pending', 'running')
`

type MarkWorkflowRunTerminalParams struct {
	Status string
	ID     int64
}

func (q *Queries) MarkWorkflowRunTerminal(ctx context.Context, arg MarkWorkflowRunTerminalParams) error {
	_, err := q.db.Exec(ctx, markWorkflowRunTerminal, arg.Status, arg.ID)
	return err
}

const setWorkflowJobContainer = `-- name: SetWorkflowJobContainer :exec
UPDATE workflow_job_runs
SET container_id = $1
WHERE id = $2
`

type SetWorkflowJobContainerParams struct {
	ContainerID pgtype.Text
	ID          int64
}

func (q *Queries) SetWorkflowJobContainer(ctx context.Context, arg SetWorkflowJobContainerParams) error {
	_, err := q.db.Exec(ctx, setWorkflowJobContainer, arg.ContainerID, arg.ID)
	return err
}

const setWorkflowJobOutputs = `-- name: SetWorkflowJobOutputs :exec
UPDATE workflow_job_runs
SET job_outputs_json = $1::jsonb
WHERE id = $2
`

type SetWorkflowJobOutputsParams struct {
	Outputs []byte
	ID      int64
}

func (q *Queries) SetWorkflowJobOutputs(ctx context.Context, arg SetWorkflowJobOutputsParams) error {
	_, err := q.db.Exec(ctx, setWorkflowJobOutputs, arg.Outputs, arg.ID)
	return err
}

const setWorkflowJobStepOutputs = `-- name: SetWorkflowJobStepOutputs :exec
UPDATE workflow_job_runs
SET step_outputs_json = COALESCE(step_outputs_json, '{}'::jsonb) || jsonb_build_object($1, $2::jsonb)
WHERE id = $3
`

type SetWorkflowJobStepOutputsParams struct {
	StepID  interface{}
	Outputs []byte
	ID      int64
}

// Merge step outputs into the job's step_outputs_json. Uses jsonb || to
// upsert at the step_id level, preserving outputs from previously-completed steps.
func (q *Queries) SetWorkflowJobStepOutputs(ctx context.Context, arg SetWorkflowJobStepOutputsParams) error {
	_, err := q.db.Exec(ctx, setWorkflowJobStepOutputs, arg.StepID, arg.Outputs, arg.ID)
	return err
}

const skipRemainingWorkflowJobs = `-- name: SkipRemainingWorkflowJobs :exec
UPDATE workflow_job_runs
SET status = 'skipped', finished_at = NOW()
WHERE workflow_run_id = $1
  AND status = 'pending'
  AND sequence_index > $2
`

type SkipRemainingWorkflowJobsParams struct {
	WorkflowRunID      int64
	AfterSequenceIndex int32
}

func (q *Queries) SkipRemainingWorkflowJobs(ctx context.Context, arg SkipRemainingWorkflowJobsParams) error {
	_, err := q.db.Exec(ctx, skipRemainingWorkflowJobs, arg.WorkflowRunID, arg.AfterSequenceIndex)
	return err
}
