// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package attachmentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one

INSERT INTO attachments (
    storage_key, original_name, display_name, size_bytes,
    mime_type, detected_mime_type, sha256, kind, inline,
    status, actor_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, created_at
`

type CreateAttachmentParams struct {
	StorageKey       string
	OriginalName     string
	DisplayName      string
	SizeBytes        int64
	MimeType         string
	DetectedMimeType string
	Sha256           string
	Kind             string
	Inline           bool
	Status           string
	ActorID          int64
}

type CreateAttachmentRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

// ---- attachments (platform-level) ----
func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (CreateAttachmentRow, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.StorageKey,
		arg.OriginalName,
		arg.DisplayName,
		arg.SizeBytes,
		arg.MimeType,
		arg.DetectedMimeType,
		arg.Sha256,
		arg.Kind,
		arg.Inline,
		arg.Status,
		arg.ActorID,
	)
	var i CreateAttachmentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createCommentAttachment = `-- name: CreateCommentAttachment :exec

INSERT INTO comment_attachments (comment_id, attachment_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateCommentAttachmentParams struct {
	CommentID    int64
	AttachmentID int64
}

// ---- comment_attachments (junction) ----
func (q *Queries) CreateCommentAttachment(ctx context.Context, arg CreateCommentAttachmentParams) error {
	_, err := q.db.Exec(ctx, createCommentAttachment, arg.CommentID, arg.AttachmentID)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT a.id, a.storage_key, a.original_name, a.display_name,
       a.size_bytes, a.mime_type, a.detected_mime_type, a.sha256,
       a.kind, a.inline, a.status,
       a.actor_id, a.created_at, a.deleted_at
FROM attachments a
WHERE a.id = $1
`

type GetAttachmentRow struct {
	ID               int64
	StorageKey       string
	OriginalName     string
	DisplayName      string
	SizeBytes        int64
	MimeType         string
	DetectedMimeType string
	Sha256           string
	Kind             string
	Inline           bool
	Status           string
	ActorID          int64
	CreatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

func (q *Queries) GetAttachment(ctx context.Context, id int64) (GetAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i GetAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.OriginalName,
		&i.DisplayName,
		&i.SizeBytes,
		&i.MimeType,
		&i.DetectedMimeType,
		&i.Sha256,
		&i.Kind,
		&i.Inline,
		&i.Status,
		&i.ActorID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAttachmentIDsByComment = `-- name: ListAttachmentIDsByComment :many
SELECT attachment_id
FROM comment_attachments
WHERE comment_id = $1
ORDER BY attachment_id
`

func (q *Queries) ListAttachmentIDsByComment(ctx context.Context, commentID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAttachmentIDsByComment, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var attachment_id int64
		if err := rows.Scan(&attachment_id); err != nil {
			return nil, err
		}
		items = append(items, attachment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAttachment = `-- name: SoftDeleteAttachment :exec
UPDATE attachments
SET status = 'deleted', deleted_at = NOW()
WHERE id = $1 AND status <> 'deleted'
`

func (q *Queries) SoftDeleteAttachment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteAttachment, id)
	return err
}
