// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package actordb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActorByAgentSessionID = `-- name: GetActorByAgentSessionID :one
SELECT id FROM actors WHERE kind = 'agent_session' AND agent_session_id = $1
`

func (q *Queries) GetActorByAgentSessionID(ctx context.Context, agentSessionID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, getActorByAgentSessionID, agentSessionID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActorByBotID = `-- name: GetActorByBotID :one
SELECT id FROM actors WHERE kind = 'bot' AND bot_id = $1
`

func (q *Queries) GetActorByBotID(ctx context.Context, botID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, getActorByBotID, botID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActorByID = `-- name: GetActorByID :one
SELECT id, kind, display_name, user_id, role_key, workflow_run_id, agent_session_id, bot_id, created_at FROM actors WHERE id = $1
`

func (q *Queries) GetActorByID(ctx context.Context, id int64) (Actor, error) {
	row := q.db.QueryRow(ctx, getActorByID, id)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.UserID,
		&i.RoleKey,
		&i.WorkflowRunID,
		&i.AgentSessionID,
		&i.BotID,
		&i.CreatedAt,
	)
	return i, err
}

const getActorByRoleKey = `-- name: GetActorByRoleKey :one
SELECT id FROM actors WHERE kind = 'agent' AND role_key = $1
`

func (q *Queries) GetActorByRoleKey(ctx context.Context, roleKey pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, getActorByRoleKey, roleKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActorByUserID = `-- name: GetActorByUserID :one
SELECT id FROM actors WHERE kind = 'user' AND user_id = $1
`

func (q *Queries) GetActorByUserID(ctx context.Context, userID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, getActorByUserID, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActorByWorkflowRunID = `-- name: GetActorByWorkflowRunID :one
SELECT id FROM actors WHERE kind = 'workflow' AND workflow_run_id = $1
`

func (q *Queries) GetActorByWorkflowRunID(ctx context.Context, workflowRunID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, getActorByWorkflowRunID, workflowRunID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSystemActorID = `-- name: GetSystemActorID :one
SELECT id FROM actors WHERE kind = 'system' LIMIT 1
`

func (q *Queries) GetSystemActorID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getSystemActorID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertActor = `-- name: InsertActor :one

INSERT INTO actors (kind, display_name, user_id, role_key, workflow_run_id, agent_session_id, bot_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT DO NOTHING
RETURNING id
`

type InsertActorParams struct {
	Kind           string
	DisplayName    string
	UserID         pgtype.Int8
	RoleKey        pgtype.Text
	WorkflowRunID  pgtype.Int8
	AgentSessionID pgtype.Int8
	BotID          pgtype.Text
}

// Actor module queries.
// Ensure* methods use a two-step pattern: INSERT ... ON CONFLICT DO NOTHING
// RETURNING id, then fall back to a SELECT by the kind-specific key. The
// partial unique indexes in 00001_create_actors.sql guarantee at-most-one
// row per kind+key, so the INSERT is safe under concurrent calls (ON
// CONFLICT DO NOTHING silently discards the loser) and the follow-up
// SELECT always finds the winner.
func (q *Queries) InsertActor(ctx context.Context, arg InsertActorParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertActor,
		arg.Kind,
		arg.DisplayName,
		arg.UserID,
		arg.RoleKey,
		arg.WorkflowRunID,
		arg.AgentSessionID,
		arg.BotID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
