// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package actordb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureAgentRole = `-- name: EnsureAgentRole :one
INSERT INTO actors (kind, agent_role_key, display_name)
VALUES ('agent_role', $1, $2)
ON CONFLICT (agent_role_key) WHERE kind = 'agent_role' DO UPDATE
    SET display_name = EXCLUDED.display_name,
        updated_at = NOW()
RETURNING id, kind, user_id, agent_role_key, agent_session_id, workflow_run_id, display_name, created_at, updated_at
`

type EnsureAgentRoleParams struct {
	AgentRoleKey pgtype.Text
	DisplayName  string
}

func (q *Queries) EnsureAgentRole(ctx context.Context, arg EnsureAgentRoleParams) (Actor, error) {
	row := q.db.QueryRow(ctx, ensureAgentRole, arg.AgentRoleKey, arg.DisplayName)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.AgentRoleKey,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureAgentSession = `-- name: EnsureAgentSession :one
INSERT INTO actors (kind, agent_session_id, agent_role_key, display_name)
VALUES ('agent_session', $1, $2, $3)
ON CONFLICT (agent_session_id) WHERE kind = 'agent_session' DO UPDATE
    SET display_name = EXCLUDED.display_name,
        agent_role_key = EXCLUDED.agent_role_key,
        updated_at = NOW()
RETURNING id, kind, user_id, agent_role_key, agent_session_id, workflow_run_id, display_name, created_at, updated_at
`

type EnsureAgentSessionParams struct {
	AgentSessionID pgtype.Int8
	RoleKey        pgtype.Text
	DisplayName    string
}

func (q *Queries) EnsureAgentSession(ctx context.Context, arg EnsureAgentSessionParams) (Actor, error) {
	row := q.db.QueryRow(ctx, ensureAgentSession, arg.AgentSessionID, arg.RoleKey, arg.DisplayName)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.AgentRoleKey,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureBot = `-- name: EnsureBot :one
INSERT INTO actors (kind, agent_role_key, display_name)
VALUES ('bot', $1, $2)
ON CONFLICT (agent_role_key) WHERE kind = 'bot' DO UPDATE
    SET display_name = EXCLUDED.display_name,
        updated_at = NOW()
RETURNING id, kind, user_id, agent_role_key, agent_session_id, workflow_run_id, display_name, created_at, updated_at
`

type EnsureBotParams struct {
	Name        pgtype.Text
	DisplayName string
}

func (q *Queries) EnsureBot(ctx context.Context, arg EnsureBotParams) (Actor, error) {
	row := q.db.QueryRow(ctx, ensureBot, arg.Name, arg.DisplayName)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.AgentRoleKey,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureUser = `-- name: EnsureUser :one
INSERT INTO actors (kind, user_id, display_name)
VALUES ('user', $1, $2)
ON CONFLICT (user_id) WHERE kind = 'user' DO UPDATE
    SET display_name = EXCLUDED.display_name,
        updated_at = NOW()
RETURNING id, kind, user_id, agent_role_key, agent_session_id, workflow_run_id, display_name, created_at, updated_at
`

type EnsureUserParams struct {
	UserID      pgtype.Int8
	DisplayName string
}

// Idempotent: ON CONFLICT on the partial unique index for (kind='user', user_id)
// returns the existing row when the tuple already exists.
func (q *Queries) EnsureUser(ctx context.Context, arg EnsureUserParams) (Actor, error) {
	row := q.db.QueryRow(ctx, ensureUser, arg.UserID, arg.DisplayName)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.AgentRoleKey,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureWorkflowRun = `-- name: EnsureWorkflowRun :one
INSERT INTO actors (kind, workflow_run_id, display_name)
VALUES ('workflow_run', $1, $2)
ON CONFLICT (workflow_run_id) WHERE kind = 'workflow_run' DO UPDATE
    SET display_name = EXCLUDED.display_name,
        updated_at = NOW()
RETURNING id, kind, user_id, agent_role_key, agent_session_id, workflow_run_id, display_name, created_at, updated_at
`

type EnsureWorkflowRunParams struct {
	WorkflowRunID pgtype.Int8
	DisplayName   string
}

func (q *Queries) EnsureWorkflowRun(ctx context.Context, arg EnsureWorkflowRunParams) (Actor, error) {
	row := q.db.QueryRow(ctx, ensureWorkflowRun, arg.WorkflowRunID, arg.DisplayName)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.AgentRoleKey,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActorByID = `-- name: GetActorByID :one
SELECT id, kind, user_id, agent_role_key, agent_session_id, workflow_run_id, display_name, created_at, updated_at FROM actors WHERE id = $1
`

func (q *Queries) GetActorByID(ctx context.Context, id int64) (Actor, error) {
	row := q.db.QueryRow(ctx, getActorByID, id)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.AgentRoleKey,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActorByRef = `-- name: GetActorByRef :one
SELECT id, kind, user_id, agent_role_key, agent_session_id, workflow_run_id, display_name, created_at, updated_at FROM actors
WHERE kind = $1
  AND (
    ($2::BIGINT IS NOT NULL AND user_id = $2)
    OR ($3::TEXT IS NOT NULL AND agent_role_key = $3)
    OR ($4::BIGINT IS NOT NULL AND agent_session_id = $4)
    OR ($5::BIGINT IS NOT NULL AND workflow_run_id = $5)
  )
`

type GetActorByRefParams struct {
	Kind           string
	UserID         pgtype.Int8
	AgentRoleKey   pgtype.Text
	AgentSessionID pgtype.Int8
	WorkflowRunID  pgtype.Int8
}

// Look up an existing actor by (kind, discriminant). The caller
// constructs the WHERE clause by filling only the relevant column
// for the kind; the other discriminants are NULL and will not match
// any row of a different kind.
func (q *Queries) GetActorByRef(ctx context.Context, arg GetActorByRefParams) (Actor, error) {
	row := q.db.QueryRow(ctx, getActorByRef,
		arg.Kind,
		arg.UserID,
		arg.AgentRoleKey,
		arg.AgentSessionID,
		arg.WorkflowRunID,
	)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.AgentRoleKey,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
