// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package actordb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureAgentRole = `-- name: EnsureAgentRole :one
INSERT INTO actors (kind, display_name, repo_id, role_key)
VALUES ('agent_role', '@agent-' || $1, $2, $1)
ON CONFLICT (repo_id, role_key) WHERE kind = 'agent_role' DO NOTHING
RETURNING id, kind, display_name, user_id, agent_session_id, workflow_run_id, repo_id, role_key, bot_handle, created_at
`

type EnsureAgentRoleParams struct {
	RoleKey string
	RepoID  pgtype.Int8
}

// Idempotent upsert for kind='agent_role'. Display name is derived from
// the role key in @agent-<key> format.
func (q *Queries) EnsureAgentRole(ctx context.Context, arg EnsureAgentRoleParams) (Actor, error) {
	row := q.db.QueryRow(ctx, ensureAgentRole, arg.RoleKey, arg.RepoID)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.UserID,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.RepoID,
		&i.RoleKey,
		&i.BotHandle,
		&i.CreatedAt,
	)
	return i, err
}

const ensureAgentSession = `-- name: EnsureAgentSession :one
INSERT INTO actors (kind, display_name, agent_session_id)
SELECT 'agent_session',
       COALESCE(NULLIF(s.role, ''), '?') || ' #' || s.id,
       $1
FROM agent_sessions s WHERE s.id = $1
ON CONFLICT (agent_session_id) WHERE kind = 'agent_session' DO NOTHING
RETURNING id, kind, display_name, user_id, agent_session_id, workflow_run_id, repo_id, role_key, bot_handle, created_at
`

// Idempotent upsert for kind='agent_session'.
func (q *Queries) EnsureAgentSession(ctx context.Context, agentSessionID pgtype.Int8) (Actor, error) {
	row := q.db.QueryRow(ctx, ensureAgentSession, agentSessionID)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.UserID,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.RepoID,
		&i.RoleKey,
		&i.BotHandle,
		&i.CreatedAt,
	)
	return i, err
}

const ensureBot = `-- name: EnsureBot :one
INSERT INTO actors (kind, display_name, bot_handle)
VALUES ('bot', $1, $1)
ON CONFLICT (bot_handle) WHERE kind = 'bot' DO NOTHING
RETURNING id, kind, display_name, user_id, agent_session_id, workflow_run_id, repo_id, role_key, bot_handle, created_at
`

// Idempotent upsert for kind='bot'. Reserved for PAT/OAuth apps.
func (q *Queries) EnsureBot(ctx context.Context, botHandle string) (Actor, error) {
	row := q.db.QueryRow(ctx, ensureBot, botHandle)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.UserID,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.RepoID,
		&i.RoleKey,
		&i.BotHandle,
		&i.CreatedAt,
	)
	return i, err
}

const ensureUser = `-- name: EnsureUser :one
INSERT INTO actors (kind, display_name, user_id)
SELECT 'user', u.username, $1
FROM users u WHERE u.id = $1
ON CONFLICT (user_id) WHERE kind = 'user' DO NOTHING
RETURNING id, kind, display_name, user_id, agent_session_id, workflow_run_id, repo_id, role_key, bot_handle, created_at
`

// Idempotent upsert for kind='user'. Reads display_name from the users
// table on insert so it's always current.
func (q *Queries) EnsureUser(ctx context.Context, userID pgtype.Int8) (Actor, error) {
	row := q.db.QueryRow(ctx, ensureUser, userID)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.UserID,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.RepoID,
		&i.RoleKey,
		&i.BotHandle,
		&i.CreatedAt,
	)
	return i, err
}

const ensureWorkflowRun = `-- name: EnsureWorkflowRun :one
INSERT INTO actors (kind, display_name, workflow_run_id)
SELECT 'workflow_run',
       'workflow/' || wr.workflow_name || '#' || wr.id,
       $1
FROM workflow_runs wr WHERE wr.id = $1
ON CONFLICT (workflow_run_id) WHERE kind = 'workflow_run' DO NOTHING
RETURNING id, kind, display_name, user_id, agent_session_id, workflow_run_id, repo_id, role_key, bot_handle, created_at
`

// Idempotent upsert for kind='workflow_run'.
func (q *Queries) EnsureWorkflowRun(ctx context.Context, workflowRunID pgtype.Int8) (Actor, error) {
	row := q.db.QueryRow(ctx, ensureWorkflowRun, workflowRunID)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.UserID,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.RepoID,
		&i.RoleKey,
		&i.BotHandle,
		&i.CreatedAt,
	)
	return i, err
}

const getActorByID = `-- name: GetActorByID :one

SELECT id, kind, display_name,
       user_id, agent_session_id, workflow_run_id,
       repo_id, role_key, bot_handle,
       created_at
FROM actors
WHERE id = $1
`

// ---- actors ----
func (q *Queries) GetActorByID(ctx context.Context, id int64) (Actor, error) {
	row := q.db.QueryRow(ctx, getActorByID, id)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.UserID,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.RepoID,
		&i.RoleKey,
		&i.BotHandle,
		&i.CreatedAt,
	)
	return i, err
}

const getActorByRef = `-- name: GetActorByRef :one
SELECT id, kind, display_name,
       user_id, agent_session_id, workflow_run_id,
       repo_id, role_key, bot_handle,
       created_at
FROM actors
WHERE kind = $1
  AND ($1::TEXT != 'user'           OR user_id = $2)
  AND ($1::TEXT != 'agent_session'  OR agent_session_id = $3)
  AND ($1::TEXT != 'agent_role'     OR (repo_id = $4 AND role_key = $5))
  AND ($1::TEXT != 'workflow_run'   OR workflow_run_id = $6)
  AND ($1::TEXT != 'bot'            OR bot_handle = $7)
  AND ($1::TEXT != 'system'         OR id = 1)
`

type GetActorByRefParams struct {
	Kind           string
	UserID         pgtype.Int8
	AgentSessionID pgtype.Int8
	RepoID         pgtype.Int8
	RoleKey        string
	WorkflowRunID  pgtype.Int8
	BotHandle      string
}

// Look up an actor by its natural key. Only the columns relevant to the
// given kind are used in the WHERE clause; NULL-safe comparisons prevent
// false matches across kinds.
func (q *Queries) GetActorByRef(ctx context.Context, arg GetActorByRefParams) (Actor, error) {
	row := q.db.QueryRow(ctx, getActorByRef,
		arg.Kind,
		arg.UserID,
		arg.AgentSessionID,
		arg.RepoID,
		arg.RoleKey,
		arg.WorkflowRunID,
		arg.BotHandle,
	)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.UserID,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.RepoID,
		&i.RoleKey,
		&i.BotHandle,
		&i.CreatedAt,
	)
	return i, err
}

const systemActor = `-- name: SystemActor :one
SELECT id, kind, display_name,
       user_id, agent_session_id, workflow_run_id,
       repo_id, role_key, bot_handle,
       created_at
FROM actors
WHERE id = 1
`

// Returns the singleton system actor (id=1), seeded by the migration.
func (q *Queries) SystemActor(ctx context.Context) (Actor, error) {
	row := q.db.QueryRow(ctx, systemActor)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.UserID,
		&i.AgentSessionID,
		&i.WorkflowRunID,
		&i.RepoID,
		&i.RoleKey,
		&i.BotHandle,
		&i.CreatedAt,
	)
	return i, err
}
