// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tokendb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	ID         int64
	UserID     int64
	Name       string
	Prefix     string
	HashedKey  string
	Scopes     []string
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	ActorID    int64
}

type Actor struct {
	ID             int64
	Kind           string
	UserID         pgtype.Int8
	AgentRoleKey   pgtype.Text
	AgentSessionID pgtype.Int8
	WorkflowRunID  pgtype.Int8
	DisplayName    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
