// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package tokendb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one
INSERT INTO access_tokens (user_id, name, prefix, hashed_key, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, prefix, hashed_key, scopes, last_used_at, expires_at, revoked_at, created_at
`

type CreateTokenParams struct {
	UserID    int64
	Name      string
	Prefix    string
	HashedKey string
	Scopes    []string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (AccessToken, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.HashedKey,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.HashedKey,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTokenByPrefix = `-- name: GetTokenByPrefix :one
SELECT id, user_id, name, prefix, hashed_key, scopes, last_used_at, expires_at, revoked_at, created_at FROM access_tokens WHERE prefix = $1
`

func (q *Queries) GetTokenByPrefix(ctx context.Context, prefix string) (AccessToken, error) {
	row := q.db.QueryRow(ctx, getTokenByPrefix, prefix)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.HashedKey,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTokensByUser = `-- name: ListTokensByUser :many
SELECT id, user_id, name, prefix, hashed_key, scopes, last_used_at, expires_at, revoked_at, created_at FROM access_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTokensByUser(ctx context.Context, userID int64) ([]AccessToken, error) {
	rows, err := q.db.Query(ctx, listTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessToken{}
	for rows.Next() {
		var i AccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.HashedKey,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToken = `-- name: RevokeToken :execrows
UPDATE access_tokens
SET revoked_at = NOW()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeTokenParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchTokenLastUsed = `-- name: TouchTokenLastUsed :exec
UPDATE access_tokens
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchTokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchTokenLastUsed, id)
	return err
}
