// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package releasedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BranchProtection struct {
	ID               int64
	RepoID           int64
	Pattern          string
	ForbidForcePush  bool
	ForbidDelete     bool
	ForbidDirectPush bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Organization struct {
	ID          int64
	Name        string
	DisplayName string
	Description string
	AvatarUrl   string
	CreatedBy   int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type OrganizationMember struct {
	OrgID   int64
	UserID  int64
	Role    string
	AddedBy int64
	AddedAt pgtype.Timestamptz
}

type Release struct {
	ID              int64
	RepoID          int64
	TagName         string
	TargetCommitSha string
	Title           string
	Notes           string
	IsDraft         bool
	PublishedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ReleaseAsset struct {
	ID          int64
	ReleaseID   int64
	Name        string
	ContentType string
	SizeBytes   int64
	StorageKey  string
	CreatedAt   pgtype.Timestamptz
}

type Repo struct {
	ID            int64
	OwnerUserID   pgtype.Int8
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerOrgID    pgtype.Int8
}

type RepoMember struct {
	RepoID  int64
	UserID  int64
	Role    string
	AddedBy int64
	AddedAt pgtype.Timestamptz
}

type RepoVariable struct {
	ID        int64
	RepoID    int64
	Name      string
	Value     string
	Kind      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
