// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package releasedb

import (
	"context"
)

const countReleasesByRepo = `-- name: CountReleasesByRepo :one
SELECT COUNT(*) FROM releases WHERE repo_id = $1
`

func (q *Queries) CountReleasesByRepo(ctx context.Context, repoID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReleasesByRepo, repoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReleasesByRepoDraft = `-- name: CountReleasesByRepoDraft :one
SELECT COUNT(*) FROM releases WHERE repo_id = $1 AND is_draft = $2
`

type CountReleasesByRepoDraftParams struct {
	RepoID  int64
	IsDraft bool
}

func (q *Queries) CountReleasesByRepoDraft(ctx context.Context, arg CountReleasesByRepoDraftParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReleasesByRepoDraft, arg.RepoID, arg.IsDraft)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO release_assets (release_id, name, content_type, size_bytes, storage_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, release_id, name, content_type, size_bytes, storage_key, created_at
`

type CreateAssetParams struct {
	ReleaseID   int64
	Name        string
	ContentType string
	SizeBytes   int64
	StorageKey  string
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (ReleaseAsset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ReleaseID,
		arg.Name,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
	)
	var i ReleaseAsset
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (repo_id, tag_name, target_commit_sha, title, notes, is_draft)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, repo_id, tag_name, target_commit_sha, title, notes, is_draft, published_at, created_at, updated_at
`

type CreateReleaseParams struct {
	RepoID          int64
	TagName         string
	TargetCommitSha string
	Title           string
	Notes           string
	IsDraft         bool
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, createRelease,
		arg.RepoID,
		arg.TagName,
		arg.TargetCommitSha,
		arg.Title,
		arg.Notes,
		arg.IsDraft,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TagName,
		&i.TargetCommitSha,
		&i.Title,
		&i.Notes,
		&i.IsDraft,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :execrows
DELETE FROM release_assets WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAsset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRelease = `-- name: DeleteRelease :execrows
DELETE FROM releases WHERE id = $1
`

func (q *Queries) DeleteRelease(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRelease, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, release_id, name, content_type, size_bytes, storage_key, created_at FROM release_assets WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id int64) (ReleaseAsset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i ReleaseAsset
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetByReleaseAndName = `-- name: GetAssetByReleaseAndName :one
SELECT id, release_id, name, content_type, size_bytes, storage_key, created_at FROM release_assets WHERE release_id = $1 AND name = $2
`

type GetAssetByReleaseAndNameParams struct {
	ReleaseID int64
	Name      string
}

func (q *Queries) GetAssetByReleaseAndName(ctx context.Context, arg GetAssetByReleaseAndNameParams) (ReleaseAsset, error) {
	row := q.db.QueryRow(ctx, getAssetByReleaseAndName, arg.ReleaseID, arg.Name)
	var i ReleaseAsset
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const getReleaseByID = `-- name: GetReleaseByID :one
SELECT id, repo_id, tag_name, target_commit_sha, title, notes, is_draft, published_at, created_at, updated_at FROM releases WHERE id = $1
`

func (q *Queries) GetReleaseByID(ctx context.Context, id int64) (Release, error) {
	row := q.db.QueryRow(ctx, getReleaseByID, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TagName,
		&i.TargetCommitSha,
		&i.Title,
		&i.Notes,
		&i.IsDraft,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReleaseByRepoAndTag = `-- name: GetReleaseByRepoAndTag :one
SELECT id, repo_id, tag_name, target_commit_sha, title, notes, is_draft, published_at, created_at, updated_at FROM releases WHERE repo_id = $1 AND tag_name = $2
`

type GetReleaseByRepoAndTagParams struct {
	RepoID  int64
	TagName string
}

func (q *Queries) GetReleaseByRepoAndTag(ctx context.Context, arg GetReleaseByRepoAndTagParams) (Release, error) {
	row := q.db.QueryRow(ctx, getReleaseByRepoAndTag, arg.RepoID, arg.TagName)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TagName,
		&i.TargetCommitSha,
		&i.Title,
		&i.Notes,
		&i.IsDraft,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssetsByRelease = `-- name: ListAssetsByRelease :many
SELECT id, release_id, name, content_type, size_bytes, storage_key, created_at FROM release_assets
WHERE release_id = $1
ORDER BY name
`

func (q *Queries) ListAssetsByRelease(ctx context.Context, releaseID int64) ([]ReleaseAsset, error) {
	rows, err := q.db.Query(ctx, listAssetsByRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseAsset{}
	for rows.Next() {
		var i ReleaseAsset
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.Name,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesByRepo = `-- name: ListReleasesByRepo :many
SELECT id, repo_id, tag_name, target_commit_sha, title, notes, is_draft, published_at, created_at, updated_at FROM releases
WHERE repo_id = $1
ORDER BY published_at DESC NULLS LAST, created_at DESC
LIMIT $2 OFFSET $3
`

type ListReleasesByRepoParams struct {
	RepoID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListReleasesByRepo(ctx context.Context, arg ListReleasesByRepoParams) ([]Release, error) {
	rows, err := q.db.Query(ctx, listReleasesByRepo, arg.RepoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.TagName,
			&i.TargetCommitSha,
			&i.Title,
			&i.Notes,
			&i.IsDraft,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesByRepoDraft = `-- name: ListReleasesByRepoDraft :many
SELECT id, repo_id, tag_name, target_commit_sha, title, notes, is_draft, published_at, created_at, updated_at FROM releases
WHERE repo_id = $1 AND is_draft = $2
ORDER BY published_at DESC NULLS LAST, created_at DESC
LIMIT $3 OFFSET $4
`

type ListReleasesByRepoDraftParams struct {
	RepoID  int64
	IsDraft bool
	Limit   int32
	Offset  int32
}

func (q *Queries) ListReleasesByRepoDraft(ctx context.Context, arg ListReleasesByRepoDraftParams) ([]Release, error) {
	rows, err := q.db.Query(ctx, listReleasesByRepoDraft,
		arg.RepoID,
		arg.IsDraft,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.TagName,
			&i.TargetCommitSha,
			&i.Title,
			&i.Notes,
			&i.IsDraft,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishRelease = `-- name: PublishRelease :one
UPDATE releases
SET is_draft    = FALSE,
    published_at = NOW(),
    updated_at   = NOW()
WHERE id = $1 AND is_draft = TRUE
RETURNING id, repo_id, tag_name, target_commit_sha, title, notes, is_draft, published_at, created_at, updated_at
`

func (q *Queries) PublishRelease(ctx context.Context, id int64) (Release, error) {
	row := q.db.QueryRow(ctx, publishRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TagName,
		&i.TargetCommitSha,
		&i.Title,
		&i.Notes,
		&i.IsDraft,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRelease = `-- name: UpdateRelease :one
UPDATE releases
SET tag_name          = $2,
    target_commit_sha = $3,
    title             = $4,
    notes             = $5,
    updated_at        = NOW()
WHERE id = $1
RETURNING id, repo_id, tag_name, target_commit_sha, title, notes, is_draft, published_at, created_at, updated_at
`

type UpdateReleaseParams struct {
	ID              int64
	TagName         string
	TargetCommitSha string
	Title           string
	Notes           string
}

func (q *Queries) UpdateRelease(ctx context.Context, arg UpdateReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, updateRelease,
		arg.ID,
		arg.TagName,
		arg.TargetCommitSha,
		arg.Title,
		arg.Notes,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TagName,
		&i.TargetCommitSha,
		&i.Title,
		&i.Notes,
		&i.IsDraft,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
