// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package orgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID          int64
	Name        string
	DisplayName string
	Description string
	AvatarUrl   string
	CreatedBy   int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type OrganizationMember struct {
	OrgID   int64
	UserID  int64
	Role    string
	AddedBy int64
	AddedAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
