// Hangrix script step bootstrap — generated by hangrix-runner.
// This file is written to /tmp/hangrix/script-step-<id>/bootstrap.mjs
// and executed via: node /tmp/hangrix/script-step-<id>/bootstrap.mjs
//
// It constructs a read-only workflow context from environment variables,
// builds the hangrix SDK object, imports+executes the user script, and
// serialises any error for the runner to parse from stderr/system logs.

import { readFile, appendFile } from "node:fs/promises";
import { createHash } from "node:crypto";

// ---------------------------------------------------------------------------
// Context (read-only, derived from env injected by hangrix-runner)
// ---------------------------------------------------------------------------

const ctx = Object.freeze({
  repo: {
    owner: envOr("HANGRIX_REPO_OWNER"),
    name:  envOr("HANGRIX_REPO_NAME"),
  },
  workflow: {
    run_id:     envOr("HANGRIX_WORKFLOW_RUN_ID"),
    name:       envOr("HANGRIX_WORKFLOW_NAME"),
    job_key:    envOr("HANGRIX_WORKFLOW_JOB_KEY"),
    event_name: envOpt("HANGRIX_EVENT_NAME"),
    ref:        envOpt("HANGRIX_CHECKOUT_REF"),
    sha:        envOpt("HANGRIX_COMMIT_SHA"),
    tag:        envOpt("HANGRIX_TAG"),
  },
  trigger_actor: {
    kind:         envOpt("HANGRIX_TRIGGER_ACTOR_KIND"),
    id:           envOpt("HANGRIX_TRIGGER_ACTOR_ID"),
    display_name: envOpt("HANGRIX_TRIGGER_ACTOR_DISPLAY_NAME"),
  },
});

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function envOr(key) {
  const v = process.env[key];
  if (v === undefined) throw new Error(`required env ${key} not set`);
  return v;
}

function envOpt(key) {
  return process.env[key] || "";
}

const BASE_URL = envOr("HANGRIX_PLATFORM_BASE_URL");
const WORKFLOW_TOKEN = envOr("HANGRIX_WORKFLOW_TOKEN");
const STEP_OUTPUT_FILE = envOr("HANGRIX_STEP_OUTPUT_FILE");

// Accumulated outputs written by hangrix.workflow.setOutput().
// Flushed to $HANGRIX_STEP_OUTPUT_FILE on successful completion.
const _outputs = {};

// ---------------------------------------------------------------------------
// Platform API caller
// ---------------------------------------------------------------------------

async function callPlatform(method, path, body) {
  const url = BASE_URL.replace(/\/+$/, "") + path;
  const headers = {
    "Authorization": `Bearer ${WORKFLOW_TOKEN}`,
  };

  let reqBody = null;
  if (body !== undefined && body !== null) {
    headers["Content-Type"] = "application/json";
    reqBody = JSON.stringify(body);
  }

  const resp = await fetch(url, { method, headers, body: reqBody });

  if (!resp.ok) {
    let details;
    try { details = await resp.json(); } catch { details = null; }
    const err = new Error(details?.message || `API ${method} ${path} failed with ${resp.status}`);
    err.name = "HangrixApiError";
    err.code = apiErrorCode(resp.status, details);
    err.status = resp.status;
    err.details = details;
    throw err;
  }

  if (resp.status === 204) return null;
  return resp.json();
}

function apiErrorCode(status, details) {
  if (details?.code) return details.code;
  switch (status) {
    case 400: return "validation_failed";
    case 401: return "unauthorized";
    case 403: return "forbidden";
    case 404: return "not_found";
    case 409: return "conflict";
    case 413: return "upload_failed";
    case 422: return "validation_failed";
    default:  return "internal_error";
  }
}

// ---------------------------------------------------------------------------
// Multipart upload helper (for hangrix.attachment.upload)
// ---------------------------------------------------------------------------

async function uploadMultipart(path, filePath, fields, fileName) {
  const { open } = await import("node:fs/promises");
  const { createReadStream } = await import("node:fs");
  const { stat } = await import("node:fs/promises");

  // Read file into a Buffer for the multipart body.
  const fh = await open(filePath, "r");
  const fileStat = await stat(filePath);
  const fileBuf = Buffer.alloc(fileStat.size);
  await fh.read(fileBuf, 0, fileStat.size, 0);
  await fh.close();

  // Build multipart/form-data manually without an external dependency.
  const boundary = `----HangrixFormBoundary${createHash("sha256").update(String(Date.now())).digest("hex").slice(0, 16)}`;

  const parts = [];
  const encoder = new TextEncoder();

  // Fields
  for (const [k, v] of Object.entries(fields)) {
    parts.push(encoder.encode(`--${boundary}\r\nContent-Disposition: form-data; name="${k}"\r\n\r\n${v}\r\n`));
  }

  // File
  parts.push(encoder.encode(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="${fileName}"\r\nContent-Type: application/octet-stream\r\n\r\n`));
  parts.push(fileBuf);
  parts.push(encoder.encode(`\r\n--${boundary}--\r\n`));

  const totalLen = parts.reduce((s, p) => s + p.length, 0);
  const body = Buffer.concat(parts, totalLen);

  const url = BASE_URL.replace(/\/+$/, "") + path;
  const resp = await fetch(url, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${WORKFLOW_TOKEN}`,
      "Content-Type": `multipart/form-data; boundary=${boundary}`,
    },
    body,
  });

  if (!resp.ok) {
    let details;
    try { details = await resp.json(); } catch { details = null; }
    const err = new Error(details?.message || `upload failed with ${resp.status}`);
    err.name = "HangrixApiError";
    err.code = "upload_failed";
    err.status = resp.status;
    err.details = details;
    throw err;
  }

  return resp.json();
}

// ---------------------------------------------------------------------------
// hangrix SDK
// ---------------------------------------------------------------------------

const hangrix = Object.freeze({
  // ---- issue ----
  issue: Object.freeze({
    async get(input) {
      return callPlatform("GET", `/api/repos/${ctx.repo.owner}/${ctx.repo.name}/issues/${input.number}`);
    },
    async comment(input) {
      return callPlatform("POST", `/api/repos/${ctx.repo.owner}/${ctx.repo.name}/issues/${input.number}/comments`, {
        content:   input.content,
        file_path: input.file_path,
        line:      input.line,
      });
    },
    async listComments(input) {
      const timeline = await callPlatform("GET", `/api/repos/${ctx.repo.owner}/${ctx.repo.name}/issues/${input.number}/timeline`);
      return {
        comments: (timeline?.events || [])
          .filter(e => e.kind === "comment" || e.kind === "comment_created")
          .map(e => e.payload || e),
      };
    },
    async updateTodo(input) {
      if (!input.issue_number) {
        const err = new Error("updateTodo: issue_number is required");
        err.name = "HangrixApiError";
        err.code = "validation_failed";
        err.status = 422;
        throw err;
      }
      return callPlatform("POST", `/api/repos/${ctx.repo.owner}/${ctx.repo.name}/issues/${input.issue_number}/todos`, {
        todo_id:  input.todo_id,
        content:  input.content,
        status:   input.status,
        position: input.position,
      });
    },
  }),

  // ---- attachment ----
  attachment: Object.freeze({
    async upload(input) {
      const { resolve, normalize } = await import("node:path");
      const absPath = resolve(normalize(input.path));

      // Path must be under /workspace — prevent traversal.
      if (!absPath.startsWith("/workspace")) {
        const err = new Error(`attachment path "${input.path}" is outside /workspace`);
        err.name = "HangrixApiError";
        err.code = "forbidden";
        err.status = 403;
        throw err;
      }

      const fileName = input.display_name || absPath.split("/").pop();
      const fields = {};
      if (input.display_name) fields.display_name = input.display_name;
      if (input.inline !== undefined) fields.inline = String(input.inline);
      if (input.comment_id) fields.comment_id = String(input.comment_id);

      return uploadMultipart(
        `/api/repos/${ctx.repo.owner}/${ctx.repo.name}/issues/attachments`,
        absPath,
        fields,
        fileName,
      );
    },
  }),

  // ---- release ----
  release: Object.freeze({
    async create(input) {
      return callPlatform("POST", `/api/repos/${ctx.repo.owner}/${ctx.repo.name}/releases`, {
        tag_name: input.tag_name,
        title:    input.title,
        notes:    input.notes,
      });
    },
    async update(input) {
      return callPlatform("PATCH", `/api/repos/${ctx.repo.owner}/${ctx.repo.name}/releases/${input.release_id}`, {
        title:    input.title,
        notes:    input.notes,
        tag_name: input.tag_name,
      });
    },
    async uploadAsset(input) {
      const { resolve, normalize } = await import("node:path");
      const absPath = resolve(normalize(input.path));

      if (!absPath.startsWith("/workspace")) {
        const err = new Error(`asset path "${input.path}" is outside /workspace`);
        err.name = "HangrixApiError";
        err.code = "forbidden";
        err.status = 403;
        throw err;
      }

      const fileName = input.name || absPath.split("/").pop();
      const fields = { name: fileName };
      if (input.content_type) fields.content_type = input.content_type;

      return uploadMultipart(
        `/api/repos/${ctx.repo.owner}/${ctx.repo.name}/releases/${input.release_id}/assets`,
        absPath,
        fields,
        fileName,
      );
    },
    async publish(input) {
      return callPlatform("POST", `/api/repos/${ctx.repo.owner}/${ctx.repo.name}/releases/${input.release_id}/publish`);
    },
  }),

  // ---- workflow ----
  workflow: Object.freeze({
    getContext() {
      // Return a frozen shallow copy so scripts can't mutate the real context.
      return Object.freeze(structuredClone(ctx));
    },
    getStepOutputs(stepId) {
      // STEP_OUTPUTS_JSON is injected by the runner as a JSON env var
      // containing accumulated outputs from previous steps.
      const raw = process.env["HANGRIX_STEP_OUTPUTS_JSON"];
      if (!raw) return stepId ? {} : {};
      const all = JSON.parse(raw);
      if (stepId) return all[stepId] || {};
      return all;
    },
    setOutput(name, value) {
      if (typeof name !== "string" || name.length === 0) {
        throw new Error("setOutput: name must be a non-empty string");
      }
      _outputs[name] = String(value);
    },
  }),

  // ---- core ----
  core: Object.freeze({
    log(...args) {
      console.log(...args);
    },
  }),
});

// ---------------------------------------------------------------------------
// Flush step outputs
// ---------------------------------------------------------------------------

async function flushOutputs() {
  if (Object.keys(_outputs).length === 0) return;
  const lines = Object.entries(_outputs).map(([k, v]) => `${k}=${v}`).join("\n") + "\n";
  await appendFile(STEP_OUTPUT_FILE, lines, "utf-8");
}

// ---------------------------------------------------------------------------
// Script execution
// ---------------------------------------------------------------------------

const SCRIPT_FILE = process.env["HANGRIX_SCRIPT_STEP_USER_FILE"];
if (!SCRIPT_FILE) {
  console.error(JSON.stringify({
    error: "ConfigError",
    message: "HANGRIX_SCRIPT_STEP_USER_FILE not set — bootstrap cannot locate user script",
  }));
  process.exit(1);
}

try {
  // Use dynamic import so the user script runs as an ES module.
  // The user script receives `hangrix` as a global-like import — but
  // dynamic import doesn't inject globals. Instead we write a wrapper
  // that re-exports the SDK, and the user script imports it.
  //
  // Design choice: we import the user script directly. The user script
  // accesses hangrix via a global that we set here.
  globalThis.hangrix = hangrix;

  await import(SCRIPT_FILE);

  // Flush outputs after successful execution.
  await flushOutputs();

} catch (err) {
  // Serialise the error according to the four-layer model so the runner
  // can parse it from stderr and classify it.
  const serialised = {
    error: err.name === "HangrixApiError" ? "PlatformApiError" : "ScriptExecutionError",
    message: err.message,
  };

  if (err.name === "HangrixApiError") {
    serialised.code = err.code;
    serialised.status = err.status;
    if (err.details) serialised.details = err.details;
  }

  // If the error has a stack, include it (truncated).
  if (err.stack) {
    // Keep only the first 30 lines of the stack.
    const lines = err.stack.split("\n");
    serialised.stack = lines.slice(0, 30).join("\n");
  }

  console.error(JSON.stringify(serialised));
  process.exit(1);
}
