// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package runnerdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendMessage = `-- name: AppendMessage :one

INSERT INTO agent_session_messages (
    session_id, seq, kind, role, content, event_name,
    tool_call_id, tool_name, payload
)
SELECT
    $1,
    COALESCE(MAX(seq), 0) + 1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8::jsonb
FROM agent_session_messages WHERE session_id = $1
RETURNING id, session_id, seq, kind, role, content, event_name, tool_call_id, tool_name, payload, created_at
`

type AppendMessageParams struct {
	SessionID  int64
	Kind       string
	Role       string
	Content    string
	EventName  string
	ToolCallID string
	ToolName   string
	Payload    []byte
}

// ---- messages ----
// COALESCE(MAX(seq)+1, 1) is racy under concurrent appends; the UNIQUE
// (session_id, seq) constraint catches collisions and the caller retries.
func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (AgentSessionMessage, error) {
	row := q.db.QueryRow(ctx, appendMessage,
		arg.SessionID,
		arg.Kind,
		arg.Role,
		arg.Content,
		arg.EventName,
		arg.ToolCallID,
		arg.ToolName,
		arg.Payload,
	)
	var i AgentSessionMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Seq,
		&i.Kind,
		&i.Role,
		&i.Content,
		&i.EventName,
		&i.ToolCallID,
		&i.ToolName,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const archiveSessionsByIssue = `-- name: ArchiveSessionsByIssue :execrows
UPDATE agent_sessions
SET status               = 'archived',
    ended_at             = COALESCE(ended_at, NOW()),
    session_token_sealed = NULL
WHERE repo_id      = $1
  AND issue_number = $2
  AND status      != 'archived'
`

type ArchiveSessionsByIssueParams struct {
	RepoID      pgtype.Int8
	IssueNumber pgtype.Int4
}

// Flip every non-archived session on this (repo, issue) to archived.
// Driven by issue.closed / issue.merged: the parent issue is the only
// thing that can archive sessions — there is no per-session admin
// archive button (docs/agent-config.md §"Session 模型"). Already-archived
// rows are skipped so the call is idempotent. session_token_sealed is
// NULL'd so a leaked DB snapshot of an archived session can't expose the
// bearer plaintext.
func (q *Queries) ArchiveSessionsByIssue(ctx context.Context, arg ArchiveSessionsByIssueParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveSessionsByIssue, arg.RepoID, arg.IssueNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimNextSessionLock = `-- name: ClaimNextSessionLock :one
SELECT id, runner_id, repo_id, issue_number, status, role, model, agent_image, working_branch, base_branch, host_addendum, env, session_token_prefix, session_token_hash, session_token_sealed, session_token_revoked_at, exit_code, error_message, created_by, created_at, claimed_at, started_at, ended_at, repo_sha, role_key, cause_kind, cause_id, role_config FROM agent_sessions
WHERE status = 'pending'
  AND (runner_id = $1 OR runner_id IS NULL)
ORDER BY created_at ASC, id ASC
FOR UPDATE SKIP LOCKED
LIMIT 1
`

// Skip-locked claim: pins the oldest pending session this runner is
// eligible to run. M7a relaxed the rule from "pinned-to-this-runner
// only" to "pinned OR unpinned": the spawner now leaves runner_id NULL
// when no pre-assignment policy applies, and any eligible runner picks
// the row up. The follow-up ClaimSessionUpdate writes runner_id so the
// audit row records who actually ran it.
func (q *Queries) ClaimNextSessionLock(ctx context.Context, runnerID pgtype.Int8) (AgentSession, error) {
	row := q.db.QueryRow(ctx, claimNextSessionLock, runnerID)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.RunnerID,
		&i.RepoID,
		&i.IssueNumber,
		&i.Status,
		&i.Role,
		&i.Model,
		&i.AgentImage,
		&i.WorkingBranch,
		&i.BaseBranch,
		&i.HostAddendum,
		&i.Env,
		&i.SessionTokenPrefix,
		&i.SessionTokenHash,
		&i.SessionTokenSealed,
		&i.SessionTokenRevokedAt,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.RepoSha,
		&i.RoleKey,
		&i.CauseKind,
		&i.CauseID,
		&i.RoleConfig,
	)
	return i, err
}

const claimPendingInputsLock = `-- name: ClaimPendingInputsLock :many
SELECT id, session_id, seq, payload, consumed_at, created_at FROM agent_session_inputs
WHERE session_id = $1 AND consumed_at IS NULL
ORDER BY seq ASC
FOR UPDATE SKIP LOCKED
LIMIT $2
`

type ClaimPendingInputsLockParams struct {
	SessionID int64
	Lim       int32
}

func (q *Queries) ClaimPendingInputsLock(ctx context.Context, arg ClaimPendingInputsLockParams) ([]AgentSessionInput, error) {
	rows, err := q.db.Query(ctx, claimPendingInputsLock, arg.SessionID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSessionInput{}
	for rows.Next() {
		var i AgentSessionInput
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.Payload,
			&i.ConsumedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimSessionUpdate = `-- name: ClaimSessionUpdate :exec
UPDATE agent_sessions
SET status = 'claimed',
    claimed_at = NOW(),
    runner_id = $1
WHERE id = $2
`

type ClaimSessionUpdateParams struct {
	RunnerID pgtype.Int8
	ID       int64
}

// Pins runner_id at claim time so unpinned rows record who took them.
func (q *Queries) ClaimSessionUpdate(ctx context.Context, arg ClaimSessionUpdateParams) error {
	_, err := q.db.Exec(ctx, claimSessionUpdate, arg.RunnerID, arg.ID)
	return err
}

const createRunner = `-- name: CreateRunner :one

INSERT INTO runners (
    name, owner_user_id, visibility, status,
    enroll_token_prefix, enroll_token_hash, created_by
) VALUES (
    $1,
    $2,
    $3,
    'pending',
    $4,
    $5,
    $6
)
RETURNING id, name, owner_user_id, visibility, status, capabilities, last_heartbeat_at, enroll_token_prefix, enroll_token_hash, enroll_token_used_at, agent_token_prefix, agent_token_hash, agent_token_revoked_at, created_by, created_at, updated_at
`

type CreateRunnerParams struct {
	Name              string
	OwnerUserID       pgtype.Int8
	Visibility        string
	EnrollTokenPrefix string
	EnrollTokenHash   string
	CreatedBy         int64
}

// ---- runners ----
func (q *Queries) CreateRunner(ctx context.Context, arg CreateRunnerParams) (Runner, error) {
	row := q.db.QueryRow(ctx, createRunner,
		arg.Name,
		arg.OwnerUserID,
		arg.Visibility,
		arg.EnrollTokenPrefix,
		arg.EnrollTokenHash,
		arg.CreatedBy,
	)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.Visibility,
		&i.Status,
		&i.Capabilities,
		&i.LastHeartbeatAt,
		&i.EnrollTokenPrefix,
		&i.EnrollTokenHash,
		&i.EnrollTokenUsedAt,
		&i.AgentTokenPrefix,
		&i.AgentTokenHash,
		&i.AgentTokenRevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO agent_sessions (
    runner_id, repo_id, issue_number, status, role, model,
    agent_image, working_branch, base_branch,
    host_addendum, env, session_token_prefix, session_token_hash,
    session_token_sealed, created_by,
    repo_sha, role_key, cause_kind, cause_id, role_config
) VALUES (
    $1,
    $2,
    $3,
    'pending',
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10::jsonb,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19::jsonb
)
RETURNING id, runner_id, repo_id, issue_number, status, role, model, agent_image, working_branch, base_branch, host_addendum, env, session_token_prefix, session_token_hash, session_token_sealed, session_token_revoked_at, exit_code, error_message, created_by, created_at, claimed_at, started_at, ended_at, repo_sha, role_key, cause_kind, cause_id, role_config
`

type CreateSessionParams struct {
	RunnerID           pgtype.Int8
	RepoID             pgtype.Int8
	IssueNumber        pgtype.Int4
	Role               string
	Model              string
	AgentImage         string
	WorkingBranch      string
	BaseBranch         string
	HostAddendum       string
	Env                []byte
	SessionTokenPrefix string
	SessionTokenHash   string
	SessionTokenSealed pgtype.Text
	CreatedBy          int64
	RepoSha            string
	RoleKey            string
	CauseKind          string
	CauseID            string
	RoleConfig         []byte
}

// ---- agent_sessions ----
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AgentSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.RunnerID,
		arg.RepoID,
		arg.IssueNumber,
		arg.Role,
		arg.Model,
		arg.AgentImage,
		arg.WorkingBranch,
		arg.BaseBranch,
		arg.HostAddendum,
		arg.Env,
		arg.SessionTokenPrefix,
		arg.SessionTokenHash,
		arg.SessionTokenSealed,
		arg.CreatedBy,
		arg.RepoSha,
		arg.RoleKey,
		arg.CauseKind,
		arg.CauseID,
		arg.RoleConfig,
	)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.RunnerID,
		&i.RepoID,
		&i.IssueNumber,
		&i.Status,
		&i.Role,
		&i.Model,
		&i.AgentImage,
		&i.WorkingBranch,
		&i.BaseBranch,
		&i.HostAddendum,
		&i.Env,
		&i.SessionTokenPrefix,
		&i.SessionTokenHash,
		&i.SessionTokenSealed,
		&i.SessionTokenRevokedAt,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.RepoSha,
		&i.RoleKey,
		&i.CauseKind,
		&i.CauseID,
		&i.RoleConfig,
	)
	return i, err
}

const deleteRunner = `-- name: DeleteRunner :execrows
DELETE FROM runners WHERE id = $1
`

// Hard-delete a runner row. agent_sessions.runner_id has ON DELETE SET
// NULL so historical session rows survive — runner_id just goes blank
// on them. Use this for "remove from list" semantics; for "stop running
// but keep the row" use DisableRunner.
func (q *Queries) DeleteRunner(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRunner, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM agent_sessions WHERE id = $1
`

// Hard-delete a session row. Cascades remove the message log + inputs
// queue (FK ON DELETE CASCADE in the migration). Use for the user-
// visible "delete agent run" affordance — once a session is failed
// and the user doesn't want it recoverable, this clears the row.
func (q *Queries) DeleteSession(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableRunner = `-- name: DisableRunner :execrows
UPDATE runners
SET status = 'disabled',
    agent_token_revoked_at = COALESCE(agent_token_revoked_at, NOW()),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DisableRunner(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, disableRunner, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueInput = `-- name: EnqueueInput :one

INSERT INTO agent_session_inputs (session_id, seq, payload)
SELECT
    $1,
    COALESCE(MAX(seq), 0) + 1,
    $2::jsonb
FROM agent_session_inputs WHERE session_id = $1
RETURNING id, session_id, seq, payload, consumed_at, created_at
`

type EnqueueInputParams struct {
	SessionID int64
	Payload   []byte
}

// ---- inputs queue ----
func (q *Queries) EnqueueInput(ctx context.Context, arg EnqueueInputParams) (AgentSessionInput, error) {
	row := q.db.QueryRow(ctx, enqueueInput, arg.SessionID, arg.Payload)
	var i AgentSessionInput
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Seq,
		&i.Payload,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRunnerByAgentPrefix = `-- name: GetRunnerByAgentPrefix :one
SELECT id, name, owner_user_id, visibility, status, capabilities, last_heartbeat_at, enroll_token_prefix, enroll_token_hash, enroll_token_used_at, agent_token_prefix, agent_token_hash, agent_token_revoked_at, created_by, created_at, updated_at FROM runners WHERE agent_token_prefix = $1
`

func (q *Queries) GetRunnerByAgentPrefix(ctx context.Context, agentTokenPrefix pgtype.Text) (Runner, error) {
	row := q.db.QueryRow(ctx, getRunnerByAgentPrefix, agentTokenPrefix)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.Visibility,
		&i.Status,
		&i.Capabilities,
		&i.LastHeartbeatAt,
		&i.EnrollTokenPrefix,
		&i.EnrollTokenHash,
		&i.EnrollTokenUsedAt,
		&i.AgentTokenPrefix,
		&i.AgentTokenHash,
		&i.AgentTokenRevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunnerByEnrollPrefixForUpdate = `-- name: GetRunnerByEnrollPrefixForUpdate :one
SELECT id, name, owner_user_id, visibility, status, capabilities, last_heartbeat_at, enroll_token_prefix, enroll_token_hash, enroll_token_used_at, agent_token_prefix, agent_token_hash, agent_token_revoked_at, created_by, created_at, updated_at FROM runners
WHERE enroll_token_prefix = $1
FOR UPDATE
`

// Used in the enrollment-redemption transaction. FOR UPDATE pins the row
// so a concurrent redemption serialises behind us and loses cleanly.
func (q *Queries) GetRunnerByEnrollPrefixForUpdate(ctx context.Context, enrollTokenPrefix string) (Runner, error) {
	row := q.db.QueryRow(ctx, getRunnerByEnrollPrefixForUpdate, enrollTokenPrefix)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.Visibility,
		&i.Status,
		&i.Capabilities,
		&i.LastHeartbeatAt,
		&i.EnrollTokenPrefix,
		&i.EnrollTokenHash,
		&i.EnrollTokenUsedAt,
		&i.AgentTokenPrefix,
		&i.AgentTokenHash,
		&i.AgentTokenRevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunnerByID = `-- name: GetRunnerByID :one
SELECT id, name, owner_user_id, visibility, status, capabilities, last_heartbeat_at, enroll_token_prefix, enroll_token_hash, enroll_token_used_at, agent_token_prefix, agent_token_hash, agent_token_revoked_at, created_by, created_at, updated_at FROM runners WHERE id = $1
`

func (q *Queries) GetRunnerByID(ctx context.Context, id int64) (Runner, error) {
	row := q.db.QueryRow(ctx, getRunnerByID, id)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.Visibility,
		&i.Status,
		&i.Capabilities,
		&i.LastHeartbeatAt,
		&i.EnrollTokenPrefix,
		&i.EnrollTokenHash,
		&i.EnrollTokenUsedAt,
		&i.AgentTokenPrefix,
		&i.AgentTokenHash,
		&i.AgentTokenRevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, runner_id, repo_id, issue_number, status, role, model, agent_image, working_branch, base_branch, host_addendum, env, session_token_prefix, session_token_hash, session_token_sealed, session_token_revoked_at, exit_code, error_message, created_by, created_at, claimed_at, started_at, ended_at, repo_sha, role_key, cause_kind, cause_id, role_config FROM agent_sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id int64) (AgentSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.RunnerID,
		&i.RepoID,
		&i.IssueNumber,
		&i.Status,
		&i.Role,
		&i.Model,
		&i.AgentImage,
		&i.WorkingBranch,
		&i.BaseBranch,
		&i.HostAddendum,
		&i.Env,
		&i.SessionTokenPrefix,
		&i.SessionTokenHash,
		&i.SessionTokenSealed,
		&i.SessionTokenRevokedAt,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.RepoSha,
		&i.RoleKey,
		&i.CauseKind,
		&i.CauseID,
		&i.RoleConfig,
	)
	return i, err
}

const getSessionByTokenPrefix = `-- name: GetSessionByTokenPrefix :one
SELECT id, runner_id, repo_id, issue_number, status, role, model, agent_image, working_branch, base_branch, host_addendum, env, session_token_prefix, session_token_hash, session_token_sealed, session_token_revoked_at, exit_code, error_message, created_by, created_at, claimed_at, started_at, ended_at, repo_sha, role_key, cause_kind, cause_id, role_config FROM agent_sessions WHERE session_token_prefix = $1
`

func (q *Queries) GetSessionByTokenPrefix(ctx context.Context, sessionTokenPrefix string) (AgentSession, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenPrefix, sessionTokenPrefix)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.RunnerID,
		&i.RepoID,
		&i.IssueNumber,
		&i.Status,
		&i.Role,
		&i.Model,
		&i.AgentImage,
		&i.WorkingBranch,
		&i.BaseBranch,
		&i.HostAddendum,
		&i.Env,
		&i.SessionTokenPrefix,
		&i.SessionTokenHash,
		&i.SessionTokenSealed,
		&i.SessionTokenRevokedAt,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.RepoSha,
		&i.RoleKey,
		&i.CauseKind,
		&i.CauseID,
		&i.RoleConfig,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, session_id, seq, kind, role, content, event_name, tool_call_id, tool_name, payload, created_at FROM agent_session_messages
WHERE session_id = $1
ORDER BY seq ASC
`

func (q *Queries) ListMessages(ctx context.Context, sessionID int64) ([]AgentSessionMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSessionMessage{}
	for rows.Next() {
		var i AgentSessionMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.Kind,
			&i.Role,
			&i.Content,
			&i.EventName,
			&i.ToolCallID,
			&i.ToolName,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSessions = `-- name: ListRecentSessions :many
SELECT id, runner_id, repo_id, issue_number, status, role, model, agent_image, working_branch, base_branch, host_addendum, env, session_token_prefix, session_token_hash, session_token_sealed, session_token_revoked_at, exit_code, error_message, created_by, created_at, claimed_at, started_at, ended_at, repo_sha, role_key, cause_kind, cause_id, role_config FROM agent_sessions
WHERE ($1::TEXT   IS NULL OR role_key   = $1::TEXT)
  AND ($2::TEXT     IS NULL OR status     = $2::TEXT)
  AND ($3::BIGINT  IS NULL OR repo_id    = $3::BIGINT)
  AND ($4::TIMESTAMPTZ IS NULL OR created_at >= $4::TIMESTAMPTZ)
ORDER BY id DESC
LIMIT $5
`

type ListRecentSessionsParams struct {
	RoleKey pgtype.Text
	Status  pgtype.Text
	RepoID  pgtype.Int8
	Since   pgtype.Timestamptz
	Lim     int32
}

// Returns the most-recent agent_sessions across the whole platform with
// optional filters. Powers the admin "global agent sessions" audit view
// under /api/admin/agent-sessions. Every filter is independent and
// nullable; the caller composes whichever set of constraints applies.
func (q *Queries) ListRecentSessions(ctx context.Context, arg ListRecentSessionsParams) ([]AgentSession, error) {
	rows, err := q.db.Query(ctx, listRecentSessions,
		arg.RoleKey,
		arg.Status,
		arg.RepoID,
		arg.Since,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSession{}
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.RunnerID,
			&i.RepoID,
			&i.IssueNumber,
			&i.Status,
			&i.Role,
			&i.Model,
			&i.AgentImage,
			&i.WorkingBranch,
			&i.BaseBranch,
			&i.HostAddendum,
			&i.Env,
			&i.SessionTokenPrefix,
			&i.SessionTokenHash,
			&i.SessionTokenSealed,
			&i.SessionTokenRevokedAt,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.RepoSha,
			&i.RoleKey,
			&i.CauseKind,
			&i.CauseID,
			&i.RoleConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunners = `-- name: ListRunners :many
SELECT id, name, owner_user_id, visibility, status, capabilities, last_heartbeat_at, enroll_token_prefix, enroll_token_hash, enroll_token_used_at, agent_token_prefix, agent_token_hash, agent_token_revoked_at, created_by, created_at, updated_at FROM runners
WHERE ($1::BIGINT IS NULL OR owner_user_id = $1)
  AND ($2::TEXT  IS NULL OR visibility    = $2)
ORDER BY id DESC
`

type ListRunnersParams struct {
	OwnerUserID pgtype.Int8
	Visibility  pgtype.Text
}

func (q *Queries) ListRunners(ctx context.Context, arg ListRunnersParams) ([]Runner, error) {
	rows, err := q.db.Query(ctx, listRunners, arg.OwnerUserID, arg.Visibility)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Runner{}
	for rows.Next() {
		var i Runner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerUserID,
			&i.Visibility,
			&i.Status,
			&i.Capabilities,
			&i.LastHeartbeatAt,
			&i.EnrollTokenPrefix,
			&i.EnrollTokenHash,
			&i.EnrollTokenUsedAt,
			&i.AgentTokenPrefix,
			&i.AgentTokenHash,
			&i.AgentTokenRevokedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, runner_id, repo_id, issue_number, status, role, model, agent_image, working_branch, base_branch, host_addendum, env, session_token_prefix, session_token_hash, session_token_sealed, session_token_revoked_at, exit_code, error_message, created_by, created_at, claimed_at, started_at, ended_at, repo_sha, role_key, cause_kind, cause_id, role_config FROM agent_sessions
WHERE ($1::BIGINT IS NULL OR runner_id = $1)
  AND ($2::TEXT   IS NULL OR status    = $2)
ORDER BY id DESC
LIMIT $3
`

type ListSessionsParams struct {
	RunnerID pgtype.Int8
	Status   pgtype.Text
	Lim      int32
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]AgentSession, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.RunnerID, arg.Status, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSession{}
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.RunnerID,
			&i.RepoID,
			&i.IssueNumber,
			&i.Status,
			&i.Role,
			&i.Model,
			&i.AgentImage,
			&i.WorkingBranch,
			&i.BaseBranch,
			&i.HostAddendum,
			&i.Env,
			&i.SessionTokenPrefix,
			&i.SessionTokenHash,
			&i.SessionTokenSealed,
			&i.SessionTokenRevokedAt,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.RepoSha,
			&i.RoleKey,
			&i.CauseKind,
			&i.CauseID,
			&i.RoleConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByIssue = `-- name: ListSessionsByIssue :many
SELECT id, runner_id, repo_id, issue_number, status, role, model, agent_image, working_branch, base_branch, host_addendum, env, session_token_prefix, session_token_hash, session_token_sealed, session_token_revoked_at, exit_code, error_message, created_by, created_at, claimed_at, started_at, ended_at, repo_sha, role_key, cause_kind, cause_id, role_config FROM agent_sessions
WHERE repo_id      = $1
  AND issue_number = $2
ORDER BY id ASC
`

type ListSessionsByIssueParams struct {
	RepoID      pgtype.Int8
	IssueNumber pgtype.Int4
}

// Returns every agent_session row for the (repo, issue) tuple in spawn
// order. Powers the audit query view: a caller hands an issue, gets
// back the entire role roster (with snapshot pins) that has touched it.
func (q *Queries) ListSessionsByIssue(ctx context.Context, arg ListSessionsByIssueParams) ([]AgentSession, error) {
	rows, err := q.db.Query(ctx, listSessionsByIssue, arg.RepoID, arg.IssueNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSession{}
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.RunnerID,
			&i.RepoID,
			&i.IssueNumber,
			&i.Status,
			&i.Role,
			&i.Model,
			&i.AgentImage,
			&i.WorkingBranch,
			&i.BaseBranch,
			&i.HostAddendum,
			&i.Env,
			&i.SessionTokenPrefix,
			&i.SessionTokenHash,
			&i.SessionTokenSealed,
			&i.SessionTokenRevokedAt,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.RepoSha,
			&i.RoleKey,
			&i.CauseKind,
			&i.CauseID,
			&i.RoleConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInputsConsumed = `-- name: MarkInputsConsumed :exec
UPDATE agent_session_inputs SET consumed_at = NOW() WHERE id = ANY($1::BIGINT[])
`

func (q *Queries) MarkInputsConsumed(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markInputsConsumed, ids)
	return err
}

const markSessionIdle = `-- name: MarkSessionIdle :execrows
UPDATE agent_sessions
SET status    = 'idle',
    exit_code = $1
WHERE id = $2
  AND status IN ('claimed', 'running')
`

type MarkSessionIdleParams struct {
	ExitCode pgtype.Int4
	ID       int64
}

// Flip a running session to idle: one turn finished but the parent issue
// is still live, so the row should stay reusable for the next trigger.
// Unlike MarkSessionTerminal this DOES NOT NULL session_token_sealed —
// the runner re-uses the same session identity when the row is rewoken,
// so the sealed plaintext must survive across container exits. ended_at
// is intentionally left NULL because the session as a logical unit
// isn't done; only the most recent container is.
func (q *Queries) MarkSessionIdle(ctx context.Context, arg MarkSessionIdleParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionIdle, arg.ExitCode, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSessionRunning = `-- name: MarkSessionRunning :execrows
UPDATE agent_sessions
SET status = 'running', started_at = COALESCE(started_at, NOW())
WHERE id = $1 AND status IN ('claimed', 'running')
`

func (q *Queries) MarkSessionRunning(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionRunning, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSessionTerminal = `-- name: MarkSessionTerminal :execrows
UPDATE agent_sessions
SET status               = $1,
    ended_at             = NOW(),
    exit_code            = $2,
    error_message        = $3,
    session_token_sealed = NULL
WHERE id = $4
  AND status NOT IN ('succeeded', 'failed', 'cancelled', 'archived')
`

type MarkSessionTerminalParams struct {
	Status       string
	ExitCode     pgtype.Int4
	ErrorMessage string
	ID           int64
}

// session_token_sealed is NULL'd at terminate time so a leaked DB
// snapshot of a dead session no longer carries the bearer plaintext.
//
// The NOT IN guard MUST list every terminal state — otherwise a late
// runner terminate (e.g. container exited just as issue.closed fired)
// could overwrite an `archived` row with `succeeded` and lose the
// "session ended because the issue closed" signal in the audit chain.
// `archived` was added in migration 00002; we updated this guard at
// the same time the agent_session module landed.
func (q *Queries) MarkSessionTerminal(ctx context.Context, arg MarkSessionTerminalParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionTerminal,
		arg.Status,
		arg.ExitCode,
		arg.ErrorMessage,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const redeemEnrollmentUpdate = `-- name: RedeemEnrollmentUpdate :exec
UPDATE runners
SET status                 = 'active',
    enroll_token_used_at   = NOW(),
    agent_token_prefix     = $1,
    agent_token_hash       = $2,
    agent_token_revoked_at = NULL,
    capabilities           = $3::jsonb,
    last_heartbeat_at      = NOW(),
    updated_at             = NOW()
WHERE id = $4
`

type RedeemEnrollmentUpdateParams struct {
	AgentTokenPrefix pgtype.Text
	AgentTokenHash   pgtype.Text
	Capabilities     []byte
	ID               int64
}

// Second half of the redemption transaction: flip the row to active,
// mark used_at, persist the fresh agent token hash + prefix.
func (q *Queries) RedeemEnrollmentUpdate(ctx context.Context, arg RedeemEnrollmentUpdateParams) error {
	_, err := q.db.Exec(ctx, redeemEnrollmentUpdate,
		arg.AgentTokenPrefix,
		arg.AgentTokenHash,
		arg.Capabilities,
		arg.ID,
	)
	return err
}

const resumeSession = `-- name: ResumeSession :execrows
UPDATE agent_sessions
SET status               = 'pending',
    session_token_prefix = $1,
    session_token_hash   = $2,
    session_token_sealed = $3,
    runner_id            = NULL,
    claimed_at           = NULL,
    started_at           = NULL,
    ended_at             = NULL,
    exit_code            = NULL,
    error_message        = ''
WHERE id = $4
  AND status IN ('idle', 'failed', 'succeeded', 'cancelled')
`

type ResumeSessionParams struct {
	SessionTokenPrefix string
	SessionTokenHash   string
	SessionTokenSealed pgtype.Text
	ID                 int64
}

// User-initiated resume: flip an idle / failed / succeeded row back to
// 'pending' so the next runner poll picks it up. Re-mints the session
// token (the previous sealed plaintext was NULL'd on terminate for
// failed/succeeded). For idle rows the sealed token survives so we
// pass through the existing value via the caller's sealed arg.
//
// archived rows are not resumable — the parent issue archived them and
// a new issue is required to start fresh. cancelled is treated as
// failed for legacy data.
func (q *Queries) ResumeSession(ctx context.Context, arg ResumeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, resumeSession,
		arg.SessionTokenPrefix,
		arg.SessionTokenHash,
		arg.SessionTokenSealed,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRunnerHeartbeat = `-- name: UpdateRunnerHeartbeat :execrows
UPDATE runners
SET last_heartbeat_at = NOW(),
    capabilities = $1::jsonb,
    updated_at = NOW()
WHERE id = $2
`

type UpdateRunnerHeartbeatParams struct {
	Capabilities []byte
	ID           int64
}

func (q *Queries) UpdateRunnerHeartbeat(ctx context.Context, arg UpdateRunnerHeartbeatParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRunnerHeartbeat, arg.Capabilities, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
