// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repodb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BranchProtection struct {
	ID               int64
	RepoID           int64
	Pattern          string
	ForbidForcePush  bool
	ForbidDelete     bool
	ForbidDirectPush bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Organization struct {
	ID          int64
	Name        string
	DisplayName string
	Description string
	AvatarUrl   string
	CreatedBy   int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type OrganizationMember struct {
	OrgID   int64
	UserID  int64
	Role    string
	AddedBy int64
	AddedAt pgtype.Timestamptz
}

type Repo struct {
	ID            int64
	OwnerUserID   pgtype.Int8
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerOrgID    pgtype.Int8
}

type RepoMember struct {
	RepoID  int64
	UserID  int64
	Role    string
	AddedBy int64
	AddedAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
