// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repodb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repo struct {
	ID            int64
	OwnerID       int64
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
