// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRepoMember = `-- name: AddRepoMember :exec
INSERT INTO repo_members (repo_id, user_id, role, actor_id)
VALUES ($1, $2, $3, $4)
`

type AddRepoMemberParams struct {
	RepoID  int64
	UserID  int64
	Role    string
	ActorID int64
}

func (q *Queries) AddRepoMember(ctx context.Context, arg AddRepoMemberParams) error {
	_, err := q.db.Exec(ctx, addRepoMember,
		arg.RepoID,
		arg.UserID,
		arg.Role,
		arg.ActorID,
	)
	return err
}

const countReposByOrgOwner = `-- name: CountReposByOrgOwner :one
SELECT COUNT(*)
FROM repos r
JOIN organizations o ON o.id = r.owner_org_id
WHERE r.owner_org_id = $1
  AND o.deleted_at IS NULL
  AND ($2::bool OR r.visibility = 'public')
`

type CountReposByOrgOwnerParams struct {
	OwnerOrgID     pgtype.Int8
	IncludePrivate bool
}

func (q *Queries) CountReposByOrgOwner(ctx context.Context, arg CountReposByOrgOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReposByOrgOwner, arg.OwnerOrgID, arg.IncludePrivate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReposByUserOwner = `-- name: CountReposByUserOwner :one
SELECT COUNT(*)
FROM repos r
WHERE r.owner_user_id = $1
  AND ($2::bool OR r.visibility = 'public')
`

type CountReposByUserOwnerParams struct {
	OwnerUserID    pgtype.Int8
	IncludePrivate bool
}

func (q *Queries) CountReposByUserOwner(ctx context.Context, arg CountReposByUserOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReposByUserOwner, arg.OwnerUserID, arg.IncludePrivate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranchProtection = `-- name: CreateBranchProtection :one
INSERT INTO branch_protections (repo_id, pattern, forbid_force_push, forbid_delete, forbid_direct_push)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, repo_id, pattern, forbid_force_push, forbid_delete, forbid_direct_push, created_at, updated_at
`

type CreateBranchProtectionParams struct {
	RepoID           int64
	Pattern          string
	ForbidForcePush  bool
	ForbidDelete     bool
	ForbidDirectPush bool
}

func (q *Queries) CreateBranchProtection(ctx context.Context, arg CreateBranchProtectionParams) (BranchProtection, error) {
	row := q.db.QueryRow(ctx, createBranchProtection,
		arg.RepoID,
		arg.Pattern,
		arg.ForbidForcePush,
		arg.ForbidDelete,
		arg.ForbidDirectPush,
	)
	var i BranchProtection
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Pattern,
		&i.ForbidForcePush,
		&i.ForbidDelete,
		&i.ForbidDirectPush,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRepoForOrg = `-- name: CreateRepoForOrg :one
INSERT INTO repos (owner_org_id, name, description, visibility, default_branch)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_user_id, name, description, visibility, default_branch, created_at, updated_at, owner_org_id
`

type CreateRepoForOrgParams struct {
	OwnerOrgID    pgtype.Int8
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
}

func (q *Queries) CreateRepoForOrg(ctx context.Context, arg CreateRepoForOrgParams) (Repo, error) {
	row := q.db.QueryRow(ctx, createRepoForOrg,
		arg.OwnerOrgID,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.DefaultBranch,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerOrgID,
	)
	return i, err
}

const createRepoForUser = `-- name: CreateRepoForUser :one
INSERT INTO repos (owner_user_id, name, description, visibility, default_branch)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_user_id, name, description, visibility, default_branch, created_at, updated_at, owner_org_id
`

type CreateRepoForUserParams struct {
	OwnerUserID   pgtype.Int8
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
}

func (q *Queries) CreateRepoForUser(ctx context.Context, arg CreateRepoForUserParams) (Repo, error) {
	row := q.db.QueryRow(ctx, createRepoForUser,
		arg.OwnerUserID,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.DefaultBranch,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerOrgID,
	)
	return i, err
}

const createRepoVariable = `-- name: CreateRepoVariable :one
INSERT INTO repo_variables (repo_id, name, value, kind)
VALUES ($1, $2, $3, $4)
RETURNING id, repo_id, name, value, kind, created_at, updated_at
`

type CreateRepoVariableParams struct {
	RepoID int64
	Name   string
	Value  string
	Kind   string
}

func (q *Queries) CreateRepoVariable(ctx context.Context, arg CreateRepoVariableParams) (RepoVariable, error) {
	row := q.db.QueryRow(ctx, createRepoVariable,
		arg.RepoID,
		arg.Name,
		arg.Value,
		arg.Kind,
	)
	var i RepoVariable
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Name,
		&i.Value,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBranchProtection = `-- name: DeleteBranchProtection :execrows
DELETE FROM branch_protections WHERE id = $1 AND repo_id = $2
`

type DeleteBranchProtectionParams struct {
	ID     int64
	RepoID int64
}

func (q *Queries) DeleteBranchProtection(ctx context.Context, arg DeleteBranchProtectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBranchProtection, arg.ID, arg.RepoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRepo = `-- name: DeleteRepo :execrows
DELETE FROM repos WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRepo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRepoVariable = `-- name: DeleteRepoVariable :execrows
DELETE FROM repo_variables
WHERE id = $1 AND repo_id = $2
`

type DeleteRepoVariableParams struct {
	ID     int64
	RepoID int64
}

func (q *Queries) DeleteRepoVariable(ctx context.Context, arg DeleteRepoVariableParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRepoVariable, arg.ID, arg.RepoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBranchProtection = `-- name: GetBranchProtection :one
SELECT id, repo_id, pattern, forbid_force_push, forbid_delete, forbid_direct_push, created_at, updated_at
FROM branch_protections
WHERE id = $1 AND repo_id = $2
`

type GetBranchProtectionParams struct {
	ID     int64
	RepoID int64
}

func (q *Queries) GetBranchProtection(ctx context.Context, arg GetBranchProtectionParams) (BranchProtection, error) {
	row := q.db.QueryRow(ctx, getBranchProtection, arg.ID, arg.RepoID)
	var i BranchProtection
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Pattern,
		&i.ForbidForcePush,
		&i.ForbidDelete,
		&i.ForbidDirectPush,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT r.id, r.owner_user_id, r.name, r.description, r.visibility, r.default_branch, r.created_at, r.updated_at, r.owner_org_id,
       COALESCE(u.username, o.name) AS owner_name,
       CASE
           WHEN r.owner_user_id IS NOT NULL THEN 'user'
           ELSE 'org'
       END AS owner_kind
FROM repos r
LEFT JOIN users u         ON u.id = r.owner_user_id
LEFT JOIN organizations o ON o.id = r.owner_org_id AND o.deleted_at IS NULL
WHERE r.id = $1
`

type GetRepoByIDRow struct {
	ID            int64
	OwnerUserID   pgtype.Int8
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerOrgID    pgtype.Int8
	OwnerName     string
	OwnerKind     string
}

func (q *Queries) GetRepoByID(ctx context.Context, id int64) (GetRepoByIDRow, error) {
	row := q.db.QueryRow(ctx, getRepoByID, id)
	var i GetRepoByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerOrgID,
		&i.OwnerName,
		&i.OwnerKind,
	)
	return i, err
}

const getRepoByOrgOwnerAndName = `-- name: GetRepoByOrgOwnerAndName :one
SELECT r.id, r.owner_user_id, r.name, r.description, r.visibility, r.default_branch, r.created_at, r.updated_at, r.owner_org_id,
       o.name AS owner_name,
       'org'::text AS owner_kind
FROM repos r
JOIN organizations o ON o.id = r.owner_org_id
WHERE r.owner_org_id = $1 AND r.name = $2 AND o.deleted_at IS NULL
`

type GetRepoByOrgOwnerAndNameParams struct {
	OwnerOrgID pgtype.Int8
	Name       string
}

type GetRepoByOrgOwnerAndNameRow struct {
	ID            int64
	OwnerUserID   pgtype.Int8
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerOrgID    pgtype.Int8
	OwnerName     string
	OwnerKind     string
}

func (q *Queries) GetRepoByOrgOwnerAndName(ctx context.Context, arg GetRepoByOrgOwnerAndNameParams) (GetRepoByOrgOwnerAndNameRow, error) {
	row := q.db.QueryRow(ctx, getRepoByOrgOwnerAndName, arg.OwnerOrgID, arg.Name)
	var i GetRepoByOrgOwnerAndNameRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerOrgID,
		&i.OwnerName,
		&i.OwnerKind,
	)
	return i, err
}

const getRepoByUserOwnerAndName = `-- name: GetRepoByUserOwnerAndName :one
SELECT r.id, r.owner_user_id, r.name, r.description, r.visibility, r.default_branch, r.created_at, r.updated_at, r.owner_org_id,
       u.username AS owner_name,
       'user'::text AS owner_kind
FROM repos r
JOIN users u ON u.id = r.owner_user_id
WHERE r.owner_user_id = $1 AND r.name = $2
`

type GetRepoByUserOwnerAndNameParams struct {
	OwnerUserID pgtype.Int8
	Name        string
}

type GetRepoByUserOwnerAndNameRow struct {
	ID            int64
	OwnerUserID   pgtype.Int8
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerOrgID    pgtype.Int8
	OwnerName     string
	OwnerKind     string
}

func (q *Queries) GetRepoByUserOwnerAndName(ctx context.Context, arg GetRepoByUserOwnerAndNameParams) (GetRepoByUserOwnerAndNameRow, error) {
	row := q.db.QueryRow(ctx, getRepoByUserOwnerAndName, arg.OwnerUserID, arg.Name)
	var i GetRepoByUserOwnerAndNameRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerOrgID,
		&i.OwnerName,
		&i.OwnerKind,
	)
	return i, err
}

const getRepoMember = `-- name: GetRepoMember :one
SELECT m.repo_id, m.user_id, u.username, m.role, m.actor_id, m.added_at
FROM repo_members m
JOIN users u ON u.id = m.user_id
WHERE m.repo_id = $1 AND m.user_id = $2
`

type GetRepoMemberParams struct {
	RepoID int64
	UserID int64
}

type GetRepoMemberRow struct {
	RepoID   int64
	UserID   int64
	Username string
	Role     string
	ActorID  int64
	AddedAt  pgtype.Timestamptz
}

func (q *Queries) GetRepoMember(ctx context.Context, arg GetRepoMemberParams) (GetRepoMemberRow, error) {
	row := q.db.QueryRow(ctx, getRepoMember, arg.RepoID, arg.UserID)
	var i GetRepoMemberRow
	err := row.Scan(
		&i.RepoID,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.ActorID,
		&i.AddedAt,
	)
	return i, err
}

const getRepoVariable = `-- name: GetRepoVariable :one
SELECT id, repo_id, name, value, kind, created_at, updated_at
FROM repo_variables
WHERE id = $1 AND repo_id = $2
`

type GetRepoVariableParams struct {
	ID     int64
	RepoID int64
}

func (q *Queries) GetRepoVariable(ctx context.Context, arg GetRepoVariableParams) (RepoVariable, error) {
	row := q.db.QueryRow(ctx, getRepoVariable, arg.ID, arg.RepoID)
	var i RepoVariable
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Name,
		&i.Value,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoVariableByName = `-- name: GetRepoVariableByName :one
SELECT id, repo_id, name, value, kind, created_at, updated_at
FROM repo_variables
WHERE repo_id = $1 AND name = $2
`

type GetRepoVariableByNameParams struct {
	RepoID int64
	Name   string
}

func (q *Queries) GetRepoVariableByName(ctx context.Context, arg GetRepoVariableByNameParams) (RepoVariable, error) {
	row := q.db.QueryRow(ctx, getRepoVariableByName, arg.RepoID, arg.Name)
	var i RepoVariable
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Name,
		&i.Value,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranchProtectionsByRepo = `-- name: ListBranchProtectionsByRepo :many
SELECT id, repo_id, pattern, forbid_force_push, forbid_delete, forbid_direct_push, created_at, updated_at
FROM branch_protections
WHERE repo_id = $1
ORDER BY pattern
`

func (q *Queries) ListBranchProtectionsByRepo(ctx context.Context, repoID int64) ([]BranchProtection, error) {
	rows, err := q.db.Query(ctx, listBranchProtectionsByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchProtection{}
	for rows.Next() {
		var i BranchProtection
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Pattern,
			&i.ForbidForcePush,
			&i.ForbidDelete,
			&i.ForbidDirectPush,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoMembers = `-- name: ListRepoMembers :many
SELECT m.repo_id, m.user_id, u.username, m.role, m.actor_id, m.added_at
FROM repo_members m
JOIN users u ON u.id = m.user_id
WHERE m.repo_id = $1
ORDER BY m.role DESC, u.username ASC
`

type ListRepoMembersRow struct {
	RepoID   int64
	UserID   int64
	Username string
	Role     string
	ActorID  int64
	AddedAt  pgtype.Timestamptz
}

func (q *Queries) ListRepoMembers(ctx context.Context, repoID int64) ([]ListRepoMembersRow, error) {
	rows, err := q.db.Query(ctx, listRepoMembers, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepoMembersRow{}
	for rows.Next() {
		var i ListRepoMembersRow
		if err := rows.Scan(
			&i.RepoID,
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.ActorID,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoVariables = `-- name: ListRepoVariables :many
SELECT id, repo_id, name, value, kind, created_at, updated_at
FROM repo_variables
WHERE repo_id = $1
ORDER BY name
`

func (q *Queries) ListRepoVariables(ctx context.Context, repoID int64) ([]RepoVariable, error) {
	rows, err := q.db.Query(ctx, listRepoVariables, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepoVariable{}
	for rows.Next() {
		var i RepoVariable
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Name,
			&i.Value,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByOrgOwner = `-- name: ListReposByOrgOwner :many
SELECT r.id, r.owner_user_id, r.name, r.description, r.visibility, r.default_branch, r.created_at, r.updated_at, r.owner_org_id,
       o.name AS owner_name,
       'org'::text AS owner_kind
FROM repos r
JOIN organizations o ON o.id = r.owner_org_id
WHERE r.owner_org_id = $1
  AND o.deleted_at IS NULL
  AND ($4::bool OR r.visibility = 'public')
ORDER BY r.created_at DESC, r.id DESC
LIMIT $2 OFFSET $3
`

type ListReposByOrgOwnerParams struct {
	OwnerOrgID     pgtype.Int8
	Limit          int32
	Offset         int32
	IncludePrivate bool
}

type ListReposByOrgOwnerRow struct {
	ID            int64
	OwnerUserID   pgtype.Int8
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerOrgID    pgtype.Int8
	OwnerName     string
	OwnerKind     string
}

func (q *Queries) ListReposByOrgOwner(ctx context.Context, arg ListReposByOrgOwnerParams) ([]ListReposByOrgOwnerRow, error) {
	rows, err := q.db.Query(ctx, listReposByOrgOwner,
		arg.OwnerOrgID,
		arg.Limit,
		arg.Offset,
		arg.IncludePrivate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReposByOrgOwnerRow{}
	for rows.Next() {
		var i ListReposByOrgOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.DefaultBranch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerOrgID,
			&i.OwnerName,
			&i.OwnerKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByUserOwner = `-- name: ListReposByUserOwner :many
SELECT r.id, r.owner_user_id, r.name, r.description, r.visibility, r.default_branch, r.created_at, r.updated_at, r.owner_org_id,
       u.username AS owner_name,
       'user'::text AS owner_kind
FROM repos r
JOIN users u ON u.id = r.owner_user_id
WHERE r.owner_user_id = $1
  AND ($4::bool OR r.visibility = 'public')
ORDER BY r.created_at DESC, r.id DESC
LIMIT $2 OFFSET $3
`

type ListReposByUserOwnerParams struct {
	OwnerUserID    pgtype.Int8
	Limit          int32
	Offset         int32
	IncludePrivate bool
}

type ListReposByUserOwnerRow struct {
	ID            int64
	OwnerUserID   pgtype.Int8
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerOrgID    pgtype.Int8
	OwnerName     string
	OwnerKind     string
}

func (q *Queries) ListReposByUserOwner(ctx context.Context, arg ListReposByUserOwnerParams) ([]ListReposByUserOwnerRow, error) {
	rows, err := q.db.Query(ctx, listReposByUserOwner,
		arg.OwnerUserID,
		arg.Limit,
		arg.Offset,
		arg.IncludePrivate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReposByUserOwnerRow{}
	for rows.Next() {
		var i ListReposByUserOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.DefaultBranch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerOrgID,
			&i.OwnerName,
			&i.OwnerKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRepoMember = `-- name: RemoveRepoMember :execrows
DELETE FROM repo_members
WHERE repo_id = $1 AND user_id = $2
`

type RemoveRepoMemberParams struct {
	RepoID int64
	UserID int64
}

func (q *Queries) RemoveRepoMember(ctx context.Context, arg RemoveRepoMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeRepoMember, arg.RepoID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transferRepoToOrg = `-- name: TransferRepoToOrg :execrows
UPDATE repos
SET owner_user_id = NULL,
    owner_org_id  = $2,
    updated_at    = NOW()
WHERE id = $1
`

type TransferRepoToOrgParams struct {
	ID         int64
	OwnerOrgID pgtype.Int8
}

func (q *Queries) TransferRepoToOrg(ctx context.Context, arg TransferRepoToOrgParams) (int64, error) {
	result, err := q.db.Exec(ctx, transferRepoToOrg, arg.ID, arg.OwnerOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transferRepoToUser = `-- name: TransferRepoToUser :execrows
UPDATE repos
SET owner_user_id = $2,
    owner_org_id  = NULL,
    updated_at    = NOW()
WHERE id = $1
`

type TransferRepoToUserParams struct {
	ID          int64
	OwnerUserID pgtype.Int8
}

func (q *Queries) TransferRepoToUser(ctx context.Context, arg TransferRepoToUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, transferRepoToUser, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBranchProtection = `-- name: UpdateBranchProtection :one
UPDATE branch_protections
SET pattern             = $3,
    forbid_force_push   = $4,
    forbid_delete       = $5,
    forbid_direct_push  = $6,
    updated_at          = NOW()
WHERE id = $1 AND repo_id = $2
RETURNING id, repo_id, pattern, forbid_force_push, forbid_delete, forbid_direct_push, created_at, updated_at
`

type UpdateBranchProtectionParams struct {
	ID               int64
	RepoID           int64
	Pattern          string
	ForbidForcePush  bool
	ForbidDelete     bool
	ForbidDirectPush bool
}

func (q *Queries) UpdateBranchProtection(ctx context.Context, arg UpdateBranchProtectionParams) (BranchProtection, error) {
	row := q.db.QueryRow(ctx, updateBranchProtection,
		arg.ID,
		arg.RepoID,
		arg.Pattern,
		arg.ForbidForcePush,
		arg.ForbidDelete,
		arg.ForbidDirectPush,
	)
	var i BranchProtection
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Pattern,
		&i.ForbidForcePush,
		&i.ForbidDelete,
		&i.ForbidDirectPush,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepoMemberRole = `-- name: UpdateRepoMemberRole :execrows
UPDATE repo_members
SET role = $3
WHERE repo_id = $1 AND user_id = $2
`

type UpdateRepoMemberRoleParams struct {
	RepoID int64
	UserID int64
	Role   string
}

func (q *Queries) UpdateRepoMemberRole(ctx context.Context, arg UpdateRepoMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRepoMemberRole, arg.RepoID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRepoMeta = `-- name: UpdateRepoMeta :one
UPDATE repos
SET description    = $2,
    default_branch = $3,
    visibility     = $4,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, owner_user_id, name, description, visibility, default_branch, created_at, updated_at, owner_org_id
`

type UpdateRepoMetaParams struct {
	ID            int64
	Description   string
	DefaultBranch string
	Visibility    string
}

func (q *Queries) UpdateRepoMeta(ctx context.Context, arg UpdateRepoMetaParams) (Repo, error) {
	row := q.db.QueryRow(ctx, updateRepoMeta,
		arg.ID,
		arg.Description,
		arg.DefaultBranch,
		arg.Visibility,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerOrgID,
	)
	return i, err
}

const updateRepoVariable = `-- name: UpdateRepoVariable :one
UPDATE repo_variables
SET name       = $3,
    value      = $4,
    kind       = $5,
    updated_at = NOW()
WHERE id = $1 AND repo_id = $2
RETURNING id, repo_id, name, value, kind, created_at, updated_at
`

type UpdateRepoVariableParams struct {
	ID     int64
	RepoID int64
	Name   string
	Value  string
	Kind   string
}

func (q *Queries) UpdateRepoVariable(ctx context.Context, arg UpdateRepoVariableParams) (RepoVariable, error) {
	row := q.db.QueryRow(ctx, updateRepoVariable,
		arg.ID,
		arg.RepoID,
		arg.Name,
		arg.Value,
		arg.Kind,
	)
	var i RepoVariable
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Name,
		&i.Value,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
