// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReposByOwner = `-- name: CountReposByOwner :one
SELECT COUNT(*)
FROM repos r
WHERE r.owner_id = $1
  AND ($2::bool OR r.visibility = 'public')
`

type CountReposByOwnerParams struct {
	OwnerID        int64
	IncludePrivate bool
}

func (q *Queries) CountReposByOwner(ctx context.Context, arg CountReposByOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReposByOwner, arg.OwnerID, arg.IncludePrivate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranchProtection = `-- name: CreateBranchProtection :one
INSERT INTO branch_protections (repo_id, pattern, forbid_force_push, forbid_delete, forbid_direct_push)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, repo_id, pattern, forbid_force_push, forbid_delete, forbid_direct_push, created_at, updated_at
`

type CreateBranchProtectionParams struct {
	RepoID           int64
	Pattern          string
	ForbidForcePush  bool
	ForbidDelete     bool
	ForbidDirectPush bool
}

func (q *Queries) CreateBranchProtection(ctx context.Context, arg CreateBranchProtectionParams) (BranchProtection, error) {
	row := q.db.QueryRow(ctx, createBranchProtection,
		arg.RepoID,
		arg.Pattern,
		arg.ForbidForcePush,
		arg.ForbidDelete,
		arg.ForbidDirectPush,
	)
	var i BranchProtection
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Pattern,
		&i.ForbidForcePush,
		&i.ForbidDelete,
		&i.ForbidDirectPush,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (owner_id, name, description, visibility, default_branch)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, name, description, visibility, default_branch, created_at, updated_at
`

type CreateRepoParams struct {
	OwnerID       int64
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, createRepo,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.DefaultBranch,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBranchProtection = `-- name: DeleteBranchProtection :execrows
DELETE FROM branch_protections WHERE id = $1 AND repo_id = $2
`

type DeleteBranchProtectionParams struct {
	ID     int64
	RepoID int64
}

func (q *Queries) DeleteBranchProtection(ctx context.Context, arg DeleteBranchProtectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBranchProtection, arg.ID, arg.RepoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRepo = `-- name: DeleteRepo :execrows
DELETE FROM repos WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRepo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existsRepoNameForOwner = `-- name: ExistsRepoNameForOwner :one
SELECT EXISTS (
    SELECT 1 FROM repos WHERE owner_id = $1 AND name = $2
)
`

type ExistsRepoNameForOwnerParams struct {
	OwnerID int64
	Name    string
}

func (q *Queries) ExistsRepoNameForOwner(ctx context.Context, arg ExistsRepoNameForOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsRepoNameForOwner, arg.OwnerID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBranchProtection = `-- name: GetBranchProtection :one
SELECT id, repo_id, pattern, forbid_force_push, forbid_delete, forbid_direct_push, created_at, updated_at
FROM branch_protections
WHERE id = $1 AND repo_id = $2
`

type GetBranchProtectionParams struct {
	ID     int64
	RepoID int64
}

func (q *Queries) GetBranchProtection(ctx context.Context, arg GetBranchProtectionParams) (BranchProtection, error) {
	row := q.db.QueryRow(ctx, getBranchProtection, arg.ID, arg.RepoID)
	var i BranchProtection
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Pattern,
		&i.ForbidForcePush,
		&i.ForbidDelete,
		&i.ForbidDirectPush,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT r.id, r.owner_id, r.name, r.description, r.visibility, r.default_branch, r.created_at, r.updated_at, u.username AS owner_username
FROM repos r
JOIN users u ON u.id = r.owner_id
WHERE r.id = $1
`

type GetRepoByIDRow struct {
	ID            int64
	OwnerID       int64
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerUsername string
}

func (q *Queries) GetRepoByID(ctx context.Context, id int64) (GetRepoByIDRow, error) {
	row := q.db.QueryRow(ctx, getRepoByID, id)
	var i GetRepoByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUsername,
	)
	return i, err
}

const getRepoByOwnerAndName = `-- name: GetRepoByOwnerAndName :one
SELECT r.id, r.owner_id, r.name, r.description, r.visibility, r.default_branch, r.created_at, r.updated_at, u.username AS owner_username
FROM repos r
JOIN users u ON u.id = r.owner_id
WHERE r.owner_id = $1 AND r.name = $2
`

type GetRepoByOwnerAndNameParams struct {
	OwnerID int64
	Name    string
}

type GetRepoByOwnerAndNameRow struct {
	ID            int64
	OwnerID       int64
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerUsername string
}

func (q *Queries) GetRepoByOwnerAndName(ctx context.Context, arg GetRepoByOwnerAndNameParams) (GetRepoByOwnerAndNameRow, error) {
	row := q.db.QueryRow(ctx, getRepoByOwnerAndName, arg.OwnerID, arg.Name)
	var i GetRepoByOwnerAndNameRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUsername,
	)
	return i, err
}

const listBranchProtectionsByRepo = `-- name: ListBranchProtectionsByRepo :many
SELECT id, repo_id, pattern, forbid_force_push, forbid_delete, forbid_direct_push, created_at, updated_at
FROM branch_protections
WHERE repo_id = $1
ORDER BY pattern
`

func (q *Queries) ListBranchProtectionsByRepo(ctx context.Context, repoID int64) ([]BranchProtection, error) {
	rows, err := q.db.Query(ctx, listBranchProtectionsByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchProtection{}
	for rows.Next() {
		var i BranchProtection
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Pattern,
			&i.ForbidForcePush,
			&i.ForbidDelete,
			&i.ForbidDirectPush,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByOwner = `-- name: ListReposByOwner :many
SELECT r.id, r.owner_id, r.name, r.description, r.visibility, r.default_branch, r.created_at, r.updated_at, u.username AS owner_username
FROM repos r
JOIN users u ON u.id = r.owner_id
WHERE r.owner_id = $1
  AND ($4::bool OR r.visibility = 'public')
ORDER BY r.created_at DESC, r.id DESC
LIMIT $2 OFFSET $3
`

type ListReposByOwnerParams struct {
	OwnerID        int64
	Limit          int32
	Offset         int32
	IncludePrivate bool
}

type ListReposByOwnerRow struct {
	ID            int64
	OwnerID       int64
	Name          string
	Description   string
	Visibility    string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	OwnerUsername string
}

func (q *Queries) ListReposByOwner(ctx context.Context, arg ListReposByOwnerParams) ([]ListReposByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listReposByOwner,
		arg.OwnerID,
		arg.Limit,
		arg.Offset,
		arg.IncludePrivate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReposByOwnerRow{}
	for rows.Next() {
		var i ListReposByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.DefaultBranch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranchProtection = `-- name: UpdateBranchProtection :one
UPDATE branch_protections
SET pattern             = $3,
    forbid_force_push   = $4,
    forbid_delete       = $5,
    forbid_direct_push  = $6,
    updated_at          = NOW()
WHERE id = $1 AND repo_id = $2
RETURNING id, repo_id, pattern, forbid_force_push, forbid_delete, forbid_direct_push, created_at, updated_at
`

type UpdateBranchProtectionParams struct {
	ID               int64
	RepoID           int64
	Pattern          string
	ForbidForcePush  bool
	ForbidDelete     bool
	ForbidDirectPush bool
}

func (q *Queries) UpdateBranchProtection(ctx context.Context, arg UpdateBranchProtectionParams) (BranchProtection, error) {
	row := q.db.QueryRow(ctx, updateBranchProtection,
		arg.ID,
		arg.RepoID,
		arg.Pattern,
		arg.ForbidForcePush,
		arg.ForbidDelete,
		arg.ForbidDirectPush,
	)
	var i BranchProtection
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Pattern,
		&i.ForbidForcePush,
		&i.ForbidDelete,
		&i.ForbidDirectPush,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepoMeta = `-- name: UpdateRepoMeta :one
UPDATE repos
SET description    = $2,
    default_branch = $3,
    visibility     = $4,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, owner_id, name, description, visibility, default_branch, created_at, updated_at
`

type UpdateRepoMetaParams struct {
	ID            int64
	Description   string
	DefaultBranch string
	Visibility    string
}

func (q *Queries) UpdateRepoMeta(ctx context.Context, arg UpdateRepoMetaParams) (Repo, error) {
	row := q.db.QueryRow(ctx, updateRepoMeta,
		arg.ID,
		arg.Description,
		arg.DefaultBranch,
		arg.Visibility,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
