// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package planenginedb

import (
	"context"
)

const createPlanState = `-- name: CreatePlanState :one
INSERT INTO plan_state (epic_issue_id)
VALUES ($1)
ON CONFLICT (epic_issue_id) DO NOTHING
RETURNING epic_issue_id, status, max_concurrency,
          auto_step_budget, auto_steps_used, updated_at
`

func (q *Queries) CreatePlanState(ctx context.Context, epicIssueID int64) (PlanState, error) {
	row := q.db.QueryRow(ctx, createPlanState, epicIssueID)
	var i PlanState
	err := row.Scan(
		&i.EpicIssueID,
		&i.Status,
		&i.MaxConcurrency,
		&i.AutoStepBudget,
		&i.AutoStepsUsed,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanState = `-- name: GetPlanState :one

SELECT epic_issue_id, status, max_concurrency,
       auto_step_budget, auto_steps_used, updated_at
FROM plan_state
WHERE epic_issue_id = $1
`

// ---- plan_state ----
func (q *Queries) GetPlanState(ctx context.Context, epicIssueID int64) (PlanState, error) {
	row := q.db.QueryRow(ctx, getPlanState, epicIssueID)
	var i PlanState
	err := row.Scan(
		&i.EpicIssueID,
		&i.Status,
		&i.MaxConcurrency,
		&i.AutoStepBudget,
		&i.AutoStepsUsed,
		&i.UpdatedAt,
	)
	return i, err
}

const incPlanStateStepsUsed = `-- name: IncPlanStateStepsUsed :exec
UPDATE plan_state
SET auto_steps_used = auto_steps_used + $1,
    updated_at = NOW()
WHERE epic_issue_id = $2
`

type IncPlanStateStepsUsedParams struct {
	Delta       int32
	EpicIssueID int64
}

func (q *Queries) IncPlanStateStepsUsed(ctx context.Context, arg IncPlanStateStepsUsedParams) error {
	_, err := q.db.Exec(ctx, incPlanStateStepsUsed, arg.Delta, arg.EpicIssueID)
	return err
}

const listActivePlanStates = `-- name: ListActivePlanStates :many
SELECT epic_issue_id, status, max_concurrency,
       auto_step_budget, auto_steps_used, updated_at
FROM plan_state
WHERE status = 'active'
ORDER BY epic_issue_id
`

func (q *Queries) ListActivePlanStates(ctx context.Context) ([]PlanState, error) {
	rows, err := q.db.Query(ctx, listActivePlanStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanState{}
	for rows.Next() {
		var i PlanState
		if err := rows.Scan(
			&i.EpicIssueID,
			&i.Status,
			&i.MaxConcurrency,
			&i.AutoStepBudget,
			&i.AutoStepsUsed,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlanStateBudget = `-- name: SetPlanStateBudget :exec
UPDATE plan_state
SET auto_step_budget = $1, updated_at = NOW()
WHERE epic_issue_id = $2
`

type SetPlanStateBudgetParams struct {
	Budget      int32
	EpicIssueID int64
}

func (q *Queries) SetPlanStateBudget(ctx context.Context, arg SetPlanStateBudgetParams) error {
	_, err := q.db.Exec(ctx, setPlanStateBudget, arg.Budget, arg.EpicIssueID)
	return err
}

const setPlanStateConcurrency = `-- name: SetPlanStateConcurrency :exec
UPDATE plan_state
SET max_concurrency = $1, updated_at = NOW()
WHERE epic_issue_id = $2
`

type SetPlanStateConcurrencyParams struct {
	N           int32
	EpicIssueID int64
}

func (q *Queries) SetPlanStateConcurrency(ctx context.Context, arg SetPlanStateConcurrencyParams) error {
	_, err := q.db.Exec(ctx, setPlanStateConcurrency, arg.N, arg.EpicIssueID)
	return err
}

const setPlanStateStatus = `-- name: SetPlanStateStatus :exec
UPDATE plan_state
SET status = $1, updated_at = NOW()
WHERE epic_issue_id = $2
`

type SetPlanStateStatusParams struct {
	Status      string
	EpicIssueID int64
}

func (q *Queries) SetPlanStateStatus(ctx context.Context, arg SetPlanStateStatusParams) error {
	_, err := q.db.Exec(ctx, setPlanStateStatus, arg.Status, arg.EpicIssueID)
	return err
}
