// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package llmproviderdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Actor struct {
	ID             int64
	Kind           string
	UserID         pgtype.Int8
	AgentRoleKey   pgtype.Text
	AgentSessionID pgtype.Int8
	WorkflowRunID  pgtype.Int8
	DisplayName    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type LlmProvider struct {
	ID              int64
	Name            string
	Type            string
	BaseUrl         string
	ApiKeyEncrypted string
	AllowedModels   []string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Disabled        bool
	ActorID         int64
}

type LlmUsageLog struct {
	ID               int64
	SessionID        pgtype.Int8
	ProviderID       int64
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMs        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
	CreatedAt        pgtype.Timestamptz
	RequestBody      string
	ResponseBody     string
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
