// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package llmproviderdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LlmProvider struct {
	ID              int64
	Name            string
	Type            string
	BaseUrl         string
	ApiKeyEncrypted string
	AllowedModels   []string
	CreatedBy       int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type LlmUsageLog struct {
	ID               int64
	SessionID        pgtype.Int8
	ProviderID       int64
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMs        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
