// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package llmproviderdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsage = `-- name: CountUsage :one
SELECT COUNT(*)::BIGINT
FROM llm_usage_log u
WHERE ($1::BIGINT IS NULL OR u.provider_id = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR u.created_at >= $2)
`

type CountUsageParams struct {
	ProviderID pgtype.Int8
	Since      pgtype.Timestamptz
}

// Mirrors ListUsage's WHERE clause so the admin usage page can render the
// total row count alongside the paged window.
func (q *Queries) CountUsage(ctx context.Context, arg CountUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsage, arg.ProviderID, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO llm_providers (
    name, type, base_url, api_key_encrypted, allowed_models, created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, name, type, base_url, api_key_encrypted, allowed_models, created_by, created_at, updated_at, disabled
`

type CreateProviderParams struct {
	Name            string
	Type            string
	BaseUrl         string
	ApiKeyEncrypted string
	AllowedModels   []string
	CreatedBy       int64
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.Type,
		arg.BaseUrl,
		arg.ApiKeyEncrypted,
		arg.AllowedModels,
		arg.CreatedBy,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.AllowedModels,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :execrows
DELETE FROM llm_providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findProviderByModel = `-- name: FindProviderByModel :one
SELECT id, name, type, base_url, api_key_encrypted, allowed_models, created_by, created_at, updated_at, disabled FROM llm_providers
WHERE $1::TEXT = ANY(allowed_models)
  AND NOT disabled
ORDER BY id ASC
LIMIT 1
`

// Lowest-id provider whose allowed_models contains :model wins. Explicit
// ::TEXT cast tells sqlc that the parameter is a single string, not an
// array — without it the inferred type matches the column type. Disabled
// providers are filtered out so the proxy responds 404 instead of routing
// to an upstream the operator has paused.
func (q *Queries) FindProviderByModel(ctx context.Context, model string) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, findProviderByModel, model)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.AllowedModels,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, type, base_url, api_key_encrypted, allowed_models, created_by, created_at, updated_at, disabled FROM llm_providers WHERE id = $1
`

func (q *Queries) GetProviderByID(ctx context.Context, id int64) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.AllowedModels,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
	)
	return i, err
}

const getProviderByName = `-- name: GetProviderByName :one
SELECT id, name, type, base_url, api_key_encrypted, allowed_models, created_by, created_at, updated_at, disabled FROM llm_providers WHERE name = $1
`

func (q *Queries) GetProviderByName(ctx context.Context, name string) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, getProviderByName, name)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.AllowedModels,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, type, base_url, api_key_encrypted, allowed_models, created_by, created_at, updated_at, disabled FROM llm_providers ORDER BY name ASC
`

func (q *Queries) ListProviders(ctx context.Context) ([]LlmProvider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmProvider{}
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.BaseUrl,
			&i.ApiKeyEncrypted,
			&i.AllowedModels,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsage = `-- name: ListUsage :many
SELECT u.id, u.session_id, u.provider_id, u.model, u.prompt_tokens, u.completion_tokens, u.total_tokens, u.latency_ms, u.status_code, u.error_message, u.request_path, u.created_at, p.name AS provider_name
FROM llm_usage_log u
JOIN llm_providers p ON p.id = u.provider_id
WHERE ($1::BIGINT IS NULL OR u.provider_id = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR u.created_at >= $2)
ORDER BY u.created_at DESC
LIMIT $4
OFFSET $3
`

type ListUsageParams struct {
	ProviderID pgtype.Int8
	Since      pgtype.Timestamptz
	Off        int32
	Lim        int32
}

type ListUsageRow struct {
	ID               int64
	SessionID        pgtype.Int8
	ProviderID       int64
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMs        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
	CreatedAt        pgtype.Timestamptz
	ProviderName     string
}

func (q *Queries) ListUsage(ctx context.Context, arg ListUsageParams) ([]ListUsageRow, error) {
	rows, err := q.db.Query(ctx, listUsage,
		arg.ProviderID,
		arg.Since,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsageRow{}
	for rows.Next() {
		var i ListUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProviderID,
			&i.Model,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.LatencyMs,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.RequestPath,
			&i.CreatedAt,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordUsage = `-- name: RecordUsage :exec
INSERT INTO llm_usage_log (
    session_id, provider_id, model,
    prompt_tokens, completion_tokens, total_tokens,
    latency_ms, status_code, error_message, request_path
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
`

type RecordUsageParams struct {
	SessionID        pgtype.Int8
	ProviderID       int64
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMs        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
}

func (q *Queries) RecordUsage(ctx context.Context, arg RecordUsageParams) error {
	_, err := q.db.Exec(ctx, recordUsage,
		arg.SessionID,
		arg.ProviderID,
		arg.Model,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.LatencyMs,
		arg.StatusCode,
		arg.ErrorMessage,
		arg.RequestPath,
	)
	return err
}

const setProviderDisabled = `-- name: SetProviderDisabled :one
UPDATE llm_providers SET
    disabled   = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, name, type, base_url, api_key_encrypted, allowed_models, created_by, created_at, updated_at, disabled
`

type SetProviderDisabledParams struct {
	Disabled bool
	ID       int64
}

// Dedicated flip so the admin UI can toggle enable/disable without having
// to round-trip the full UpdateProvider payload (and without risking a
// stale base_url / allowed_models clobber).
func (q *Queries) SetProviderDisabled(ctx context.Context, arg SetProviderDisabledParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, setProviderDisabled, arg.Disabled, arg.ID)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.AllowedModels,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
	)
	return i, err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE llm_providers SET
    base_url          = $1,
    api_key_encrypted = COALESCE($2, api_key_encrypted),
    allowed_models    = $3,
    disabled          = $4,
    updated_at        = NOW()
WHERE id = $5
RETURNING id, name, type, base_url, api_key_encrypted, allowed_models, created_by, created_at, updated_at, disabled
`

type UpdateProviderParams struct {
	BaseUrl         string
	ApiKeyEncrypted pgtype.Text
	AllowedModels   []string
	Disabled        bool
	ID              int64
}

// sqlc.narg('api_key_encrypted') makes the parameter nullable; COALESCE
// keeps the stored sealed blob when the caller passes NULL (= no rotation).
func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.BaseUrl,
		arg.ApiKeyEncrypted,
		arg.AllowedModels,
		arg.Disabled,
		arg.ID,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.AllowedModels,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
	)
	return i, err
}
