// Package infra holds the Postgres-backed dashboard aggregation queries.
// Generated by sqlc — see queries.sql for the SQL surface. No migrations
// live here; the dashboard only reads from tables owned by other modules.
package infra

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/hangrix/hangrix/apps/hangrix/internal/modules/dashboard/domain"
	"github.com/hangrix/hangrix/apps/hangrix/internal/modules/dashboard/infra/dashboarddb"
)

// PostgresRepo wraps the sqlc-generated dashboard queries.
type PostgresRepo struct {
	q *dashboarddb.Queries
}

type PostgresRepoDeps struct {
	Pool *pgxpool.Pool
}

func NewPostgresRepo(deps *PostgresRepoDeps) *PostgresRepo {
	return &PostgresRepo{
		q: dashboarddb.New(deps.Pool),
	}
}

// ---- filter helpers ----

type DashboardFilter struct {
	ProviderID *int64
	Since      *time.Time
	Until      *time.Time
}

func (f DashboardFilter) providerArg() pgtype.Int8 {
	var a pgtype.Int8
	if f.ProviderID != nil {
		a = pgtype.Int8{Int64: *f.ProviderID, Valid: true}
	}
	return a
}

func (f DashboardFilter) sinceArg() pgtype.Timestamptz {
	var a pgtype.Timestamptz
	if f.Since != nil {
		a = pgtype.Timestamptz{Time: *f.Since, Valid: true}
	}
	return a
}

func (f DashboardFilter) untilArg() pgtype.Timestamptz {
	var a pgtype.Timestamptz
	if f.Until != nil {
		a = pgtype.Timestamptz{Time: *f.Until, Valid: true}
	}
	return a
}

// ---- queries ----

// SummaryStats returns the aggregate KPI values for the selected time range.
func (r *PostgresRepo) SummaryStats(ctx context.Context, f DashboardFilter) (domain.Summary, error) {
	row, err := r.q.SummaryStats(ctx, dashboarddb.SummaryStatsParams{
		ProviderID: f.providerArg(),
		Since:      f.sinceArg(),
		Until:      f.untilArg(),
	})
	if err != nil {
		return domain.Summary{}, err
	}
	return domain.Summary{
		TotalCalls:  row.TotalCalls,
		TotalTokens: row.TotalTokens,
		FailedCalls: row.FailedCalls,
	}, nil
}

// DailyCalls returns day-level request counts for the selected time range.
func (r *PostgresRepo) DailyCalls(ctx context.Context, f DashboardFilter) ([]domain.DailyCalls, error) {
	rows, err := r.q.DailyCalls(ctx, dashboarddb.DailyCallsParams{
		ProviderID: f.providerArg(),
		Since:      f.sinceArg(),
		Until:      f.untilArg(),
	})
	if err != nil {
		return nil, err
	}
	out := make([]domain.DailyCalls, 0, len(rows))
	for _, row := range rows {
		out = append(out, domain.DailyCalls{Date: row.Date, Count: row.Count})
	}
	return out, nil
}

// DailyTokens returns day-level token usage for the selected time range.
func (r *PostgresRepo) DailyTokens(ctx context.Context, f DashboardFilter) ([]domain.DailyTokens, error) {
	rows, err := r.q.DailyTokens(ctx, dashboarddb.DailyTokensParams{
		ProviderID: f.providerArg(),
		Since:      f.sinceArg(),
		Until:      f.untilArg(),
	})
	if err != nil {
		return nil, err
	}
	out := make([]domain.DailyTokens, 0, len(rows))
	for _, row := range rows {
		out = append(out, domain.DailyTokens{
			Date:             row.Date,
			TotalTokens:      row.TotalTokens,
			PromptTokens:     row.PromptTokens,
			CompletionTokens: row.CompletionTokens,
		})
	}
	return out, nil
}

// ProviderBreakdown returns per-provider aggregation for the leaderboard.
func (r *PostgresRepo) ProviderBreakdown(ctx context.Context, f DashboardFilter) ([]domain.ProviderStat, error) {
	rows, err := r.q.ProviderBreakdown(ctx, dashboarddb.ProviderBreakdownParams{
		ProviderID: f.providerArg(),
		Since:      f.sinceArg(),
		Until:      f.untilArg(),
	})
	if err != nil {
		return nil, err
	}
	out := make([]domain.ProviderStat, 0, len(rows))
	for _, row := range rows {
		out = append(out, domain.ProviderStat{
			ProviderName: row.ProviderName,
			Calls:        row.Calls,
			TotalTokens:  row.TotalTokens,
		})
	}
	return out, nil
}

// RunnerHealth returns runner liveness breakdown and total count.
func (r *PostgresRepo) RunnerHealth(ctx context.Context) (domain.Health, error) {
	row, err := r.q.RunnerHealth(ctx)
	if err != nil {
		return domain.Health{}, err
	}
	liveSess, err := r.q.LiveSessions(ctx)
	if err != nil {
		return domain.Health{}, err
	}
	return domain.Health{
		OnlineRunners:   row.OnlineRunners,
		OfflineRunners:  row.OfflineRunners,
		DisabledRunners: row.DisabledRunners,
		LiveSessions:    liveSess,
	}, nil
}

// TotalRunners returns the count from the RunnerHealth query.
func (r *PostgresRepo) TotalRunners(ctx context.Context) (int64, error) {
	row, err := r.q.RunnerHealth(ctx)
	if err != nil {
		return 0, err
	}
	return row.TotalRunners, nil
}

// RecentFailures returns the most recent failed calls (status >= 400).
func (r *PostgresRepo) RecentFailures(ctx context.Context, f DashboardFilter, limit int32) ([]domain.FailureItem, error) {
	rows, err := r.q.RecentFailures(ctx, dashboarddb.RecentFailuresParams{
		ProviderID: f.providerArg(),
		Since:      f.sinceArg(),
		Until:      f.untilArg(),
		Lim:        limit,
	})
	if err != nil {
		return nil, err
	}
	out := make([]domain.FailureItem, 0, len(rows))
	for _, row := range rows {
		item := domain.FailureItem{
			ID:           row.ID,
			ProviderName: row.ProviderName,
			Model:        row.Model,
			StatusCode:   row.StatusCode,
			ErrorMessage: row.ErrorMessage,
			CreatedAt:    row.CreatedAt.Time,
		}
		if row.SessionID.Valid {
			v := row.SessionID.Int64
			item.SessionID = &v
		}
		out = append(out, item)
	}
	return out, nil
}
