// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dashboarddb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dailyCalls = `-- name: DailyCalls :many
SELECT
  DATE(created_at)::TEXT AS date,
  COUNT(*)::BIGINT AS count
FROM llm_usage_log u
WHERE ($1::BIGINT IS NULL OR u.provider_id = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR u.created_at >= $2)
  AND ($3::TIMESTAMPTZ IS NULL OR u.created_at < $3)
GROUP BY DATE(created_at)
ORDER BY DATE(created_at) ASC
`

type DailyCallsParams struct {
	ProviderID pgtype.Int8
	Since      pgtype.Timestamptz
	Until      pgtype.Timestamptz
}

type DailyCallsRow struct {
	Date  string
	Count int64
}

func (q *Queries) DailyCalls(ctx context.Context, arg DailyCallsParams) ([]DailyCallsRow, error) {
	rows, err := q.db.Query(ctx, dailyCalls, arg.ProviderID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyCallsRow{}
	for rows.Next() {
		var i DailyCallsRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dailyTokens = `-- name: DailyTokens :many
SELECT
  DATE(created_at)::TEXT AS date,
  COALESCE(SUM(total_tokens), 0)::BIGINT AS total_tokens,
  COALESCE(SUM(prompt_tokens), 0)::BIGINT AS prompt_tokens,
  COALESCE(SUM(completion_tokens), 0)::BIGINT AS completion_tokens
FROM llm_usage_log u
WHERE ($1::BIGINT IS NULL OR u.provider_id = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR u.created_at >= $2)
  AND ($3::TIMESTAMPTZ IS NULL OR u.created_at < $3)
GROUP BY DATE(created_at)
ORDER BY DATE(created_at) ASC
`

type DailyTokensParams struct {
	ProviderID pgtype.Int8
	Since      pgtype.Timestamptz
	Until      pgtype.Timestamptz
}

type DailyTokensRow struct {
	Date             string
	TotalTokens      int64
	PromptTokens     int64
	CompletionTokens int64
}

func (q *Queries) DailyTokens(ctx context.Context, arg DailyTokensParams) ([]DailyTokensRow, error) {
	rows, err := q.db.Query(ctx, dailyTokens, arg.ProviderID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyTokensRow{}
	for rows.Next() {
		var i DailyTokensRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalTokens,
			&i.PromptTokens,
			&i.CompletionTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveSessions = `-- name: LiveSessions :one
SELECT COUNT(*)::BIGINT AS live_sessions
FROM agent_sessions
WHERE status IN ('pending', 'claimed', 'running', 'idle')
`

func (q *Queries) LiveSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, liveSessions)
	var live_sessions int64
	err := row.Scan(&live_sessions)
	return live_sessions, err
}

const providerBreakdown = `-- name: ProviderBreakdown :many
SELECT
  p.name AS provider_name,
  COUNT(*)::BIGINT AS calls,
  COALESCE(SUM(u.total_tokens), 0)::BIGINT AS total_tokens
FROM llm_usage_log u
JOIN llm_providers p ON p.id = u.provider_id
WHERE ($1::BIGINT IS NULL OR u.provider_id = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR u.created_at >= $2)
  AND ($3::TIMESTAMPTZ IS NULL OR u.created_at < $3)
GROUP BY p.id, p.name
ORDER BY calls DESC
`

type ProviderBreakdownParams struct {
	ProviderID pgtype.Int8
	Since      pgtype.Timestamptz
	Until      pgtype.Timestamptz
}

type ProviderBreakdownRow struct {
	ProviderName string
	Calls        int64
	TotalTokens  int64
}

func (q *Queries) ProviderBreakdown(ctx context.Context, arg ProviderBreakdownParams) ([]ProviderBreakdownRow, error) {
	rows, err := q.db.Query(ctx, providerBreakdown, arg.ProviderID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderBreakdownRow{}
	for rows.Next() {
		var i ProviderBreakdownRow
		if err := rows.Scan(&i.ProviderName, &i.Calls, &i.TotalTokens); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentFailures = `-- name: RecentFailures :many
SELECT
  u.id,
  p.name AS provider_name,
  u.model,
  u.status_code,
  u.error_message,
  u.created_at,
  u.session_id
FROM llm_usage_log u
JOIN llm_providers p ON p.id = u.provider_id
WHERE u.status_code >= 400
  AND ($1::BIGINT IS NULL OR u.provider_id = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR u.created_at >= $2)
  AND ($3::TIMESTAMPTZ IS NULL OR u.created_at < $3)
ORDER BY u.created_at DESC
LIMIT $4
`

type RecentFailuresParams struct {
	ProviderID pgtype.Int8
	Since      pgtype.Timestamptz
	Until      pgtype.Timestamptz
	Lim        int32
}

type RecentFailuresRow struct {
	ID           int64
	ProviderName string
	Model        string
	StatusCode   int32
	ErrorMessage string
	CreatedAt    pgtype.Timestamptz
	SessionID    pgtype.Int8
}

func (q *Queries) RecentFailures(ctx context.Context, arg RecentFailuresParams) ([]RecentFailuresRow, error) {
	rows, err := q.db.Query(ctx, recentFailures,
		arg.ProviderID,
		arg.Since,
		arg.Until,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentFailuresRow{}
	for rows.Next() {
		var i RecentFailuresRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderName,
			&i.Model,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runnerHealth = `-- name: RunnerHealth :one
SELECT
  COUNT(*) FILTER (WHERE status = 'active' AND last_heartbeat_at >= NOW() - INTERVAL '60 seconds')::BIGINT AS online_runners,
  COUNT(*) FILTER (WHERE status = 'active' AND (last_heartbeat_at IS NULL OR last_heartbeat_at < NOW() - INTERVAL '60 seconds'))::BIGINT AS offline_runners,
  COUNT(*) FILTER (WHERE status = 'disabled')::BIGINT AS disabled_runners,
  COUNT(*)::BIGINT AS total_runners
FROM runners
`

type RunnerHealthRow struct {
	OnlineRunners   int64
	OfflineRunners  int64
	DisabledRunners int64
	TotalRunners    int64
}

func (q *Queries) RunnerHealth(ctx context.Context) (RunnerHealthRow, error) {
	row := q.db.QueryRow(ctx, runnerHealth)
	var i RunnerHealthRow
	err := row.Scan(
		&i.OnlineRunners,
		&i.OfflineRunners,
		&i.DisabledRunners,
		&i.TotalRunners,
	)
	return i, err
}

const summaryStats = `-- name: SummaryStats :one
SELECT
  COUNT(*)::BIGINT AS total_calls,
  COALESCE(SUM(total_tokens), 0)::BIGINT AS total_tokens,
  COUNT(*) FILTER (WHERE status_code >= 400)::BIGINT AS failed_calls
FROM llm_usage_log u
WHERE ($1::BIGINT IS NULL OR u.provider_id = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR u.created_at >= $2)
  AND ($3::TIMESTAMPTZ IS NULL OR u.created_at < $3)
`

type SummaryStatsParams struct {
	ProviderID pgtype.Int8
	Since      pgtype.Timestamptz
	Until      pgtype.Timestamptz
}

type SummaryStatsRow struct {
	TotalCalls  int64
	TotalTokens int64
	FailedCalls int64
}

func (q *Queries) SummaryStats(ctx context.Context, arg SummaryStatsParams) (SummaryStatsRow, error) {
	row := q.db.QueryRow(ctx, summaryStats, arg.ProviderID, arg.Since, arg.Until)
	var i SummaryStatsRow
	err := row.Scan(&i.TotalCalls, &i.TotalTokens, &i.FailedCalls)
	return i, err
}
