// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package userdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
