// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package platformsettingsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PlatformSetting struct {
	Key       string
	Value     string
	UpdatedAt pgtype.Timestamptz
	UpdatedBy pgtype.Int8
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	Disabled     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
