// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package platformsettingsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PlatformSetting struct {
	Key         string
	Value       string
	Description string
	UpdatedAt   pgtype.Timestamptz
}
