// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package platformsettingsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getByKey = `-- name: GetByKey :one
SELECT key, value, updated_at, updated_by FROM platform_settings WHERE key = $1
`

func (q *Queries) GetByKey(ctx context.Context, key string) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, getByKey, key)
	var i PlatformSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listAll = `-- name: ListAll :many
SELECT key, value, updated_at, updated_by FROM platform_settings ORDER BY key ASC
`

func (q *Queries) ListAll(ctx context.Context) ([]PlatformSetting, error) {
	rows, err := q.db.Query(ctx, listAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformSetting{}
	for rows.Next() {
		var i PlatformSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO platform_settings (key, value, updated_by, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW()
`

type UpsertSettingParams struct {
	Key       string
	Value     string
	UpdatedBy pgtype.Int8
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value, arg.UpdatedBy)
	return err
}
