// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package platformsettingsdb

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value, description, updated_at
FROM platform_settings
WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i PlatformSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, description, updated_at
FROM platform_settings
ORDER BY key ASC
`

func (q *Queries) ListSettings(ctx context.Context) ([]PlatformSetting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformSetting{}
	for rows.Next() {
		var i PlatformSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO platform_settings (key, value, description)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (key) DO UPDATE SET
    value      = EXCLUDED.value,
    updated_at = NOW()
`

type UpsertSettingParams struct {
	Key         string
	Value       string
	Description string
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value, arg.Description)
	return err
}
