package service

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/hangrix/hangrix/apps/hangrix/internal/agentsconfig"
	agentsessiondomain "github.com/hangrix/hangrix/apps/hangrix/internal/modules/agent_session/domain"
	issuedomain "github.com/hangrix/hangrix/apps/hangrix/internal/modules/issue/domain"
	platformmcpdomain "github.com/hangrix/hangrix/apps/hangrix/internal/modules/platform_mcp/domain"
	runnerdomain "github.com/hangrix/hangrix/apps/hangrix/internal/modules/runner/domain"
)

// issuePatchSubmitTool lets an agent submit one or more patch files
// (generated with `git format-patch`) against the current issue.
// patch_paths is an array of workspace file paths; the server reads each
// file, parses stats, and stores them as an ordered patch series.
// base_head_sha is recorded for audit but does NOT gate application —
// whether the series can be applied is decided by `git am` at apply time.
func (r *Registry) issuePatchSubmitTool() *platformmcpdomain.Tool {
	return &platformmcpdomain.Tool{
		Name:        "issue_patch_submit",
		Description: "Submit one or more patch files (generated with `git format-patch`) to the current issue. Pass workspace file paths; the server reads the contents. Patches are stored as an ordered series for review and may be applied by a maintainer.",
		InputSchema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"title": map[string]any{
					"type":        "string",
					"description": "Short title describing this patch series (1-200 chars).",
				},
				"description": map[string]any{
					"type":        "string",
					"description": "Optional longer description of what the patch series does and why.",
				},
				"base_head_sha": map[string]any{
					"type":        "string",
					"description": "The issue branch head SHA this patch series is based on. Used for audit only — does not block application.",
				},
				"patch_paths": map[string]any{
					"type":        "array",
					"items":       map[string]any{"type": "string"},
					"description": "Ordered list of workspace file paths to patch files generated by `git format-patch`. Paths are read from disk by the server.",
				},
			},
			"required": []string{"title", "patch_paths"},
		},
		Call: func(ctx context.Context, sess *runnerdomain.AgentSession, args json.RawMessage) (platformmcpdomain.Result, error) {
			scope, err := r.loadScope(ctx, sess)
			if err != nil {
				return errorResult(err.Error()), nil
			}
			var req struct {
				Title       string   `json:"title"`
				Description string   `json:"description"`
				BaseHeadSHA string   `json:"base_head_sha"`
				PatchPaths  []string `json:"patch_paths"`
			}
			if err := unmarshalArgs(args, &req); err != nil {
				return errorResult("invalid arguments: " + err.Error()), nil
			}
			title := strings.TrimSpace(req.Title)
			if title == "" || len(title) > 200 {
				return errorResult("title is required (1-200 chars)"), nil
			}
			if len(req.PatchPaths) == 0 {
				return errorResult("patch_paths is required and must have at least one path"), nil
			}

			// Read each patch file and build the file params.
			files := make([]issuedomain.PatchFileParams, 0, len(req.PatchPaths))
			var allChanged []string
			seenPaths := make(map[string]struct{})
			var totalAdditions, totalDeletions, totalFileCount int32

			for i, path := range req.PatchPaths {
				resolved, err := resolveWorkspacePath(scope.fsPath, path)
				if err != nil {
					return errorResult(fmt.Sprintf("invalid patch_paths[%d] %q: %v", i, path, err)), nil
				}
				data, err := os.ReadFile(resolved)
				if err != nil {
					return errorResult(fmt.Sprintf("cannot read patch_paths[%d] %q: %v", i, path, err)), nil
				}
				text := string(data)
				// Extract subject from the first "Subject: " line in the patch.
				subject := ""
				for _, line := range strings.Split(text, "\n") {
					if strings.HasPrefix(line, "Subject: ") {
						subject = strings.TrimPrefix(line, "Subject: ")
						// Strip leading [PATCH ...] prefix if present.
						if idx := strings.Index(subject, "] "); idx >= 0 && strings.HasPrefix(subject, "[") {
							subject = subject[idx+2:]
						}
						break
					}
				}
				// Parse stats for this patch file.
				paths, fc, adds, dels := parsePatchStats(text)
				for _, p := range paths {
					if _, ok := seenPaths[p]; !ok {
						seenPaths[p] = struct{}{}
						allChanged = append(allChanged, p)
					}
				}
				totalFileCount += fc
				totalAdditions += adds
				totalDeletions += dels

				files = append(files, issuedomain.PatchFileParams{
					Seq:       int32(i + 1),
					FileName:  path,
					PatchText: text,
					Subject:   subject,
				})
			}

			p := &issuedomain.PatchSubmission{
				RepoID:       scope.repo.ID,
				IssueID:      scope.issue.ID,
				SessionID:    sess.ID,
				AgentRole:    sess.RoleKey,
				BaseHeadSHA:  strings.TrimSpace(req.BaseHeadSHA),
				Title:        title,
				Description:  strings.TrimSpace(req.Description),
				PatchCount:   int32(len(files)),
				ChangedPaths: allChanged,
				FileCount:    totalFileCount,
				Additions:    totalAdditions,
				Deletions:    totalDeletions,
				Status:       issuedomain.PatchStatusSubmitted,
			}

			created, err := r.deps.Patches.CreatePatch(ctx, p)
			if err != nil {
				return errorResult("create patch: " + err.Error()), nil
			}

			// Store the patch file series.
			if err := r.deps.Patches.CreatePatchFiles(ctx, created.ID, files); err != nil {
				return errorResult("create patch files: " + err.Error()), nil
			}

			// Supersede previous submitted patches from the same role.
			_, _ = r.deps.Patches.SupersedePatches(ctx, scope.issue.ID, sess.RoleKey, created.ID)

			// Write timeline event.
			payload, _ := json.Marshal(issuedomain.PatchEventPayload{
				SubmissionID: created.ID,
				Title:        created.Title,
				AgentRole:    created.AgentRole,
			})
			_, _ = r.deps.Issues.CreateAgentEvent(ctx, scope.issue.ID, issuedomain.EventPatchSubmitted, payload, sess.RoleKey)

			// Fire patch.submitted trigger.
			r.firePatchSubmitted(ctx, sess, scope, created)

			return textResult(map[string]any{
				"id":             created.ID,
				"status":         string(created.Status),
				"title":          created.Title,
				"patch_count":    created.PatchCount,
				"file_count":     created.FileCount,
				"additions":      created.Additions,
				"deletions":      created.Deletions,
				"changed_paths":  created.ChangedPaths,
				"base_head_sha":  created.BaseHeadSHA,
				"created_at":     stableTime(created.CreatedAt),
			}), nil
		},
	}
}

// firePatchSubmitted dispatches the patch.submitted trigger so
// reviewer / tester / maintainer roles wake. ChangedPaths is carried
// so per-role PushFilter (paths / paths_ignore) can be evaluated.
func (r *Registry) firePatchSubmitted(ctx context.Context, sess *runnerdomain.AgentSession, scope *sessionScope, patch *issuedomain.PatchSubmission) {
	if r.deps.Spawner == nil {
		return
	}
	triggerPayload, _ := json.Marshal(map[string]any{
		"submission_id": patch.ID,
		"title":         patch.Title,
		"description":   patch.Description,
		"agent_role":    patch.AgentRole,
		"base_head_sha": patch.BaseHeadSHA,
	})
	_, _ = r.deps.Spawner.OnTrigger(ctx, agentsessiondomain.TriggerInput{
		Trigger:      agentsconfig.TriggerPatchSubmitted,
		CauseKind:    agentsessiondomain.CauseKindPatchSubmitted,
		CauseID:      strconv.FormatInt(patch.ID, 10),
		RepoID:       scope.repo.ID,
		IssueNumber:  *sess.IssueNumber,
		ActorID:      sess.CreatedBy,
		ChangedPaths: patch.ChangedPaths,
		Payload:      triggerPayload,
	})
}

// issuePatchListTool returns all patches for the current issue.
func (r *Registry) issuePatchListTool() *platformmcpdomain.Tool {
	return &platformmcpdomain.Tool{
		Name:        "issue_patch_list",
		Description: "List all patch submissions on the current issue, newest first. Each entry includes id, title, status, agent_role, file_count, additions, deletions, and timestamps.",
		InputSchema: map[string]any{
			"type":       "object",
			"properties": map[string]any{},
		},
		Call: func(ctx context.Context, sess *runnerdomain.AgentSession, args json.RawMessage) (platformmcpdomain.Result, error) {
			scope, err := r.loadScope(ctx, sess)
			if err != nil {
				return errorResult(err.Error()), nil
			}
			patches, err := r.deps.Patches.ListPatches(ctx, scope.issue.ID)
			if err != nil {
				return errorResult("list patches: " + err.Error()), nil
			}
			items := make([]map[string]any, 0, len(patches))
			for _, p := range patches {
				items = append(items, patchSummary(p))
			}
			return textResult(map[string]any{"patches": items}), nil
		},
	}
}

// issuePatchReadTool returns metadata + ordered patch files for a submission.
func (r *Registry) issuePatchReadTool() *platformmcpdomain.Tool {
	return &platformmcpdomain.Tool{
		Name:        "issue_patch_read",
		Description: "Read a single patch submission's metadata and ordered patch files. Use the id from issue_patch_list.",
		InputSchema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{
					"type":        "integer",
					"description": "Patch submission ID to read.",
				},
			},
			"required": []string{"id"},
		},
		Call: func(ctx context.Context, sess *runnerdomain.AgentSession, args json.RawMessage) (platformmcpdomain.Result, error) {
			scope, err := r.loadScope(ctx, sess)
			if err != nil {
				return errorResult(err.Error()), nil
			}
			var req struct {
				ID int64 `json:"id"`
			}
			if err := unmarshalArgs(args, &req); err != nil {
				return errorResult("invalid arguments: " + err.Error()), nil
			}
			if req.ID <= 0 {
				return errorResult("id is required and must be positive"), nil
			}
			patch, err := r.deps.Patches.GetPatch(ctx, req.ID)
			if err != nil {
				return errorResult("get patch: " + err.Error()), nil
			}
			if patch.IssueID != scope.issue.ID {
				return errorResult("patch does not belong to the current issue"), nil
			}
			// Fetch the ordered patch files.
			patchFiles, err := r.deps.Patches.GetPatchFiles(ctx, patch.ID)
			if err != nil {
				return errorResult("get patch files: " + err.Error()), nil
			}
			files := make([]map[string]any, 0, len(patchFiles))
			for _, f := range patchFiles {
				files = append(files, map[string]any{
					"index":      f.Seq,
					"file_name":  f.FileName,
					"subject":    f.Subject,
					"patch_text": f.PatchText,
				})
			}
			return textResult(map[string]any{
				"summary": patchSummary(patch),
				"patches": files,
			}), nil
		},
	}
}

// issuePatchApplyTool transitions a submitted patch to 'applying' so a
// dedicated apply agent can pick it up and apply via `git am` in its
// workspace. No longer applies the patch synchronously. base_head_sha is
// NOT gated — the apply agent decides via real `git am` whether the series
// can be applied.
func (r *Registry) issuePatchApplyTool() *platformmcpdomain.Tool {
	return &platformmcpdomain.Tool{
		Name:        "issue_patch_apply",
		Description: "Request application of a patch submission. Transitions the patch to 'applying' so a dedicated apply agent can pick it up and apply via `git am` in its workspace. Requires `issue_patch_apply` in the role's `can:` whitelist.",
		InputSchema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{
					"type":        "integer",
					"description": "Patch submission ID to request application for.",
				},
			},
			"required": []string{"id"},
		},
		Call: func(ctx context.Context, sess *runnerdomain.AgentSession, args json.RawMessage) (platformmcpdomain.Result, error) {
			scope, err := r.loadScope(ctx, sess)
			if err != nil {
				return errorResult(err.Error()), nil
			}
			var req struct {
				ID int64 `json:"id"`
			}
			if err := unmarshalArgs(args, &req); err != nil {
				return errorResult("invalid arguments: " + err.Error()), nil
			}
			if req.ID <= 0 {
				return errorResult("id is required and must be positive"), nil
			}

			patch, err := r.deps.Patches.GetPatch(ctx, req.ID)
			if err != nil {
				return errorResult("get patch: " + err.Error()), nil
			}
			if patch.IssueID != scope.issue.ID {
				return errorResult("patch does not belong to the current issue"), nil
			}

			// Only submitted patches can be accepted for application.
			if patch.Status != issuedomain.PatchStatusSubmitted {
				return errorResult(fmt.Sprintf("cannot apply patch with status '%s' — must be 'submitted'", patch.Status)), nil
			}

			// Transition to applying so the apply agent can pick it up.
			updated, err := r.deps.Patches.MarkApplying(ctx, patch.ID)
			if err != nil {
				if errors.Is(err, issuedomain.ErrPatchNotSubmitted) {
					return errorResult("patch is not in 'submitted' state — may have been claimed by another apply request"), nil
				}
				return errorResult("mark applying: " + err.Error()), nil
			}

			// Write timeline event.
			payload, _ := json.Marshal(issuedomain.PatchEventPayload{
				SubmissionID: updated.ID,
				Title:        updated.Title,
				AgentRole:    updated.AgentRole,
			})
			_, _ = r.deps.Issues.CreateAgentEvent(ctx, scope.issue.ID, issuedomain.EventPatchApplying, payload, sess.RoleKey)

			// Fire patch.apply_requested trigger to wake the apply agent.
			r.firePatchApplyRequested(ctx, sess, scope, updated)

			return textResult(map[string]any{
				"id":      updated.ID,
				"status":  string(updated.Status),
				"message": "apply request accepted — a dedicated apply agent will pick up this submission",
			}), nil
		},
	}
}

// firePatchApplyRequested wakes the apply-agent role so it picks up the
// submission and applies it via `git am` in its workspace.
func (r *Registry) firePatchApplyRequested(ctx context.Context, sess *runnerdomain.AgentSession, scope *sessionScope, patch *issuedomain.PatchSubmission) {
	if r.deps.Spawner == nil {
		return
	}
	triggerPayload, _ := json.Marshal(map[string]any{
		"submission_id": patch.ID,
		"issue_number":  *sess.IssueNumber,
	})
	_, _ = r.deps.Spawner.OnTrigger(ctx, agentsessiondomain.TriggerInput{
		Trigger:     agentsconfig.TriggerPatchApplyRequested,
		CauseKind:   agentsessiondomain.CauseKindPatchApplyRequested,
		CauseID:     strconv.FormatInt(patch.ID, 10),
		RepoID:      scope.repo.ID,
		IssueNumber: *sess.IssueNumber,
		ActorID:     sess.CreatedBy,
		Payload:     triggerPayload,
	})
}

// issuePatchRejectTool rejects a patch submission. Patches with status
// 'submitted' or 'applying' can be rejected. A patch_rejected event is
// recorded.
func (r *Registry) issuePatchRejectTool() *platformmcpdomain.Tool {
	return &platformmcpdomain.Tool{
		Name:        "issue_patch_reject",
		Description: "Reject a patch submission. Patches with status='submitted' or 'applying' can be rejected. The patch is not applied; a rejection reason is recorded. Requires `issue_patch_reject` in the role's `can:` whitelist.",
		InputSchema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{
					"type":        "integer",
					"description": "Patch submission ID to reject.",
				},
				"reason": map[string]any{
					"type":        "string",
					"description": "Reason for rejection (required, shown on timeline).",
				},
			},
			"required": []string{"id", "reason"},
		},
		Call: func(ctx context.Context, sess *runnerdomain.AgentSession, args json.RawMessage) (platformmcpdomain.Result, error) {
			scope, err := r.loadScope(ctx, sess)
			if err != nil {
				return errorResult(err.Error()), nil
			}
			var req struct {
				ID     int64  `json:"id"`
				Reason string `json:"reason"`
			}
			if err := unmarshalArgs(args, &req); err != nil {
				return errorResult("invalid arguments: " + err.Error()), nil
			}
			if req.ID <= 0 {
				return errorResult("id is required and must be positive"), nil
			}
			reason := strings.TrimSpace(req.Reason)
			if reason == "" {
				return errorResult("reason is required"), nil
			}

			patch, err := r.deps.Patches.GetPatch(ctx, req.ID)
			if err != nil {
				return errorResult("get patch: " + err.Error()), nil
			}
			if patch.IssueID != scope.issue.ID {
				return errorResult("patch does not belong to the current issue"), nil
			}
			if patch.Status != issuedomain.PatchStatusSubmitted && patch.Status != issuedomain.PatchStatusApplying {
				return errorResult(fmt.Sprintf("cannot reject patch with status '%s' — must be 'submitted' or 'applying'", patch.Status)), nil
			}

			updated, err := r.deps.Patches.UpdatePatchStatus(ctx, patch.ID, issuedomain.PatchStatusRejected, "", reason)
			if err != nil {
				return errorResult("update patch status: " + err.Error()), nil
			}

			// Write timeline event.
			payload, _ := json.Marshal(issuedomain.PatchEventPayload{
				SubmissionID: updated.ID,
				Title:        updated.Title,
				AgentRole:    updated.AgentRole,
				Reason:       reason,
			})
			_, _ = r.deps.Issues.CreateAgentEvent(ctx, scope.issue.ID, issuedomain.EventPatchRejected, payload, sess.RoleKey)

			return textResult(map[string]any{
				"id":     updated.ID,
				"status": string(updated.Status),
				"reason": updated.RejectedReason,
			}), nil
		},
	}
}

// issuePatchWithdrawTool lets the original submitter withdraw their own
// patch submission. Only the submitter's session/role can withdraw, and
// only patches with status 'submitted' can be withdrawn.
func (r *Registry) issuePatchWithdrawTool() *platformmcpdomain.Tool {
	return &platformmcpdomain.Tool{
		Name:        "issue_patch_withdraw",
		Description: "Withdraw your own patch submission. Only the original submitter can withdraw, and only patches with status='submitted' can be withdrawn. The patch is no longer considered for application.",
		InputSchema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id": map[string]any{
					"type":        "integer",
					"description": "Patch submission ID to withdraw.",
				},
			},
			"required": []string{"id"},
		},
		Call: func(ctx context.Context, sess *runnerdomain.AgentSession, args json.RawMessage) (platformmcpdomain.Result, error) {
			scope, err := r.loadScope(ctx, sess)
			if err != nil {
				return errorResult(err.Error()), nil
			}
			var req struct {
				ID int64 `json:"id"`
			}
			if err := unmarshalArgs(args, &req); err != nil {
				return errorResult("invalid arguments: " + err.Error()), nil
			}
			if req.ID <= 0 {
				return errorResult("id is required and must be positive"), nil
			}

			patch, err := r.deps.Patches.GetPatch(ctx, req.ID)
			if err != nil {
				return errorResult("get patch: " + err.Error()), nil
			}
			if patch.IssueID != scope.issue.ID {
				return errorResult("patch does not belong to the current issue"), nil
			}
			// Only the original submitter (same agent_role) can withdraw.
			if patch.AgentRole != sess.RoleKey {
				return errorResult("only the original submitter can withdraw their own patch"), nil
			}
			if patch.Status != issuedomain.PatchStatusSubmitted {
				return errorResult(fmt.Sprintf("cannot withdraw patch with status '%s' — must be 'submitted'", patch.Status)), nil
			}

			updated, err := r.deps.Patches.UpdatePatchStatus(ctx, patch.ID, issuedomain.PatchStatusWithdrawn, "", "")
			if err != nil {
				return errorResult("update patch status: " + err.Error()), nil
			}

			// Write timeline event.
			payload, _ := json.Marshal(issuedomain.PatchEventPayload{
				SubmissionID: updated.ID,
				Title:        updated.Title,
				AgentRole:    updated.AgentRole,
			})
			_, _ = r.deps.Issues.CreateAgentEvent(ctx, scope.issue.ID, issuedomain.EventPatchWithdrawn, payload, sess.RoleKey)

			return textResult(map[string]any{
				"id":     updated.ID,
				"status": string(updated.Status),
			}), nil
		},
	}
}

// issuePatchApplyResultTool is called by the apply agent after it attempts
// to `git am` the patch series in its workspace. It writes back success
// (with the new commit SHA) or failure (with an error message).
func (r *Registry) issuePatchApplyResultTool() *platformmcpdomain.Tool {
	return &platformmcpdomain.Tool{
		Name:        "issue_patch_apply_result",
		Description: "Report the result of a patch application attempt. Called by the apply agent after `git am` + `git push`. On success the patch is marked 'applied' and the issue head is updated. On failure the error is recorded and the patch can be retried.",
		InputSchema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"submission_id": map[string]any{
					"type":        "integer",
					"description": "Patch submission ID that was being applied.",
				},
				"success": map[string]any{
					"type":        "boolean",
					"description": "Whether `git am` + `git push` succeeded.",
				},
				"commit_sha": map[string]any{
					"type":        "string",
					"description": "The new commit SHA on the issue branch (required when success=true).",
				},
				"error": map[string]any{
					"type":        "string",
					"description": "Error message from `git am` or `git push` (required when success=false).",
				},
			},
			"required": []string{"submission_id", "success"},
		},
		Call: func(ctx context.Context, sess *runnerdomain.AgentSession, args json.RawMessage) (platformmcpdomain.Result, error) {
			scope, err := r.loadScope(ctx, sess)
			if err != nil {
				return errorResult(err.Error()), nil
			}
			var req struct {
				SubmissionID int64  `json:"submission_id"`
				Success      bool   `json:"success"`
				CommitSHA    string `json:"commit_sha"`
				Error        string `json:"error"`
			}
			if err := unmarshalArgs(args, &req); err != nil {
				return errorResult("invalid arguments: " + err.Error()), nil
			}
			if req.SubmissionID <= 0 {
				return errorResult("submission_id is required and must be positive"), nil
			}

			patch, err := r.deps.Patches.GetPatch(ctx, req.SubmissionID)
			if err != nil {
				return errorResult("get patch: " + err.Error()), nil
			}
			if patch.IssueID != scope.issue.ID {
				return errorResult("patch does not belong to the current issue"), nil
			}
			if patch.Status != issuedomain.PatchStatusApplying {
				return errorResult(fmt.Sprintf("patch is not 'applying' (current: '%s')", patch.Status)), nil
			}

			if req.Success {
				commitSHA := strings.TrimSpace(req.CommitSHA)
				if commitSHA == "" {
					return errorResult("commit_sha is required when success=true"), nil
				}
				updated, err := r.deps.Patches.UpdatePatchStatus(ctx, patch.ID, issuedomain.PatchStatusApplied, commitSHA, "")
				if err != nil {
					return errorResult("update patch status: " + err.Error()), nil
				}
				// Update issue head SHA.
				_ = r.deps.Issues.UpdateHeadSHA(ctx, scope.issue.ID, commitSHA)

				// Write timeline event.
				payload, _ := json.Marshal(issuedomain.PatchEventPayload{
					SubmissionID: updated.ID,
					Title:        updated.Title,
					AgentRole:    updated.AgentRole,
					CommitSHA:    commitSHA,
				})
				_, _ = r.deps.Issues.CreateAgentEvent(ctx, scope.issue.ID, issuedomain.EventPatchApplied, payload, sess.RoleKey)

				return textResult(map[string]any{
					"id":          updated.ID,
					"status":      string(updated.Status),
					"commit_sha":  commitSHA,
					"applied_at":  stableTime(*updated.AppliedAt),
				}), nil
			}

			// Failure: record the error but leave status as 'applying' so it
			// can be retried. Use UpdateApplyError for the error field.
			applyErr := strings.TrimSpace(req.Error)
			if applyErr == "" {
				applyErr = "unknown apply error"
			}
			if err := r.deps.Patches.UpdateApplyError(ctx, patch.ID, applyErr); err != nil {
				return errorResult("update apply error: " + err.Error()), nil
			}
			// Re-fetch to get updated state.
			updated, _ := r.deps.Patches.GetPatch(ctx, patch.ID)

			return textResult(map[string]any{
				"id":     updated.ID,
				"status": string(updated.Status),
				"error":  updated.ApplyError,
			}), nil
		},
	}
}

// parsePatchStats extracts file stats from a unified diff. Returns
// changed_paths, file_count, additions, deletions. Best-effort: on
// parse failure returns zero values so the patch is still recorded.
func parsePatchStats(patch string) (paths []string, fileCount, additions, deletions int32) {
	lines := strings.Split(patch, "\n")
	seenPaths := make(map[string]struct{})
	for _, line := range lines {
		if strings.HasPrefix(line, "+++ ") || strings.HasPrefix(line, "--- ") {
			// Extract filename from "+++ b/path" or "--- a/path"
			parts := strings.SplitN(line, "/", 2)
			if len(parts) == 2 {
				p := parts[1]
				if p != "" && p != "/dev/null" {
					if _, ok := seenPaths[p]; !ok {
						seenPaths[p] = struct{}{}
						paths = append(paths, p)
					}
				}
			}
		}
		if strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "+++") {
			additions++
		}
		if strings.HasPrefix(line, "-") && !strings.HasPrefix(line, "---") {
			deletions++
		}
	}
	fileCount = int32(len(paths))
	return
}

// resolveWorkspacePath validates that the given path is a workspace-relative
// path (not absolute) and resolves it to an absolute path anchored to the
// workspace root. Returns an error if the path is absolute, attempts to
// escape the workspace root via "..", or cannot be resolved.
func resolveWorkspacePath(workspaceRoot, p string) (string, error) {
	p = filepath.Clean(p)
	if filepath.IsAbs(p) {
		return "", fmt.Errorf("absolute paths are not allowed")
	}
	resolved := filepath.Join(workspaceRoot, p)
	// filepath.Join + Clean handles ".." but we double-check we're still
	// inside the workspace root (no symlink traversal here; symlinks
	// require platform-level controls or os.Readdir).
	rel, err := filepath.Rel(workspaceRoot, resolved)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("path escapes workspace root")
	}
	return resolved, nil
}


func patchSummary(p *issuedomain.PatchSubmission) map[string]any {
	return map[string]any{
		"id":                p.ID,
		"issue_id":          p.IssueID,
		"session_id":        p.SessionID,
		"agent_role":        p.AgentRole,
		"title":             p.Title,
		"description":       p.Description,
		"base_head_sha":     p.BaseHeadSHA,
		"status":            string(p.Status),
		"patch_count":       p.PatchCount,
		"file_count":        p.FileCount,
		"additions":         p.Additions,
		"deletions":         p.Deletions,
		"changed_paths":     p.ChangedPaths,
		"applied_commit_sha": p.AppliedCommitSHA,
		"rejected_reason":   p.RejectedReason,
		"apply_error":       p.ApplyError,
		"created_at":        stableTime(p.CreatedAt),
		"updated_at":        stableTime(p.UpdatedAt),
	}
}
